### ISSUE TITLE
Velocity slow after long duration

### ISSUE THREAD

**Issue by Press22300** [PaperMC/Velocity#1006]
I've a +400 connected players server, and since build #250, Velocity up to +600% CPU consumption and I've to restart it each week. If I don't, he create a lot of ping for all connected players.

Don't hesitate to contact me via Discord: Press#0001

Thanks !

**Comment by Camotoy** [comment]
A Spark report would be most helpful in debugging this issue.

**Comment by Press22300** [comment]
hey, seems like patched on #252 update, thanks !
