### ISSUE TITLE
Can't connect with 1.19.2

### ISSUE THREAD

**Issue by Dandraghas** [PaperMC/Velocity#1011]
hi, when i tried connecting with 1.19.2 i get this error:

```
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "qusa.alint, qx)" because the return value of "java.util.Map.get(Object)" is null.
```

first i was thinking that something wrong with viabackwards, but then i created a new backend 1.19.2 server without viabackwards but again same error

even when all backend server is shutdown i get this error which is strange.

i tried other versions like 1.18 and it works just fine.

so looks like its issue with velocity.

also if i try to join with modified client(quilt/fabric) i get this error:
```
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2539$class_4532.method_22310(int, net.minecraft.class_2540)" because the return value of "java.util.Map.get(Object)" is null
```

im using latest 3.2.0-SNAPSHOT 256

**Comment by Warriorrrr** [comment]
Do you have any plugins on your proxy? If so, try reproducing without them if you haven't already since it's likely caused by one of them. The full log would also be useful to have.

**Comment by Dandraghas** [comment]
> Do you have any plugins on your proxy? If so, try reproducing without them if you haven't already since it's likely caused by one of them.

i alerady tried still same error

> The full log would also be useful to have.

full log of client? its a client errors i dont have any errors in velocity console at all.

**Comment by electronicboy** [comment]
You'd need to check the client logs, but, afaik, this was actually a client bug, but not 100% sure

**Comment by Dandraghas** [comment]
i recreated client version now everything works fine.
