### ISSUE TITLE
Switching servers between velocity causes the cape and skin overlays to disappear.

### ISSUE THREAD

**Issue by Zyrenth** [PaperMC/Velocity#1015]
Before switching servers: 
![image](https://github.com/PaperMC/Velocity/assets/71086259/5b379391-f0de-437a-b69e-2a02f5c6f993)

And after switching servers:
![image](https://github.com/PaperMC/Velocity/assets/71086259/b842b61d-faea-4289-b8f7-9c6454c76911)

This is visible to everyone on the server, not just the client side.
And if we go into the options screen, it will load the additional skin layer and cape for the player, and this also appears to everyone.

I searched through the config file if it's some sort of setting but I found nothing that could relate to this issue.

I'm running the latest 3.2.0-SNAPSHOT (Build `#256`) version of velocity.

**Comment by powercasgamer** [comment]
Can you share the output of `/velocity dump` here and try to reproduce it on a clean install of Paper and Velocity

**Comment by Zyrenth** [comment]
> Can you share the output of `/velocity dump` here and try to reproduce it on a clean install of Paper and Velocity

Here is the dump as you requested, and I'll try to reproduce it on a clean install.

[velocity-dump-2023-06-01-13-38-50.json.txt](https://github.com/PaperMC/Velocity/files/11625929/velocity-dump-2023-06-01-13-38-50.json.txt)

**Comment by Zyrenth** [comment]
I did a complete clean install of velocity and paper and successfully reproduced it.
Here are the config files of the clean install:
- Velocity:
  - [velocity.toml.txt](https://github.com/PaperMC/Velocity/files/11626073/velocity.toml.txt)
  - [velocity-dump-2023-06-01-15-55-52.json.txt](https://github.com/PaperMC/Velocity/files/11626116/velocity-dump-2023-06-01-15-55-52.json.txt)
- Server1:
  - [server.properties.txt](https://github.com/PaperMC/Velocity/files/11626080/server.properties.txt)
  - [paper-global.yml.txt](https://github.com/PaperMC/Velocity/files/11626089/paper-global.yml.txt)
- Server2:
  - [server.properties.txt](https://github.com/PaperMC/Velocity/files/11626095/server.properties.txt)
  - [paper-global.yml.txt](https://github.com/PaperMC/Velocity/files/11626097/paper-global.yml.txt)

If you need other config files I can provide you with those as well.

**Comment by Kamil02167** [comment]
I would like to add that, at least with me, this only occurs in players with Forge clients.

**Comment by 4drian3d** [comment]
I have not been able to reproduce the bug using Vanilla, Forge or Fabric in version 1.20.4, could you please give details of which version the bug occurs in?

**Comment by Zyrenth** [comment]
The server version was on 1.19.1 (Paper) but I don't really remember about the forge version (other than it was on 1.19.1) since I paused the development on that project almost 4 months ago. But I know it only occurred on modded versions as @CrazyWorldPL mentioned.

**Comment by miosenpai** [comment]
I ran into this bug with Forge on 1.20.1 and Velocity snapshot 265, but I stopped being able to repro the bug on snapshot 294.

**Comment by 4drian3d** [comment]
I can confirm by testing on these versions that the bug is no longer reproducible, thanks

**Comment by DefomCode** [comment]
I have exactly the same mistake right now.
