### ISSUE TITLE
Get Error When Im Connecting

### ISSUE THREAD

**Issue by MahdiHoseyniBeheshtian** [PaperMC/Velocity#1017]
Hello
I get an error when I try to connect to the server
Although all the configurations are correct
error:

unable to connect lobby : unable to verify player details

**Comment by electronicboy** [comment]
This is generally due to the secret not being properly configured between the proxy and the server, please use the discord for support

**Comment by MahdiHoseyniBeheshtian** [comment]
How can i fix it?
