### ISSUE TITLE
CorruptedFrameException

### ISSUE THREAD

**Issue by alexanderdidio** [PaperMC/Velocity#1019]
Randomly when new players try to join, they get this error https://mcpaste.io/34de884e4d428d4d which prevents any new players from being able to join. The only way to allow these players to join without the errors blocking them and without restarting the server, is to find and kick a specific player that's already on the spigot server (or send them to a different one).

I've tried removing all of my spigot plugins and this issue persists. This was not a problem pre-1.20 update.

Velocity dump: https://paste.wqrld.net/uguximanej.json

**Comment by electronicboy** [comment]
This isn't a velocity issue, the part you left out is the plugins on the proxy, and the fact that the connecting account is not a valid java account. 2 second search suggests that this is a geyser issue that has been patched already.
