### ISSUE TITLE
How do I send a command on behalf of the console?

### ISSUE THREAD

**Issue by Primer2022** [PaperMC/Velocity#1028]
How do I send a command on behalf of the console?

**Comment by hugmanrique** [comment]
First, we get the `ConsoleCommandSource` (https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/proxy/ConsoleCommandSource.html) via https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/proxy/ProxyServer.html#getConsoleCommandSource()
.
Next obtain the `CommandManager` (https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/proxy/ProxyServer.html#getCommandManager()) via the similarly named getter on `ProxyServer`. Finally use `CommandManager#executeAsync` (https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/command/CommandManager.html#executeAsync(com.velocitypowered.api.command.CommandSource,java.lang.String)). Don't forget to handle the future exceptions.

For more questions regarding API usage, please use the Discord server. This is an issue tracker.
