### ISSUE TITLE
skin forwarding 1.16.5

### ISSUE THREAD

**Issue by Wonkiest29** [PaperMC/Velocity#1032]
when i join to lobby all okay
 when moving to another server  top skin and cape removed but when i open setting skins and nothing change normall skin back
velocity version 3.2.0 snapshot
paper version  794 (1.16.5) # server
client forge 1.16.5 - 36.2.39
![image](https://github.com/PaperMC/Velocity/assets/88631273/315c21c9-65d2-40ba-979d-809d95dab988)
![image](https://github.com/PaperMC/Velocity/assets/88631273/7fd632e5-8e03-4656-b0ee-71e9919647d5)

thats all maybe

**Comment by Nacioszeczek** [comment]
I'll be closing this as it seems like a duplicate of #1015.
