### ISSUE TITLE
Unable to connect you to <server-name>. Please try again later.

### ISSUE THREAD

**Issue by Mr-Rene** [PaperMC/Velocity#1033]
Hello, I have a problem with not being able to connect to my server even after successfully setting up Velocity.toml, I have done all the necessary steps to successfully connect to the server but I still can't connect to the server and it says Unable to connect you to epiclands. Please try again later. How do I fix the error? Thank you in advance for your help

**Comment by electronicboy** [comment]
The issue tracker is not the place for support, please use the discord or the forums
