### ISSUE TITLE
Lags too much

### ISSUE THREAD

**Issue by iambeingtracked** [PaperMC/Velocity#1041]
Hello,

I have both my Pufferfish server and Velocity ran on one local network, different local ips, and also put outside via DMZ:
```
[servers]
# Configure your servers here. Each key represents the server's name, and the value
# represents the IP address of the server to connect to.
vanilla = "192.168.0.235:25565"

# In what order we should try servers when a player logs in or is kicked from a server.
try = [
    "vanilla"
]

[forced-hosts]
# Configure your forced hosts here.
"mc.domain.tld" = [
    "vanilla"
]
```

Velocity version: 3.2.0-SNAPSHOT
Build number 260

The resources I've allocated are more than enough. I gave 2 gigs to Velocity and 6 gigs to Pufferfish.

And it lags a lot. I started using Velocity because I wanted to properly give public IPs to the server, before that I used nginx as a reverse proxy and there was no lag.

The logs say nothing about it, I only occasionally get the "1vyrain moved too quickly" thing on the Pufferfish server.

The issue might be because the whole network is on 100mb/sec and not 1000mb/sec, but without the proxy it worked fine (although I tested it like a week ago, should I try it without the proxy again?)

Here is what that lag is: https://files.wherelinux.xyz/thing.mkv

**Comment by iambeingtracked** [comment]
UPD: Restarted it a couple of times and it didn't lag near that outpost that much, however I tried looting an ancient city and the lag is still there, weird things happen, though the server isn't overloaded at all, I mean, it's only me playing


And it doesn't lag like so when behing NGINX

**Comment by iambeingtracked** [comment]
I tried disabling caching on the side of Pufferfish and I feel like it only became worse

And I feel like it only happens when there are a lot of entities involved


More than that the lag causes a ping spike, the TPS is at it should be, but the ping skyrockets

**Comment by iambeingtracked** [comment]
At one point it just disappeared and everything was alright. Now after a few days I have this problem again

**Comment by iambeingtracked** [comment]
It seems really unstable, sometimes the problem is there, sometimes it isn't. I feel like it starts happening in the morning and gets alright till the afternoon, not sure though

**Comment by Onako2** [comment]
Could you compress the video? I am at the moment in a metered network. Thanks

**Comment by iambeingtracked** [comment]
Sure, just make sure to download it as it doesn't show the video in the browser for some reason (probably an mp4 skill issue) https://files.wherelinux.xyz/output.mp4


To add to this, seems like it's fine if I don't let the server be down for a long time and also not letting it run for too much (i.e. rebooting it in time)

**Comment by Nacioszeczek** [comment]
Please [install spark](https://spark.lucko.me/download) on both the proxy and backend servers and send a profile here. This isn't really something we can reproduce on our own.

**Comment by iambeingtracked** [comment]
Okay, when this issue pops up again I'll post it

**Comment by Nacioszeczek** [comment]
I'll close this issue until then, you will still be able to reply here and we'll reopen it if you do. Thanks!
