### ISSUE TITLE
players unable to join with a error

### ISSUE THREAD

**Issue by shawn695** [PaperMC/Velocity#1044]
sometimes randomly player would get this error when trying to join. sometimes after 5-10 mins they are able to get it. Players could be already online while others get that ERROR

20.07 21:21:54 [Server] ERROR [server connection] KikiTheGame9444 -> Main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@649122e1
20.07 21:21:54 [Server] INFO com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
20.07 21:21:54 [Server] INFO [connected player] KikiTheGame9444 (/99.254.172.70:63012) has disconnected: Your connection to Main encountered a problem.

[latest.log](https://github.com/PaperMC/Velocity/files/12114285/latest.log)

**Comment by shawn695** [comment]
happens a few times a day player DC

22.07 18:28:04 [Server] INFO [server connection] .AntiJoker420 -> Main has connected
22.07 18:28:14 [Server] ERROR [server connection] Blazzin0420 -> Main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@7930829c
22.07 18:28:14 [Server] INFO com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
22.07 18:28:14 [Server] ERROR [server connection] Masterriff -> Main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@184d45f8
22.07 18:28:14 [Server] INFO com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
22.07 18:28:14 [Server] INFO [connected player] Blazzin0420 (/184.147.172.195:50149) has disconnected: Your connection to Main encountered a problem.
22.07 18:28:14 [Server] INFO [connected player] Masterriff (/96.41.142.221:60197) has disconnected: Your connection to Main encountered a problem.
22.07 18:28:14 [Server] INFO [server connection] Blazzin0420 -> Main has disconnected
22.07 18:28:14 [Server] INFO [server connection] Masterriff -> Main has disconnected
22.07 18:28:14 [Server] ERROR [server connection] KikiTheGame9444 -> Main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@63d02a5a
22.07 18:28:14 [Server] INFO com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.

**Comment by electronicboy** [comment]
all we can see is that you got a bad packet, you'd nee to run with the flag it says to be able to get more info

**Comment by shawn695** [comment]
i cant see where to turn that flag on ?

**Comment by shawn695** [comment]
nvm i had to get apexhosting to add it, will post errors when it happens again

**Comment by shawn695** [comment]
24.07 17:34:28 [Server] ERROR [server connection] KikiTheGame9444 -> Main: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@239843f6
24.07 17:34:28 [Server] INFO io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo Direction CLIENTBOUND Protocol 1.20 State PLAY ID 3a
24.07 17:34:28 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
24.07 17:34:28 [Server] INFO Caused by: io.netty.handler.codec.CorruptedFrameException: Bad VarInt decoded
24.07 17:34:28 [Server] INFO at com.velocitypowered.proxy.protocol.ProtocolUtils.readVarInt(ProtocolUtils.java:86) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo$Action.lambda$static$4(UpsertPlayerInfo.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo.decode(UpsertPlayerInfo.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
24.07 17:34:28 [Server] INFO ... 28 more

**Comment by shawn695** [comment]
here we go, setting enabled with the same issue this link is good for 30 days Proxy server logs with the error
https://mclo.gs/nbqXSKP

**Comment by electronicboy** [comment]
Something is apparently mangling player info packets, advice is generally gonna be to start yanking plugins
