### ISSUE TITLE
Sync Commands

### ISSUE THREAD

**Issue by dlldotusha** [PaperMC/Velocity#1048]
There are plugins that help to synchronize commands between servers. Such as https://www.spigotmc.org/resources/commandsync.115/

**Comment by electronicboy** [comment]
I fail to understand how this is a velocity issue; if you're asking for somebody to make such a plugin, i'd suggest asking in the relevant places

**Comment by dlldotusha** [comment]
Add it to velocity

**Comment by electronicboy** [comment]
No. Such a feature would go against the project design goals of velocity, that is something trivially implementable in a plugin.

**Comment by dlldotusha** [comment]
Not multifunctional, but beautiful? Ok

**Comment by dlldotusha** [comment]
+Plugins work terribly

**Comment by electronicboy** [comment]
We have enough to do as-is, we don't want Velocity to be a piece of software which is the software itself, bundled with 20 dozen low-quality plugin-level stuff used by a small % of users which would need to be replaced by anybody who wanted to use such a feature in any other environment than a basic setup.

> Plugins work terribly

that statement literally makes 0 sense, anything we could do for such a feature would be doable in a plugin and vice versa, you are literally asking for somebody to bake in a plugin for a different platform into this software.

Either way, this is doable with a plugin and not something we desire to implement into the proxy itself.

**Comment by dlldotusha** [comment]
It turns out you are lazy, and you have things to do?

**Comment by electronicboy** [comment]
You are not entitled to our time or effort, nor does this feature align with our project goals. This is easily implementable in a plugin.

**Comment by 4drian3d** [comment]
> There are plugins that help to synchronize commands between servers. Such as https://www.spigotmc.org/resources/commandsync.115/

There are already plugins that do that in Velocity, why do you want it integrated into Velocity itself?

**Comment by electronicboy** [comment]
They've been org banned, if your response to "I don't believe this feature lines up with the goals of the project" is to just start insulting members of the team, I see little reason for them to be around if they're not going to have an actual discussion.
