### ISSUE TITLE
Using a Custom Session URL

### ISSUE THREAD

**Issue by Hadimhz** [PaperMC/Velocity#1051]
I'm trying to use a custom session URL for my velocity rather than the default mojang one.

After some digging in the source I found the System Property `mojang.sessionserver` over at [InitialLoginSessionHandler](https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/connection/client/InitialLoginSessionHandler.java) but it seems to throw a `java.lang.ClassNotFoundException`

Here's the startup flag i tried to use.
`
java -Xms128M -Dmojang.sessionserver="https://sessionserver.mojang.com/session/minecraft/hasJoined" -jar velocity.jar`

error:
```
Error: Could not find or load main class .sessionserver=https:..sessionserver.mojang.com.session.minecraft.hasJoined
Caused by: java.lang.ClassNotFoundException: /sessionserver=https://sessionserver/mojang/com/session/minecraft/hasJoined
```

**Comment by e-im** [comment]
this is an issue with your shell. smells like something windows. try putting the first `"` before the `-D`, so ` java -Xms128M "-Dmojang.sessionserver=https://sessionserver.mojang.com/session/minecraft/hasJoined" -jar velocity.jar`

**Comment by Hadimhz** [comment]
Yeah, someone on discord told me the same, i used cmd and it worked, thanks a lot <3
