### ISSUE TITLE
Add a server check method to online

### ISSUE THREAD

**Issue by kainlighty** [PaperMC/Velocity#1052]
You already have the server.ping method, which, if it does not give errors, then you can execute certain code with `thenRun`, and if the server is turned off (that is, an exception is thrown, then nothing will happen). So, I didn't find the boolean method, so I suggest adding this little function. Eg:
proxy.getServer("test").isOnline.

If I write this in the scheduler, I can perform certain actions as soon as the server is turned on and if it is turned off, it will return false and something can also be done. At the moment it works for me as (example):
```
proxy.getServer("test").get().ping.thenRun(() -> {
System.out.println("Server test enabled");
}).exceptionally(e -> {
System.out.println("Server test disabled");
})
```

And it could be:
```
if(proxy.getServer("test").isOnline) {
System.out.println("Server test enabled");
} else {
System.out.println("Server test disabled");
}
```

**Or maybe there is some simpler method at the moment for such an operation?**

**Comment by electronicboy** [comment]
You can already do this with ping? if not, that would be a bug; There is no real need for us to try to add something that would basically just be a glorified util wrapper for that call
