### ISSUE TITLE
Velocity PlayerChatEvent cannot retrieve the command sent by the player.

### ISSUE THREAD

**Issue by 3154311518** [PaperMC/Velocity#1054]
Velocity PlayerChatEvent cannot retrieve the command sent by the player.

For example, in the current code:
public void onChat(PlayerChatEvent event) {
    System.out.println(event.getMessage());
}
If the player sends "HI," it will print "HI."
If the player sends "/say HI," it will not print anything.

In WaterFall's ChatEvent, the command will be printed.
In Velocity's PlayerChatEvent, the command won't be printed, only the message can be printed.

**Comment by powercasgamer** [comment]
https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/command/CommandExecuteEvent.html

**Comment by 3154311518** [comment]
> [https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/command/CommandExecuteEvent.html ](https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/command/CommandExecuteEvent.html)

How to include the first slash.

**Comment by Xernium** [comment]
> > [https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/command/CommandExecuteEvent.html ](https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/command/CommandExecuteEvent.html)
> 
> How to include the first slash.

If you need it then you'll have to add it yourself. We purposefully don't provide the full command in this event because it encourages bad practices like not registering the commands you want to add through the api
