### ISSUE TITLE
Player Forwarding Error

### ISSUE THREAD

**Issue by MnLand** [PaperMC/Velocity#1061]
![image](https://github.com/PaperMC/Velocity/assets/141953534/2f5307e0-0111-4055-b3d7-222eff932fab)
Velocity 3.2.0-SNAPSHOT
Player Forwarding: Modern

**Comment by electronicboy** [comment]
Don't enable bungeecord mode if you're not using legacy forwarding.

**Comment by MnLand** [comment]
in spigot.yml on paper server?

**Comment by MnLand** [comment]
I turned off bungeecord and nothing changed

**Comment by electronicboy** [comment]
That error is explicitly caused by bungeecord mode (in spigot.yml) being enabled, make sure that you properly restart the server when changing that stuff

**Comment by MnLand** [comment]
I rechecked and rebooted all servers

**Comment by MnLand** [comment]
nothing

**Comment by electronicboy** [comment]
Please use the discord/forums for support, your issue is not coming from velocity but your backend server
