### ISSUE TITLE
Bungeecord messaging channel doesn't work on servers running 1.20.1

### ISSUE THREAD

**Issue by Pyrbu** [PaperMC/Velocity#1065]
This is the code I'm using to send the plugin messages:
```java
public class BungeeProtocolWrapper {
    private final static String CHANNEL_NAME = "bungeecord:main";

    private final DataSyncherPlugin plugin;

    public BungeeProtocolWrapper(DataSyncherPlugin plugin) {
        this.plugin = plugin;
        init();
    }

    public void init() {
        Bukkit.getMessenger().registerOutgoingPluginChannel(plugin, CHANNEL_NAME);
    }

    public void shutdown() {
        Bukkit.getMessenger().unregisterOutgoingPluginChannel(plugin, CHANNEL_NAME);
    }

    public void connectPlayer(Player player, String server) {
        player.sendPluginMessage(plugin, CHANNEL_NAME, createMessage("Connect", server));
    }

    @SuppressWarnings("UnstableApiUsage")
    private byte[] createMessage(String... parts) {
        ByteArrayDataOutput out = ByteStreams.newDataOutput();
        for (String part : parts) out.writeUTF(part);
        return out.toByteArray();
    }
}
```
This also doesn't seem to be related to #1062 since it's also broken on build 263
I have also tried registering the `bungeecord:main` channel in a velocity plugin to the channel registry but that did nothing

**Comment by electronicboy** [comment]
not a velocity issue is what I'd imagine based on the code shown, you need to use the channel BungeeCord or whatever it was, they have a hack which will screw up if you try to use the "modern" name

**Comment by Pyrbu** [comment]
> not a velocity issue is what I'd imagine based on the code shown, you need to use the channel BungeeCord or whatever it was, they have a hack which will screw up if you try to use the "modern" name

I have already tried using the `BungeeCord` channel name too and it doesn't work either
I also have an open-source plugin where the messaging worked but was magically broken when updating to 1.20.1

**Comment by electronicboy** [comment]
I'll re open this in the meanwhile as I'm too dead to follow up, but this is somewhat unlikely to be on velocities side, would more generally be wondering where you're sending the thing from

**Comment by Pyrbu** [comment]
I was using a Purpur server but I just tested it on the latest build of Paper (153) and it is also broken

**Comment by powercasgamer** [comment]
Can you double check that you don’t have [this](https://github.com/PaperMC/Velocity/blob/19abb9094e581bc4d21107e839901e5d68090b19/proxy/src/main/resources/default-velocity.toml#L123) set to false?

**Comment by Pyrbu** [comment]
I have also already checked that and it is set to true:
![image](https://github.com/PaperMC/Velocity/assets/75636092/54302ea8-6379-4936-b56f-1bd6a76f13e4)

**Comment by Pyrbu** [comment]
I just tried sending a raw plugin message packet from the server and it worked so it's not a Velocity bug, I'll do some more digging and if it ends up being a bug and not me being stupid I'll report it to the right place
