### ISSUE TITLE
No Component/kick message when denying PreLoginEvent

### ISSUE THREAD

**Issue by daniel-skopek** [PaperMC/Velocity#1066]
If I deny PreLoginEvent, the player will not connect, but it will show Connecting to the server... and after a while Timed out message instead of the intended kick message.

Code:
`	@Subscribe
	public void onPlayerLogin(PreLoginEvent e) {
		e.setResult(PreLoginEvent.PreLoginComponentResult.denied(Component.text("§cThis message will not show up")));
	}`

Velocity version: 3.2.0-SNAPSHOT (git-fc85fb05)
Client: 1.20.1

The Velocity server is not behind TCPShield or any other proxy.

I have similar problem as https://github.com/PaperMC/Velocity/issues/689.

When I set PostOrder to last in the event, it just works. Is there any reason why it doesn't work with default PostOrder?

**Comment by A248** [comment]
> When I set PostOrder to last in the event, it just works. Is there any reason why it doesn't work with default PostOrder?

Velocity's behavior does not change depending on when you modify the event -- that is, no matter the PostOrder.

You may have another plugin interfering. Test without any other plugins installed.

**Comment by Nacioszeczek** [comment]
Please do not open new issues when one already exists, in the future reply in the old issue instead and we would've reopened it if valid (I'm talking about #992).

I still cannot reproduce this, like A248 said, if you have plugins then remove them and try again or just keep using the PostOrder.
If you need help with making a plugin for Velocity or Velocity itself feel free to ask in our [Discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io/forums/).
