### ISSUE TITLE
Client crash when switching servers

### ISSUE THREAD

**Issue by FnTlv** [PaperMC/Velocity#1071]
version information:
* velocity-3.2.0-SNAPSHOT-265.jar
* client: 1.7.10-10.13.4.1614-1.7.10
* server: Crucible-1.7.10-staging-81fcb90b-server.jar

This is the crash log.
https://pastes.dev/TnTaK81KOC
He's got a chance of it happening, not a 100% chance of it happening.

**Comment by Xernium** [comment]
We can't fix issues exclusive to Forge. Velocity works with modded setups to the best of its ability but anything outside that is mostly outside of our control, sorry. Especially considering how old your version is, you'd need an expert in both forge and the old mods that may cause this to even remotely diagnose your issue
