### ISSUE TITLE
Change auth server Yggdrasil

### ISSUE THREAD

**Issue by Asuniia** [PaperMC/Velocity#1074]
How to change authentication official servers to Yggdrasil external authentication servers.

 As on Paper mc with JVM arguments :

-Dminecraft.api.auth.host=http://localhost/auth
-Dminecraft.api.account.host=http://localhost/account
-Dminecraft.api.session.host=http://localhost/session
-Dminecraft.api.services.host=http://localhost/services

**Comment by Xernium** [comment]
Velocity only uses one API endpoint which can be specified using:
```
-Dmojang.sessionserver=“https://sessionserver.mojang.com/session/minecraft/hasJoined“
```
