### ISSUE TITLE
Support RGB / Hex colors in console

### ISSUE THREAD

**Issue by Ecconia** [PaperMC/Velocity#1075]
# Topic / Request:

RGB-JSON-Text and how it currently does not end up in Velocity console as expected.

A request to make it possible to print RGB colors to Velocity console.

## How Velocity (3.2.0) currently works:

Velocity itself does support RGB JSON-Text properly by making use of the [Adventure Framework](https://github.com/KyoriPowered/adventure).
Modders can send Adventure Components to players and the console (and more).

As for players, Minecraft takes care of color and formatting handling.
This is not the case for the console - Velocity has to take care of that.

Velocity uses one of the Adventure Framework's serializers, specifically the Legacy serializer, which will convert `named colors` to the legacy color codes `§0 - §f`. All RGB colors will be mapped to one of the 16 default Minecraft colors.
The output gets printed via the `log4j` frameworks Logger.

The logging framework configuration file makes heavy use of [TerminalConsoleAppender](https://github.com/Minecrell/TerminalConsoleAppender), which also provides a formatter to convert legacy Minecraft color codes to ANSI codes - which make text colorful and formatted in console.

## Request / Issue:

Due to how Velocity processes colors right now. Only named colors are printed in console.

There are two disadvantages of not supporting RGB in console:
- The legacy ANSI handling of the MC space uses the ANSI codes `3X`, that are only 8 colors. The old ANSI mapper always make the brighter 8 colors bold, due to a lack of colors.
- More and more modders make use of the RGB colors, if they do not work in console, that is simply annoying.

As these days most terminals support RGB colors in several formats on all platforms, it is a feature that has to be implemented eventually.

There exist ANSI codes `9X` which are brighter than the `3X` colors. If one uses both, there is no need to break the formatting by making the brighter 8 colors bold.

## Naive suggestion on how to implement this (skip to next suggestion if you like):

Most terminals do support all ANSI color types, but some older ones don't.
To prevent current terminals from breaking the new coloring system should be opt-in.

The current legacy serializer supports exporting hex colors in the form `§x§r§r§g§g§b§b`, which seems to be some BungeeCord or Spigot thing. This format is good, because it can be fully removed by the regex `§.`. But it is bloated.

The current [ANSI formatter](https://github.com/Minecrell/TerminalConsoleAppender/blob/master/src/main/java/net/minecrell/terminalconsole/MinecraftFormattingConverter.java#L72) is Deprecated, as it does not belong into the project it is in.
It is recommended to copy it and adjust it where needed.

One could implement it in Velocity and simply changes the logging configuration file to use the custom one.

The custom ANSI formatter then could replace the `§x§r§r§g§g§b§b` hex code with an ANSI representation, along with the other formattings.

Pro's & Con's:
- `+` The logger will be even more powerful, as in that it now supports RGB colors and the `bold` style can be removed with actual bright colors.
- `-` Implementation is depending on what `log4j` does.
- `-` Maintaining support of different terminals is tricky.

## Much better suggestion on how to implement this feature:

In the ideal case, Velocity (or its frameworks) would be able to check if ANSI colors are supported and appropriately chooses the right color mode and there will be a manual overwrite for that color mode.

On the Paper Discord server I got a pointer, that Paper is apparently using the [adventure framework to serialize directly to ANSI](https://github.com/kyoripowered/ansi).

Using this framework is an easy solution, that brings most of these features.

Pro's & Con's:
- `+` Detecting console color support automatically
- `+` Overwrite of color mode (with startup system property argument)
- `+` RGB and normal colors
- `+` Maintenance delegated to a framework, that is already being used
- `-` Loggers won't support new legacy RGB colors codes (or any legacy colors codes, if formatter gets removed) 

In general the ANSI formatting responsibility is taken from the Logging framework with this change.
This should be okay, as the loggers normally take strings as input. And if modders want to use Components, they have to use serializers anyway. They can easily also serialize to ANSI.

If the component framework is not used, modders still can send raw ANSI codes into the logger.

I have no opinion on, if the current MC-to-ANSI logger formatter should be removed or kept.
Both systems can co-exist. The ANSI log formatter won't have to do anything though.

### 4 Lines for a PR:

Depend on the ANSI serializer:
`adventure-ansi = "net.kyori:adventure-text-serializer-ansi:4.14.0"`
`implementation(libs.adventure.ansi)`
Use the ANSI serializer (replacing 2 other lines):
`import net.kyori.adventure.text.serializer.ansi.ANSIComponentSerializer;`
`logger.info(ANSIComponentSerializer.ansi().serialize(translated));`

^ With that much effort, I am not really sure why one would not want to do the upgrade :)

-> But this issues is for discussing this change:
Is this a good option, are there any downsides?
Should the implementation be changed?
Do some instructions or notes have to be added somewhere? (This system runs on its own).

**Comment by 4drian3d** [comment]
> ### 4 Lines for a PR:
> Depend on the ANSI serializer: `adventure-ansi = "net.kyori:adventure-text-serializer-ansi:4.14.0"` `implementation(libs.adventure.ansi)` Use the ANSI serializer (replacing 2 other lines): `import net.kyori.adventure.text.serializer.ansi.ANSIComponentSerializer;` `logger.info(ANSIComponentSerializer.ansi().serialize(translated));`
> 
> ^ With that much effort, I am not really sure why one would not want to do the upgrade :)
> 
> -> But this issues is for discussing this change: Is this a good option, are there any downsides? Should the implementation be changed? Do some instructions or notes have to be added somewhere? (This system runs on its own).

~~Using the AnsiComponentSerializer instead of the LegacyComponentSerializer to log messages in console would be the easiest thing to do. But the ideal would be to implement Adventure's ComponentLogger as it was implemented in Paper. I have tried to implement it in the pull request https://github.com/PaperMC/Velocity/pull/1022 but I have not been able to finish it because it requires to update the slf4j version to 2.x which breaks the logger setup in Velocity which I have not been able to fix~~
https://github.com/PaperMC/Velocity/pull/1022

**Comment by Ecconia** [comment]
A few other contributors suggested, to use Component Loggers, but in the end these will also have to use the ANSI serializer.

It just moves the serialization to a different position, but effectively the result and the key arguments stay the same.
With the bonus of being able to create loggers that serialize components automatically. But that is a different feature (request).

Although I did not look into the component logger class, I assume it will need a manual serialization implementation, as that must be defined manually.

**Comment by 4drian3d** [comment]
Implemented in #1022
