### ISSUE TITLE
Player is kicked when cancelling PlayerChatEvent

### ISSUE THREAD

**Issue by Tobias123567** [PaperMC/Velocity#1079]
When i set the result of PlayerChatEvent to denied, the player is kicked
![Screenshot_14](https://github.com/PaperMC/Velocity/assets/42582100/22b949fb-e7a8-4d09-b9ac-4417dc43ebbb)

**Comment by Nacioszeczek** [comment]
Cancelling messages on the proxy is currently unsupported due to chat signing.
If you need help with making a plugin for Velocity feel free to reach out to us using our [Discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io/forums/).
