### ISSUE TITLE
Javadocs issues

### ISSUE THREAD

**Issue by ham1255** [PaperMC/Velocity#1080]
On javadocs hosted by PaperMC `https://jd.papermc.io/velocity/3.0.0/index.html`

anything that uses default java classes for example clicking `InetSocketAddress` to view it docs in [InboundConnection](https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/proxy/InboundConnection.html)

keep in mind the redirected url: 
`https://docs.oracle.com/en/java/javase/11/docs/api/java/net/InetSocketAddress.html?is-external=true`

![image](https://github.com/PaperMC/Velocity/assets/34905970/12117a2f-5c88-4991-921e-49364dc1e1ad)

so i cloned the project to generate Local javadocs to see if it also has the same issues, but it does not

this was the redirect url *the working one*: 
`https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/InetSocketAddress.html?is-external=true`

as you can see first url does not have `java.base` after `api/` in url. which weird is since generated docs on computer should be same for one on papermc javadocs

**Comment by 4drian3d** [comment]
It seems to be a problem of the jdk itself when generating the javadocs, I have tried both in other projects and in Velocity and it is the same failure, I have only been able to solve it by upgrading to Java 17

**Comment by 4drian3d** [comment]
In the latest builds of Velocity, it is no longer possible to reproduce this bug 

https://github.com/PaperMC/Velocity/assets/68704415/ffd66b84-50c2-4200-b91b-3dbae335900f
