### ISSUE TITLE
can't connect server through modern velocity proxy to paper-1.20.1 server:  This server requires you to connect with velocity

### ISSUE THREAD

**Issue by atsushifx** [PaperMC/Velocity#1081]
I use velocity to connect with modern ip-forwarding but can not connect. 
on Minecraft client send "This server requires you to connect with Velocity."
 
below is my server, proxy settings and velocity dump.

[paper-global.yml.txt](https://github.com/PaperMC/Velocity/files/12589695/paper-global.yml.txt)
[server.properties.txt](https://github.com/PaperMC/Velocity/files/12589696/server.properties.txt)
[velocity.toml.txt](https://github.com/PaperMC/Velocity/files/12589701/velocity.toml.txt)
[velocity-dump-2023-09-13-03-16-31.json.txt](https://github.com/PaperMC/Velocity/files/12589706/velocity-dump-2023-09-13-03-16-31.json.txt)

**Comment by electronicboy** [comment]
Screenshot? As that would scream that you didn't connect to velocity

**Comment by atsushifx** [comment]
I understand. 
This is screenshot of mt minecraft.

![ss-mc-01-2](https://github.com/PaperMC/Velocity/assets/98551/f02202cd-d2be-42a5-9dcf-d17caff63446)
![ss-mc-02-02](https://github.com/PaperMC/Velocity/assets/98551/92fd62fe-18e6-430c-ab44-fe1a0c56a681)

and this is latest.log

[latest.log.txt](https://github.com/PaperMC/Velocity/files/12593172/latest.log.txt)

**Comment by electronicboy** [comment]
The error is because you're connecting directly to the backend server rather than actually connecting to the proxy

**Comment by atsushifx** [comment]
but I set server.propertie's online-mode iis false, config/paper-global's proxies,velocity.enabled is true. 
these are written by velocity documents.
What were my settings wrong?

**Comment by Nacioszeczek** [comment]
You have to connect to the address of the proxy, not of the backend servers.
Please use our [Discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io/forums/) for further support.

**Comment by IAmStive222** [comment]
Please take a look, if you have a speed, then go to velocity.volume and change the string of forced authentication by key = true and in this case the truth becomes a lie, and check!
