### ISSUE TITLE
read timed out

### ISSUE THREAD

**Issue by Fe1son** [PaperMC/Velocity#1084]
This could happen at the random moment. Nobody can join the server, but those who were on the server do not kick from them. It is also not possible to stop the server (you can see it in the screenshot), just kill the process. I use neoprotect. I don't know, but maybe there's a problem with him?
![image](https://github.com/PaperMC/Velocity/assets/52543528/467cf176-310e-4784-be1f-6f726a70e59e)
![image](https://github.com/PaperMC/Velocity/assets/52543528/5fa7bedd-3b67-4423-9e71-6985054954ea)

**Comment by electronicboy** [comment]
read timed out just tells us that we didn't get any packets in 30 seconds
Your logs also indicate that you're generally running an unsupported environment, to boil anything down more, we'd need more information about your hosting environment/setup, but, this isn't particularly the place for such support

**Comment by Felson999** [comment]
> read timed out just tells us that we didn't get any packets in 30 seconds Your logs also indicate that you're generally running an unsupported environment, to boil anything down more, we'd need more information about your hosting environment/setup, but, this isn't particularly the place for such support

host: hetzner
os: Ubuntu
version Velocity: velocity-3.2.0-SNAPSHOT-265
[velocity.txt](https://github.com/PaperMC/Velocity/files/12652648/velocity.txt)
![image](https://github.com/PaperMC/Velocity/assets/52543528/23ac6ae9-08e1-4f1d-91ed-453db98cc491)

If it’s not convenient for you to discuss this here, please give your contacts.

**Comment by electronicboy** [comment]
There is a discord and a forums, however you are running an unsupported setup

**Comment by AloneYTBoY** [comment]
hello

**Comment by AloneYTBoY** [comment]
[11:27:01 ERROR]: [initial connection] /176.65.148.103:65355: read timed out
