### ISSUE TITLE
Question: Is this still active?

### ISSUE THREAD

**Issue by Mrs-Feathers** [PaperMC/Velocity#1089]
Hello! I've noticed that waterfall is getting active updates and is already supporting 1.20.2 but says it's end of life is soon and we should switch to velocity which hasn't been updated in 2 months and only supports to 1.20.2. We switched over to velocity and are noticing its no longer recieving updates. should we switch back to waterfall? or should we hold out for updates? we love how simple and fast the software is, but accedentally updated to 1.20.2 (and downgrading to 1.20.1 sadly bricks the server for some reason) without noticing velocity didn't work with this version, so its got our network broken for now and i'm not sure what to do.

**Comment by Nacioszeczek** [comment]
Support for 1.20.2 is a work-in-progress, there's no ETA.
Feel free to join our [Discord](https://discord.gg/papermc) for immediate updates.

**Comment by Mrs-Feathers** [comment]
thank you very much!
