### ISSUE TITLE
1.20.2 Compatibility

### ISSUE THREAD

**Issue by Funasitien** [PaperMC/Velocity#1093]
Hi!
I just made this issue as I think that Velocity don"t support 1.20.2 rn, and so it may need to be done

**Comment by Leguan16** [comment]
See #1088

**Comment by KoxSosen** [comment]
Hi! There is a PR ( #1088 ) that implements 1.20.2 support. It's under work, but if you want a copy of it, you can always compile Velocity using the instructions found in the [README.md](https://github.com/PaperMC/Velocity#building)  file.
