### ISSUE TITLE
Players aren't able to join proxy

### ISSUE THREAD

**Issue by thomasmny** [PaperMC/Velocity#1104]
Hello,

A small amount of our players (have had 3 incidents so far) are unable to connect to our sever. 
Whenever they try to join the server, the following error is thrown: https://paste.gg/p/anonymous/5b2894a506334024828ae5091b27af73

- Our Velocity version is `Velocity 3.2.0-SNAPSHOT (git-1cc3f120-b271)`
- We do not use ViaVersion as a proxy plugin, but as a lobby plugin. 
- The users have tried multiple versions of vanilla Minecraft, each without changing the outcome

**Comment by electronicboy** [comment]
You have a plugin sending a chat message to the client too early

**Comment by 4drian3d** [comment]
Try without plugins, I have seen that this error comes from a specific authentication plugin although it may be caused by a plugin that uses internal Velocity classes that has not been updated.

**Comment by thomasmny** [comment]
You're correct, was my fault. The plugin was trying to send a message before the player was connected. Waiting for the player to fully join works. Thanks :)
