### ISSUE TITLE
Server connection stuck at "Joining world" when connecting using 1.20.2

### ISSUE THREAD

**Issue by H4kt** [PaperMC/Velocity#1114]
## Setup:
* Velocity 3.2.0 (player-info-forwarding-mode=none, online-mode-true) [also tested with player-info-forwarding-mode=true]
* Paper 1.20.1 (gitPaper-196) (ViaVersion 3.8.1)

## Reproduction
Connecting to the server using 1.20.1 and lower works as intended.
Attempting to connect using 1.20.2 results in a long "Joining world" message and a timeout disconnect.

Connecting to the backend server directly works as intended even for 1.20.2.

## Demo
https://github.com/PaperMC/Velocity/assets/50774419/4d1fc45f-a12e-4358-bed5-30310375313b

**Comment by electronicboy** [comment]
All reported issues of this thus far have been down to plugins, outdated builds of ViaVersion being a common issue (might need the dev build)

**Comment by H4kt** [comment]
> All reported issues of this thus far have been down to plugins, outdated builds of ViaVersion being a common issue (might need the dev build)

Now this is not helpful.
I already stated that this is not an issue with ViaVersion since I can join the server without connecting to Velocity.

This is indeed an issue on your side. Stop being stubborn sending people to plugin developers and start actually resolving the issues on your end.

**Comment by electronicboy** [comment]
Proxies are generally more strict about stuff than the client is, have you tested with the viaversion dev build as suggested?

We do not support issues relating to protocl hacks, etc.

**Comment by H4kt** [comment]
> Proxies are generally more strict about stuff than the client is, have you tested with the viaversion dev build as suggested?
> 
> 
> 
> We do not support issues relating to protocl hacks, etc.

Yes I did before even opening this issue and nothing really changed.

**Comment by electronicboy** [comment]
Can you test without plugins in general?

**Comment by H4kt** [comment]
> Can you test without plugins in general?

I will try it out tomorrow.

**Comment by H4kt** [comment]
> Proxies are generally more strict about stuff than the client is

The other thing is that I don't really get why proxy is/should be more strict about this stuff. It seems to me that it should behave exactly like a client.

**Comment by electronicboy** [comment]
Ideally it should, however ensuring state when you're in the middle of two stateful things is generally a headache, and so it's much easier to just base your entire behavior on how the server/client behaves in order to manage state flow, rather than trying to cudgel support for all forms of unexpected behaviors

**Comment by gadget78** [comment]
i had this issue, exactly the same setup .. 
and `ViaVersion-4.9.0-23w41a-SNAPSHOT.jar` fixed this ... 

you can find ViaVersion Dev builds here .. 
https://ci.viaversion.com/job/ViaVersion-DEV/

**Comment by H4kt** [comment]
> i had this issue, exactly the same setup .. 
> 
> and `ViaVersion-4.9.0-23w41a-SNAPSHOT.jar` fixed this ... 
> 
> 
> 
> you can find ViaVersion Dev builds here .. 
> 
> https://ci.viaversion.com/job/ViaVersion-DEV/

For me it did not.
I will re-test it again tomorrow.
