### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by ArifErdoganK** [PaperMC/Velocity#1128]
Some players are experiencing the following error. What is the reason for this?

```
[16:59:00 ERROR]: [connected player] metospor (xx.xx.xx.xx/xx.xx.xx.xx:33263): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@7f54e7e9
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```

Plugins:

1. AuthMeVelocity-Velocity-4.0.4.jar
2. CommandWhitelist-Velocity-2.8.1.jar
3. floodgate-velocity_v85.jar
4. Geyser-Velocity_v340.jar
5. LuckPerms-Velocity-5.4.104.jar
6. nuvotifier_v2.7.3.jar
7. RedisBungee-Velocity-0.11.3-SNAPSHOT-all.jar
8. SkinsRestorer_v14.2.13.jar
9. Sonar_v2.0.5.jar
10. SyncCommands Velocity v4.0.1.jar
11. TAB-4.0.8-SNAPSHOT.jar
12. VelocityControl-3.11.7-SNAPSHOT.jar
13. VulcanVelocity-2.0.6.jar
14. WarpSystem_v5.1.4.jar

**Comment by electronicboy** [comment]
All we can tell you is what the OS told us, the connection was closed externally in an unexpected manner

**Comment by ArifErdoganK** [comment]
> All we can tell you is what the OS told us, the connection was closed externally in an unexpected manner

Thanks.
