### ISSUE TITLE
cannot open

### ISSUE THREAD

**Issue by Glitchmaster4415** [PaperMC/Velocity#1132]
Cannot open the file it says "A java exception has occurred."
![Screenshot 2023-10-29 074504](https://github.com/PaperMC/Velocity/assets/146447329/5b39db35-9451-4fda-ade9-43c3f1e73d86)

**Comment by Nacioszeczek** [comment]
Please use our [Discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io/forums/) for support.
