### ISSUE TITLE
MEDIUM: Use of AccessController.doPrivileged() in Public Method of Public Class

### ISSUE THREAD

**Issue by DawmosTomie** [PaperMC/Velocity#1134]
The code will execute with system privileges and should be manually checked with great care to ensure no vulnerabilities are present.

Line: 539 - Filename: Velocity\proxy\src\main\java\com\velocitypowered\proxy\VelocityServer.java

`AccessController.doPrivileged(new PrivilegedAction<Void>() {`

**Comment by electronicboy** [comment]
Not an issue, this code is in the shutdown path as is expected, only fix here would basically be to just appeasing overzelous scanning tools
