### ISSUE TITLE
To access backend command.

### ISSUE THREAD

**Issue by Harry-Jing** [PaperMC/Velocity#1159]
I am encountering a command conflict issue in my Minecraft proxy server setup involving two different mods.

1. **LibreLogin Mod for Proxy Server**: The [LibreLogin mod](https://github.com/kyngs/LibreLogin) introduces the command `/log <password>`, intended as a shorthand method for player login.

2. **Carpet Mod for Backend Server**: On my backend server, I am using the [Carpet mod](https://github.com/gnembon/fabric-carpet) (a Fabric mod), which also uses the `/log` command. This command in Carpet is detailed in their [documentation](https://github.com/gnembon/fabric-carpet/wiki/Commands#log) and is designed for utilizing Carpet loggers.

The overlapping use of the `/log` command between these two mods is causing functionality issues.

I have previously reported this issue on the LibreLogin GitHub page (https://github.com/kyngs/LibreLogin/issues/184) but am still unclear on how to resolve this conflict. Could I receive guidance on how to address this issue, or could a potential fix be implemented to differentiate the commands in these two mods?

Thank you for your assistance.

**Comment by electronicboy** [comment]
There is no mechanism for resolving this, nor generally can there be one, proxy commands will always override the servers commands as the nature of interception, best you could do is ask the proxy plugin or the mod to make their commands configurable to mitigate this
