### ISSUE TITLE
Velocity to Velocity transmits real IP and UUID

### ISSUE THREAD

**Issue by lipind** [PaperMC/Velocity#1167]
Due to special reasons such as plugin compatibility, I have to reverse proxy two Velocity
but this cannot obtain the player's real IP. In downstream servers, I can only obtain 127.0.0.1:XXXXX

Can we add the function of transmitting real IP between Velocities?

PS：I know using Velocity this way is not very reasonable, but I can only do it this way
![server](https://github.com/PaperMC/Velocity/assets/98028461/31af8fa9-3d43-4d41-912e-2f6c860222e7)

**Comment by electronicboy** [comment]
proxy in proxy is not something we intend to support, and as such, there is little interest in us to implement IP forwarding support incoming into velocity itself
