### ISSUE TITLE
weird af error kick message

### ISSUE THREAD

**Issue by czychuuu** [PaperMC/Velocity#1170]
![image](https://github.com/PaperMC/Velocity/assets/60987404/6ea8fae7-3300-4665-8755-5e48c6c04ced)
so this happens when modded 1.20.1 client tries to connect to a 1.20.2 purpur lobby server
and forced hosts are ignored

**Comment by czychuuu** [comment]
velocity console shows only this "[connected player] czychuuu (/ip) has connected"
and on the lobby "czychuuu lost connection: Disconnected"

**Comment by Timongcraft** [comment]
1.20.1 and 1.20.2 are not compatible.

**Comment by Timongcraft** [comment]
I meant not compatible.

**Comment by Noxillio** [comment]
> 1.20.1 and 1.20.2 are not compatible.

Unless you're using ViaBackward. In which case you'll want to report this to them. If this was a version compatibility issue on its own due to Velocity, then it would specifically say that the client version is too old and ask you to update.

**Comment by 4drian3d** [comment]
Protocol hack plugins are not supported, you should report the bug to ViaVersion/ViaBackwards as you are connecting with a different client version than the one you have on your backend server
