### ISSUE TITLE
error connecting velocity 1.20.4

### ISSUE THREAD

**Issue by cesar3453** [PaperMC/Velocity#1171]
Error when trying to connect to a 1.20.4 server using velocity in 1.20.2 connecting normally and nothing showing on the console and as if the player doesn't even have to connect

![Screenshot_6](https://github.com/PaperMC/Velocity/assets/95100758/bd196427-22f2-4904-9262-b61645ed711e)

**Comment by Timongcraft** [comment]
If you are trying to connect to a server on 1.20.4 with a client on 1.20.2, that won't work because they are incompatible.

**Comment by cesar3453** [comment]
Yes, in this case I had the client 1.20.4 and the server is also 1.20.4

**Comment by Timongcraft** [comment]
And what do you mean by `using velocity in 1.20.2` ?

**Comment by cesar3453** [comment]
I think I expressed myself badly, sorry, I meant that using velocity-3.3.0-SNAPSHOT-311 it does not connect to a 1.20.4 server, but if the server is in version 1.20.2 it works normally

**Comment by Timongcraft** [comment]
I just updated velocity and paper and it works fine (1.20.4), could you try updating and send a list of your plugins?

**Comment by cesar3453** [comment]
strange, I updated it to the paper and it's connecting so the error must be in purpur Thanks for the help

**Comment by electronicboy** [comment]
This is pretty much always down to plugins messing with packets, theres nothing for us to go off here
