### ISSUE TITLE
Couldn't dispatch custom payload - help

### ISSUE THREAD

**Issue by Resp0und** [PaperMC/Velocity#1177]
Hello. My server kicked me after try to join Velocity with "Sodium mod 1.20.2".
Trying to use -Dpaper.disableChannelLimit=true - nothing

Log's: https://logpaste.com/DZAajtOA

**Comment by Timongcraft** [comment]
This is not a velocity issue.

**Comment by Resp0und** [comment]
> This is not a velocity issue.

I am using the version without plugins, an error does not allow me to log into the server

**Comment by Timongcraft** [comment]
> 
> I am using the version without plugins, an error does not allow me to log into the server

You sent a Purpur log: "This server is running Purpur".
And the issue happens within the backend (Purpur) and not the proxy (Velocity).

**Comment by Resp0und** [comment]
Idk, client can't connect to the Velocity, not a backend server. Velocity says - Couldn't dispatch custom payload

[23:46:52] [Netty NIO Worker #2/ERROR] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] SokTV (/127.0.0.1:62376): disconnected while connecting to lobby: Invalid custom payload!
[23:46:53] [Netty NIO Worker #2/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] SokTV (/127.0.0.1:62376) has disconnected: *********** lobby: Invalid custom payload!

**Comment by Timongcraft** [comment]
I cannot find "Invalid custom payload!" anywhere in the velocity code/language files.
Try updating everything.
Is this between client and server or proxy and backend?
Has this worked in some previous version?
Logs for everything would also be helpful.

**Comment by Xernium** [comment]
The errors you are seeing are produced by the **Server** and not by Velocity.
**Your setup is unsupported!**
To diagnose:
1. Switch to Paper. We only support unmodified Paper servers 
2. Remove the packet events plugin and the plugins depending on it. At least one of them is broken

If you can still reproduce the issue after then there actually is a problem that needs to be investigated
