### ISSUE TITLE
New Resource Pack API in 1.20.4

### ISSUE THREAD

**Issue by BingYanchi** [PaperMC/Velocity#1178]
In 1.20.4, clients allow saving multiple server resource bundles, and multiple resource bundles can be applied simultaneously.

But I don't seem to see the relevant JavaDoc. Velocity's original sending resource package api will not clear the original resource package. After obtaining the new resource package, it will coexist with the old resource package.

It may be that Velocity does not support the new resource pack of 1.20.4.

**Comment by electronicboy** [comment]
This is generally known pending the adventure update

**Comment by BingYanchi** [comment]
> This is generally known pending the adventure update

But now for the 1.20.4 client, the old resource package will not be cleared when receiving a new resource package, which will cause multiple resource packages to take effect at the same time. Does Velocity have any plans to fix this issue before the adventure update, or just let the client clear resource packs when they are sent.

**Comment by Emibergo02** [comment]
hi i have the same problem
steps to reproduce:
install a new velocity+paper with oraxen(i use it only to send new packs quickly)
regenerate/resend pack with new entries
logout
rejoin and it sends you the first default pack and the modified one
(it should've sent me just the new one)

**Comment by 4drian3d** [comment]
Could you try the latest commit?

**Comment by Emibergo02** [comment]
Still not working as intended @4drian3d

**Comment by Emibergo02** [comment]
check your Discord DMs
i sent you a complete report of the issue from my perspective @4drian3d

**Comment by 4drian3d** [comment]
#1225 should resolve the ResourcePacks API issue, for the ResourcePacks bug, another issue should be opened
