### ISSUE TITLE
Multiple players getting kicked

### ISSUE THREAD

**Issue by SladeHazard** [PaperMC/Velocity#1190]
hey sometimes multiple people get kicked from the proxy for no reason, anyone has an idea on why this could be happening?
![image](https://github.com/PaperMC/Velocity/assets/45261094/03b64e84-1529-48fb-bb31-ba4d07851304)

spigot server is just =  [20:34:17 INFO]: AngelAlina lost connection: Disconnected

**Comment by electronicboy** [comment]
read timed out just says that we didn't get any packets in 30 seconds

**Comment by SladeHazard** [comment]
> read timed out just says that we didn't get any packets in 30 seconds

do you know why it happens? is it related to some proxy plugin, spigot plugin or networking issues with the server host or ddos provider service? because it only kicks like 10 players out of 100, not all of them
