### ISSUE TITLE
Can't connect since build 329

### ISSUE THREAD

**Issue by x1p** [PaperMC/Velocity#1207]
As of build 329, players can't connect to the network anymore. The server also won't respond to the client's serverlist ping.
Build 328 works as normal.

Server is on a shared host with a specific port.
Test client (Paper 1.20.4) uses the direct hostname:port to connect. (So no SRV-record)

Tested up until build 334

**Comment by 4drian3d** [comment]
You have to check that your plugins are up to date, in build 329 there was a change in Velocity internal code that breaks plugins that use packets

**Comment by x1p** [comment]
Thnx. I found the culprit
