### ISSUE TITLE
Bad disconnect message when no available servers

### ISSUE THREAD

**Issue by rwnd-bradley** [PaperMC/Velocity#1213]
The disconnect message `Internal Exception: io.netty.handler.codec.DecoderException: te: Loading NBT data` is displayed when the `[servers]` config section is either empty or the initial server is set to null in PlayerChooseInitialServerEvent. Tested using the build git-953ab6d8-b335, with no plugins, and a vanilla 1.20.4 client. The console still logs the correct disconnect message.

**Comment by 4drian3d** [comment]
Can you show the complete error? That one line doesn't give much information

**Comment by rwnd-bradley** [comment]
There are no proxy side errors, that 1 line is what the client sees in the disconnect screen.

![image](https://github.com/PaperMC/Velocity/assets/75290033/1466511c-0450-4755-b638-007deeca57fc)
