### ISSUE TITLE
Allow setting custom server brand to show to clients

### ISSUE THREAD

**Issue by mrjasonn** [PaperMC/Velocity#1218]
This would actually be very useful, as server admins would actually want to hide some info. If just the backend server supports this (e.g. Paper), then the Velocity part can't be hidden and would be easier to just set on proxy.

**Comment by Xernium** [comment]
There's plugins to do this already. The very little credit the team gets for the software shouldn't be removed without this consideration. We could probably natively allow the type of software to be hidden (eg replace with Paper/Proxy) but not entirely remove it.

That being said:
Even if you hide this it will do nothing to obscure the use of this software. All Minecraft hosting software can be easily identified by its behavior. If this is about security then it's starting at the wrong end of the equation

**Comment by mrjasonn** [comment]
> There's plugins to do this already. The very little credit the team gets for the software shouldn't be removed without this consideration. We could probably natively allow the type of software to be hidden (eg replace with Paper/Proxy) but not entirely remove it.
> 
> That being said: Even if you hide this it will do nothing to obscure the use of this software. All Minecraft hosting software can be easily identified by its behavior. If this is about security then it's starting at the wrong end of the equation

Then can we have it natively hidden? @Xernium

**Comment by 4drian3d** [comment]
> > There's plugins to do this already. The very little credit the team gets for the software shouldn't be removed without this consideration. We could probably natively allow the type of software to be hidden (eg replace with Paper/Proxy) but not entirely remove it.
> > That being said: Even if you hide this it will do nothing to obscure the use of this software. All Minecraft hosting software can be easily identified by its behavior. If this is about security then it's starting at the wrong end of the equation
> 
> Then can we have it natively hidden?

No. Please don't keep insisting, it's a practice we don't recommend or encourage, but there are plugins for it if you really want to do it
