### ISSUE TITLE
Velocity kicks player from proxy if use /server command

### ISSUE THREAD

**Issue by yukisnowflake** [PaperMC/Velocity#1219]
<fixed, closing and deleting issue>

**Comment by electronicboy** [comment]
Well, the connection attempt failing is not a velocity error, I am puzzled as to how you got into the illegal state, however;
is there any logs on the server as to the connection being closed from its side? Can you reproduce without plugins? version?

**Comment by yukisnowflake** [comment]
my bad, fixed
