### ISSUE TITLE
Unable to use non-ASCII characters as server name

### ISSUE THREAD

**Issue by jhqwqmc** [PaperMC/Velocity#1220]
Using non-ASCII characters as the server name results in unusable commands.
![image](https://github.com/PaperMC/Velocity/assets/113768629/d793fbf9-3882-41c4-bb32-cb5121e5ceda)

**Comment by electronicboy** [comment]
This is an issue with brigadier, generally little we can do about it without compromising on the command setups

**Comment by jhqwqmc** [comment]
Okay, this is affecting the operation of the server, it would be nice if it could be fixed

**Comment by electronicboy** [comment]
We have no control over mojangs command library, you would need to report it to them
