### ISSUE TITLE
Build 343: Unable to authenticate player

### ISSUE THREAD

**Issue by Teslicek** [PaperMC/Velocity#1221]
Started getting this error after updating Velocity.
Happens randomly on player quit.

https://pastes.dev/R59bkq68kT

**Comment by electronicboy** [comment]
There is nothing in velocity that should be doing network requests on a player disconnecting, and this is generally not a velocity issue, the HTTP server that a connection was connected to was explictly closed by the server it was connected to which is something apparently on your own local network, assuming that that is the target IP in there

> java.util.concurrent.CompletionException: java.io.IOException: /172.18.0.6:44190: GOAWAY received

**Comment by Teslicek** [comment]
Still happens, my bad for thinking it happens on player quit.

It actually happens when a player tries to join the server.

The error is completely random and the client only sees "Disconnected", but when they rejoin, everything's fine.
