### ISSUE TITLE
IPv6 doesn't work via AAAA Domain record

### ISSUE THREAD

**Issue by KastenKlicker** [PaperMC/Velocity#1222]
I can only connect to velocity with the IPv6 address, but not with the AAAA Domain record.

I run velocity 3.3.0 344 on Ubuntu 20.04. 

My velocity.toml: https://gist.github.com/KastenKlicker/788873c66800f32efbb7805b35756f8d

Ufw does allow tcp to port 25565 from anywhere just for IPv6 (I disabled IPv4 for test purposes).
The AAAA records for the main domain and subdomain for the forced hosts are known by my PC and the Server.

Velocity doesn't recognize any connection attempts when trying to connect via domain. No error or anything.

Apache and ssh just work fine via the AAAA records and I don't see any obvious issue in my velocity.toml. :(

**Comment by Nacioszeczek** [comment]
If you can connect directly through the IP but not through a domain there's nothing for us to fix here.
Check if you don't have any SRV records that may be overriding what your client is trying to connect to and remember DNS propagation sometimes just takes a while.
