### ISSUE TITLE
commands freeze the proxy

### ISSUE THREAD

**Issue by exor9** [PaperMC/Velocity#1230]
Hi.  I have a problem because I added a velocity plugin and after entering the command from this plugin, the entire proxy freezes.  For this plugin to work, I need vpacketevents, which is installed, but when I add it, commands from other plugins also stop working.  Do you have any ideas?
the plugin works, this only happens after using the command from the plugin. No errors

**Comment by electronicboy** [comment]
if it only happens after using commands from a plugin, you would generally want to speak to their support, likely they're locking up the event handler, see jstack, etc
