### ISSUE TITLE
Random disconnects on join

### ISSUE THREAD

**Issue by Teslicek** [PaperMC/Velocity#1242]
Ever since velocity commits https://github.com/PaperMC/velocity/commit/6d7335b21fb25054dbfd871b099a71c0eb6d7c11 or https://github.com/PaperMC/velocity/commit/b22b2dc458bcbef9a4e0fb8320dac9e58002230e (not sure, which one caused it), my players started experiencing random disconnects on join.

I already created an issue https://github.com/PaperMC/Velocity/issues/1221, however it got rejected, as if it was not velocity's fault.

Steps to reproduce:
\- Paper 422, no plugins
\- Velocity 358, no plugins
\- Vanilla client 1.20.4
\- Start rejoining the server until you experience the error (as the error happens randomly)
\- My velocity log from startup: https://pastes.dev/bbmKPkHB1q
\- My paper log from startup: https://pastes.dev/gp7lCZumLt

Disconnect message:
![image](https://github.com/PaperMC/Velocity/assets/87967222/e37c44a3-ada7-4ba8-ae2f-ca21de24e7cf)

**Comment by 4drian3d** [comment]
Can you test the latest build to see if you can still reproduce this bug?

**Comment by Teslicek** [comment]
Tried reconnecting for 15 minutes in a row, I did not get the error now.

Logs:
\- velocity: https://pastes.dev/tpdorryytM
\- backend: https://pastes.dev/QUNzpiQWpm

The only weird thing I encountered during the testing was that even though I disconnected from the proxy, 3 times I got the error as if I was still connected, however, that might have been caused due to the proxy being behind tcpshield, who knows.

**Comment by 4drian3d** [comment]
Yes, that could be caused by one of your plugins, but thanks for testing
