### ISSUE TITLE
The information in the chat bar is missing

### ISSUE THREAD

**Issue by Crystal0404** [PaperMC/Velocity#1244]
I only kept the necessary mods for running velocity on the fabric

The Minecraft version is 1.20.4

I used ```velocity-3.3.0-SNAPSHOT-358.jar``` for the Velocity version

I recorded a short video and after switching servers, the chat message disappeared

**Comment by Crystal0404** [comment]
I don't know why I can't upload the video directly. I put it in a compressed file and uploaded it
[Zulu-17 2024.02.14 - 17.25.40.04.zip](https://github.com/PaperMC/Velocity/files/14277847/Zulu-17.2024.02.14.-.17.25.40.04.zip)

**Comment by Warriorrrr** [comment]
This is intended behaviour, the client will clear its chat when it gets switched back into the config state, the server (or proxy in this case) can't do anything to prevent that.
