### ISSUE TITLE
Cannot invoke "com.velocitypowered.api.proxy.player.ResourcePackInfo.getId()" because "resourcePackInfo" is null

### ISSUE THREAD

**Issue by pjindras** [PaperMC/Velocity#1257]
Hello, some players are getting kicked from my server with this error message, I am using Velocity 3.3.0-SNAPSHOT (git-953ab6d8-b335)

java.lang.NullPointerException: Cannot invoke "com.velocitypowered.api.proxy.player.ResourcePackInfo.getId()" because "resourcePackInfo" is null

https://paste.gg/p/anonymous/e6480ddb6938486ab6be946174d0ffb3

**Comment by electronicboy** [comment]
You're outdated by almost 30 builds, in which the resource pack system has had a lot of work recently
