### ISSUE TITLE
Disconnecting with velocity ?

### ISSUE THREAD

**Issue by BlindMag** [PaperMC/Velocity#1269]
I'm unsure if this is related to the system I'm on, if it's a user error in my pterodactyl installation, or if this is solely a velocity issue. I'm getting booted off the server with the following error: https://pastebin.com/d0RYsmuf We're using pterodactyl on a hosted dedicated Ubuntu server. Any ideas what could be the cause? 

I tried a clean install of both velocity and multiple purpur servers.

**Comment by BlindMag** [comment]
This is happening intermittently, especially on backend server restarts. There is no plugins in any of the servers. I am using Velocity 3.3.0-snapshot and purpur 2155.

**Comment by electronicboy** [comment]
All we can see is that you've apparently got mangled compressed packets, stuff like this is generally down to plugins or environmental oddities, hard to say otherwise

**Comment by BlindMag** [comment]
Plugins on the proxy or on the backend servers?

**Comment by electronicboy** [comment]
Both, generally it's been on the servers, but, mangled data is mangled data;

outside of that, there is no real info to work off here, this is not really the place for support as it needlessly floods peoples inboxes

**Comment by BlindMag** [comment]
I'm just trying to understand what is happening, does this mean it's something to do with the system if I have no plugins, clean installs on a new system.

**Comment by electronicboy** [comment]
Hard to say, I've seen people have these issues due to faulty OS installs, bad ram, etc
