### ISSUE TITLE
Unable to access other servers when trying to connect to one server

### ISSUE THREAD

**Issue by neokoni** [PaperMC/Velocity#1278]
With viaversion and viarewind installed on velocity, there are three servers other than the login lobby, a leaves 1.20.4 server, a purpur 1.20.2 server, and a fabric 1.20.4 server

When joining Minecraft with a version other than 1.20.4, only the fabric server is inaccessible, the rest of the servers are playable.

When trying to connect to a fabric server with a non-1.20.4 version of Minecraft, it will only say that it is trying to connect, and after a while it will say that the connection failed.

You can't switch to another server until the connection fails, and it will say "Already trying to connect to this server" when switching.

**Comment by electronicboy** [comment]
you can't abort a connection attempt "in fly", not without requiring much more state tracking in order to accommodate this. Some level of rewriting the entire server connection/switching process is planned down the road which might make this easier, but, this is expected behavior
