### ISSUE TITLE
scorboard character limit

### ISSUE THREAD

**Issue by 0ZyroX** [PaperMC/Velocity#1299]
Hello, in order to enter Velocity with version 1.8, I have to use viabackwards and viarewind, and now that I have used the above servers, their 1.13 version has given a character limit to the scorboard and it won't accept more than 12 characters, what should I do?
Image
![Screenshot_2](https://github.com/PaperMC/Velocity/assets/132475371/04a6a129-c471-44d4-8b1f-d61652980341)

**Comment by electronicboy** [comment]
Those protocol hacks have nothing to do with us
