### ISSUE TITLE
support version

### ISSUE THREAD

**Issue by 0ZyroX** [PaperMC/Velocity#1301]
When we install Velocity, does it support from 1.8 to 1.20.4?

**Comment by electronicboy** [comment]
Please stop spamming issues on the tracker

**Comment by 0ZyroX** [comment]
sorry

**Comment by 0ZyroX** [comment]
Can you give me some advice, why can't I enter the server with 1.8.9?

**Comment by electronicboy** [comment]
This is not the place for support, you've already been told what to do on discord
