### ISSUE TITLE
"bungee-plugin-message-channel" on true breaks custom BungeeCord plugin messaging

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Velocity#1312]
If a third party plugin writes on the BungeeCord channel with this option on true it never receives the plugin message packet.

This is caused by the method below returning true and not allowing subChannel to be customized by third party developers. This works just fine on BungeeCord which is superior to Velocity anyways. I am just kidding, please let developers use BungeeCord channel for their plugins.

https://github.com/PaperMC/Velocity/blob/1228f147423d14a6e0b0c940259aa59da90797b1/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/BungeeCordMessageResponder.java#L382

**Comment by electronicboy** [comment]
The bungeecord channel is not your channel, it's 100% intentional that we do not allow others to abuse this channel, use your own, or use the features within the channel properly.

**Comment by kangarko** [comment]
Thanks for the info.

Afaik the BungeeCord channel cannot be spoofed by malicious clients so they can't write custom packets and execute commands on the network? 

We used to broadcast plugin messages on the BungeeCord channel on Bungee for that reason.

**Comment by electronicboy** [comment]
> Afaik the BungeeCord channel cannot be spoofed by malicious clients so they can't write custom packets and execute commands on the network?

That is why you validate the sender of the messages in the proxy plugin, there is no real justification for hijacking somebody else's channel here

**Comment by kangarko** [comment]
Thanks for your time.
