### ISSUE TITLE
Failed to decode packet 1.20.5/1.20.6

### ISSUE THREAD

**Issue by ChrisTVH** [PaperMC/Velocity#1337]
This does not seem to be a viaversion problem, I had viaversion and viabackwards on my velocity proxy and the same thing happens with 1.20.5/1.20.6.

So what I did was to remove it from the proxy and put it on all servers as people usually do, and the same error persists.

It is assumed that by default players can connect to multiple versions of the proxy, it also happens that in rare cases if you connect but in most attempts when you open your client does not allow you to connect.

![image](https://github.com/ViaVersion/ViaVersion/assets/58376852/c12d4281-7680-45c1-a08c-e7a85380abad)

**Comment by electronicboy** [comment]
We do not support protocol hacked environments, and velocity doesn't really touch these packets in a manner that would cause this, so more than likely you've just got something setting an invalid name. You'd need to see if there is something in the client logs as to the cause of this, as we have 0 means to diagnose what is going on here without any info.

**Comment by ChrisTVH** [comment]
> We do not support protocol hacked environments, and velocity doesn't really touch these packets in a manner that would cause this, so more than likely you've just got something setting an invalid name. You'd need to see if there is something in the client logs as to the cause of this, as we have 0 means to diagnose what is going on here without any info.

All this I tested on a vanilla minecraft client without modifications.
https://mclo.gs/8nzKGuT

**Comment by electronicboy** [comment]
There is generally nothing useful in that log, all I can advise at this moment is to reproduce without plugins, etc

**Comment by ChrisTVH** [comment]
> There is generally nothing useful in that log, all I can advise at this moment is to reproduce without plugins, etc

That's why I'm blank, in the proxy it doesn't even say that it connects, in the client it doesn't say anything either, it's weird.

**Comment by electronicboy** [comment]
likely because the proxy does not care to validate this info the same way that mojangs client does now

**Comment by ChrisTVH** [comment]
> likely because the proxy does not care to validate this info the same way that mojangs client does now

For now I will do what you told me and try to connect without plugins and I will try with the official launcher too (although some of my users told me that it happens the same way too) and see what happens.

**Comment by ChrisTVH** [comment]
I started without plugins and I put them 1 by 1 until I put all the ones I have, and it works correctly in my local pc with windows.
The only option, which is different from my network that is now active, is `tcp-fast-open` a function that only works on linux.

Also activate to see the log better: log-command-executions, show-ping-requests, enable-player-address-logging.

I don't think they have anything to do with or affect anything.

**Comment by ChrisTVH** [comment]
I have tried changing this on my proxy which is hosted with linux and it is still the same, this is one of the weirdest things I have seen ._.

**Comment by ChrisTVH** [comment]
There you have found the cause, in conclusion this happens when the limbo servers have not been upgraded to support new versions.
