### ISSUE TITLE
Invalid signature for profile public key.

### ISSUE THREAD

**Issue by HappyMajor** [PaperMC/Velocity#1340]
When I try to connect to my MC server run by PurpurMC via Velocity proxy then I get the following error message:

> Error Message: [21:54:36 INFO]: HappyMaj0r lost connection: Invalid signature for profile public key.

When I join my server without Velocity, then it works.

Versions:

Velocity: Velocity 3.3.0-SNAPSHOT
Server: purpur-1.20.6-2219

What I tried:

- enforce-secure-profile to false for each server
- online-mode to false for each server
- restarted mc client.
- installed prism and launched mc there
- force-key-authentication to false on Velocity
- tried it with 2 accounts

**Comment by electronicboy** [comment]
player-info-forwarding-mode?

**Comment by HappyMajor** [comment]
This was quick 👍 

It has the value "NONE"

player-info-forwarding-mode = "NONE"

**Comment by electronicboy** [comment]
That would be why, no player info forwarding means that the UUID that the proxy gets will be an offline mode one, which, as the signature is keyed using the players UUID, will mean that the thing will always be invalid

**Comment by HappyMajor** [comment]
Might be worth to update the getting started guide. Player forwarding was actually referenced but it sounded very optional and more as a mandatory config for prod in terms of security:

![image](https://github.com/PaperMC/Velocity/assets/1957550/17635ff4-5caf-40d8-9f34-f68c8e6eaca8)

I think I will update it myself tomorrow.
