### ISSUE TITLE
authlib+velocity+paper 1.20.6，player join server： Invalid signature for profile public key.

### ISSUE THREAD

**Issue by BiteMeIfYouCan** [PaperMC/Velocity#1345]
Using authlib, Velocity, and paper-1.20.6-137

According to the existing information:

In the server.properties file:
```
enforce-secure-profile = false
```
In paper-global.yml, configure the following:
```
velocity:
  enabled: false
  online-mode: false
  secret: wGJH1DvOZrLg
```
In velocity.toml, configure the following:

```
player-info-forwarding-mode = "legacy"
prevent-client-proxy-connections = false
```
However, when connecting to the server,server: "Invalid signature for profile public key."

When I set online-mode to false in velocity.toml, I can enter the server normally, but then I cannot use authlib.

**Comment by ShawnFoxter** [comment]
why are you using legacy mode?

**Comment by electronicboy** [comment]
This is generally down to the backend server having 0 forwarding setup and thus the UUID being wrong, causing it to not match the key that the profile signature expected
