### ISSUE TITLE
velocity 3.3.0 396 + paper1.20.6 - cannot ban /server

### ISSUE THREAD

**Issue by LittleHe1** [PaperMC/Velocity#1346]
I don't want players use `/server` to connect other servers so i set `velocity.command.server` to false by luckperms.
It was worked in 1.20.2 but failed in 1.20.6

Is the permission changed?

**Comment by powercasgamer** [comment]
Make sure that you've properly installed LuckPerms on Velocity and denied the permission on the velocity instance. Also make sure you do not have another plugin that is overriding the `/server` command. You can check this (and also see which permission you're missing) by doing `/lpv verbose command (player) server`.

Please use [our discord](https://discord.gg/papermc) for support next time.

**Comment by LittleHe1** [comment]
> Make sure that you've properly installed LuckPerms on Velocity and denied the permission on the velocity instance. Also make sure you do not have another plugin that is overriding the `/server` command. You can check this (and also see which permission you're missing) by doing `/lpv verbose command (player) server`.
> 
> Please use [our discord](https://discord.gg/papermc) for support next time.

Thank you, I use `lpv group default permission set velocity.command.server false` in velocity and it worked.
That might be a wrong in luckperms because in the past time I just used  `lp group default permission set velocity.command.server false` in servers(paper) and it worked, now it doesn't work.
