### ISSUE TITLE
How to get the backend server's motd Players MaxPlayers Version

### ISSUE THREAD

**Issue by 3154311518** [PaperMC/Velocity#1348]
How to get the backend server's motd Players MaxPlayers Version
Does Velocity provide these methods？

**Comment by AydenC77** [comment]
im trying to do the same thing i use pterodactyl so i was jest going to use its api but i dont think you can

**Comment by Warriorrrr** [comment]
https://jd.papermc.io/velocity/3.3.0/com/velocitypowered/api/proxy/server/RegisteredServer.html#ping()
