### ISSUE TITLE
Forced-Hosts not working

### ISSUE THREAD

**Issue by DavidFrings** [PaperMC/Velocity#1350]
I have a Velocity server with a domain and I am tying to use my domain with forced-hosts, but I can't get it running.
(My server only has ipv6 and an ufw firewall with 25565 allowed)
My normal domain works but the rest doesn't.

In Cloudflare I set a * Record(AAAA) and a @ record(AAAA) to my server

**Comment by Nacioszeczek** [comment]
What's the exact domain you're trying to connect to?
Does your network support IPv6?
What message do you see when connecting?

**Comment by DavidFrings** [comment]
my domain is privatgames.net and yes my network has ipv6 (the privatgames.net works but subdomains like mc.privatgames.net doesn't)

**Comment by Nacioszeczek** [comment]
I can resolve an AAAA record for `mc.privatgames.net.` but not for `privatgames.net.`, cannot connect to it however, so you need to figure out why it's being blocked.

**Comment by DavidFrings** [comment]
And I activated the reverse proxy in Cloudflare

**Comment by electronicboy** [comment]
your root domain does not resolve to anything, your subdomain resolves to a cloudflare IP address, CF will not terminate non HTTP/S connections for you (not unless you pay $$$)

**Comment by DavidFrings** [comment]
> your root domain does not resolve to anything, your subdomain resolves to a cloudflare IP address, CF will not terminate non HTTP/S connections for you (not unless you pay $$$)

what do you mean with terminate non HTTP/S connections ?

**Comment by electronicboy** [comment]
They will not handle raw TCP streams, only web stuff

**Comment by DavidFrings** [comment]
oh thx

**Comment by DavidFrings** [comment]
I will check this

**Comment by DavidFrings** [comment]
Yes that was the Problem!
For all the people who have the same problem,
deactivate the proxy!!! 

And for the readme.md maybe make an Note...
