### ISSUE TITLE
Error with Packet size of protocols

### ISSUE THREAD

**Issue by SimonMage** [PaperMC/Velocity#1356]
Hello, I have I problems on my server and using a plugin open source BetterHud I have made my custom hud on my backend server but Velocity kicks me from the proxy because the hud made with resourcepack is too much than Velociy accepts, as you can see on log. Please give me the possibility to increase that packet size or fix it. Obviously without Velocity as Proxy everything works fine.

[2024-06-16-3.log](https://github.com/user-attachments/files/15858172/2024-06-16-3.log)

**Comment by SimonMage** [comment]
Log made with mcpaste.io

https://mcpaste.io/d735a60b8625d300

**Comment by electronicboy** [comment]
Looks like when they moved the packets over to the codec system they got rid of the packet specific component size limits

**Comment by SimonMage** [comment]
I'm not an expert but this means that can be fixed by Velocity right?

> Looks like when they moved the packets over to the codec system they got rid of the packet specific component size limits

**Comment by electronicboy** [comment]
Yes, we just need to increase the limits for versions after that change; I just can't touch much because I'm recovering from surgery

**Comment by SimonMage** [comment]
Thank you so much and I hope you to recover faster, good health!

> Yes, we just need to increase the limits for versions after that change; I just can't touch much because I'm recovering from surgery

**Comment by SimonMage** [comment]
Hey 👋🏻 any news about it? It was just needed to increase the limits right?

**Comment by SimonMage** [comment]
![Screenshot_1](https://github.com/PaperMC/Velocity/assets/75200996/8c6679cc-d889-4a46-a930-9a21add5cc0e)

I noticed that in some cases the size is variable, in this case is over 90.000.

Please increase to a number very big or make a config in velocity.toml to change the default value for future problems

> Yes, we just need to increase the limits for versions after that change; I just can't touch much because I'm recovering from surgery

**Comment by electronicboy** [comment]
We are not going to expose a config option. When this is fixed, the packet limit will reflect the protocol network limit as determined by the vanilla spec.

**Comment by SimonMage** [comment]
> We are not going to expose a config option. When this is fixed, the packet limit will reflect the protocol network limit as determined by the vanilla spec.

Oh really? And how much is the packet limit for Minecraft 1.20.2 ?

**Comment by SimonMage00** [comment]
> We are not going to expose a config option. When this is fixed, the packet limit will reflect the protocol network limit as determined by the vanilla spec.

Any news about htis update?

**Comment by SimonMage** [comment]
> We are not going to expose a config option. When this is fixed, the packet limit will reflect the protocol network limit as determined by the vanilla spec.

Any news

**Comment by electronicboy** [comment]
I am still blind

if somebody knows the protocol version the limit was bumped, and to what, this would make my life easier, unless somebody can submit a PR, etc

**Comment by Timongcraft** [comment]
> if somebody knows the protocol version the limit was bumped, and to what, this would make my life easier, unless somebody can submit a PR, etc
I know that the decoder switched from a maximum decompressed length of 2097152 in 1.17 to a maximum compressed length of 2097152 and a maximum uncompressed length of 8388608 in 1.17.1.
