### ISSUE TITLE
[Feature] Domain name resolution support

### ISSUE THREAD

**Issue by sulingjiang** [PaperMC/Velocity#1377]
### Requested Feature

Add domain name resolution support

### Why is this needed?

It is more convenient to use domain name than IP.

### Alternative Solutions

无

### Additional Information

I haven't seen it yet. Repeat.

**Comment by electronicboy** [comment]
velocity already resolves hostnames?

**Comment by sulingjiang** [comment]
No,and print error prompt.

unable to connect to server authme

**Comment by electronicboy** [comment]
Please show the actual error, as afaik, people have been using DNS resolution with velocity for years with docker just fine

**Comment by sulingjiang** [comment]
![Image_1720399450683](https://github.com/PaperMC/Velocity/assets/174881650/2e8ef498-d285-4577-ae5b-fcb336bf4ca7)

**Comment by sulingjiang** [comment]
![Image_1720399507500](https://github.com/PaperMC/Velocity/assets/174881650/7602dd03-8e9a-46ff-89a7-e3d33b35e378)

This mistake was actually handed in for others.

**Comment by electronicboy** [comment]
> Authme/172...

it resolved the record just fine, the destination IP refused the connection.
