### ISSUE TITLE
Kick from a backened server to the fallback server in a few time later

### ISSUE THREAD

**Issue by Appleman4136** [PaperMC/Velocity#1387]
### Expected Behavior

I just want to fix it
but i have no idea on it

### Actual Behavior

[09:10:26 ERROR]: [server connection] Appleman4136 -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@6b7cfdc4
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
[09:10:26 INFO]: [server connection] Appleman4136 -> survival has disconnected
[09:10:26 INFO]: [server connection] Appleman4136 -> mslb has connected

I have two server mslb and survival
After i join survival from mslb(using /server command)
i can join it successfully
but it will kick me in a few time later
and drop the issue that i show at the top

### Steps to Reproduce

Maybe just an explaination?
i cant sure what i need now cause idk what type of issue is it

### Plugin List

Velocity: fastlogin, floodgate, geyser, luckperms, skinsrestorer, slashhub, snap

mslb (hub) server:- DriveBackupV2, Essentials, FastLogin, floodgate, Geyser-Spigot, ItemEdit, LuckPerms, OpenInv, PlaceholderAPI, ProtocolLib,SkinsRestorer, spark, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, WorldEdit

survival: - DriveBackupV2, FastLogin, floodgate, Geyser-Spigot, LuckPerms, PlaceholderAPI, ProtocolLib, SkinsRestorer, spark, Vault,VentureChat, ViaBackwards, ViaRewind, ViaVersion

### Velocity Version

Velocity 3.3.0-SNAPSHOT (git-a4476253-b411)

### Additional Information

I have alr try to remove all of my plugin but this issue still present

**Comment by electronicboy** [comment]
> [server connection] Appleman4136 -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@6b7cfdc4
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

The connection was closed by the client, we'd need more logs, and this generally looks more like a support question for an unsupported setup

**Comment by Appleman4136** [comment]
[survival.log](https://github.com/user-attachments/files/16319376/survival.log)
[lobby.log](https://github.com/user-attachments/files/16319377/lobby.log)
[velocity.log](https://github.com/user-attachments/files/16319381/velocity.log)

**Comment by Appleman4136** [comment]
> > [server connection] Appleman4136 -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@6b7cfdc4
> > io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
> 
> The connection was closed by the server, we'd need more logs, but this generally looks more like a support question for an unsupported setup

[survival.log](https://github.com/user-attachments/files/16319386/survival.log)
[lobby.log](https://github.com/user-attachments/files/16319387/lobby.log)
[velocity.log](https://github.com/user-attachments/files/16319388/velocity.log)

**Comment by electronicboy** [comment]
We don't support servers running in offline mode, and your logs are flooded with network errors

**Comment by Appleman4136** [comment]
> We don't support servers running in offline mode, and your logs are flooded with network errors

I will set server to off mode cause im using fastlogin

The network problem is cause by SQL problem. I had alr try remove the plugin which needed SQL but it still present.

I noticed that my survival is the only server which didnt have the sql problem
