### ISSUE TITLE
PlayerConnectionRequestEvent

### ISSUE THREAD

**Issue by SpigotRCE** [PaperMC/Velocity#1388]
### Requested Feature

PlayerConnectionRequestEvent will be fired when a Player#createConnectionRequest is made.

### Why is this needed?

It's useful when there are multiple servers like "hub-1" "hub-2" etc. and you have to send the player to a particular hub server so that will be managed by the plugin and the connection request can be made for just "hub"

### Alternative Solutions

ServerPreConnectEvent I have tried but not really a fan of it.

### Additional Information

Nah nothing

**Comment by astei** [comment]
...so what exactly is your ask here? You want a new event because you don't like `ServerPreConnectEvent`? That's really not enough reason. What feature is it missing?

**Comment by SpigotRCE** [comment]
I believe when changing the server during ServerPreConnectEvent would call it self after changing the server? 
Sorry if I am going wrong here.

**Comment by Timongcraft** [comment]
No, it does not. It fires before the player connects to a new server, indicated by the 'Pre', but it is also specified in the [JavaDoc](https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/player/ServerPreConnectEvent.html).
