### ISSUE TITLE
Unable to connect to 1.20.4 Arclight server through modern forwarding

### ISSUE THREAD

**Issue by Aruvelut-123** [PaperMC/Velocity#1390]
### Expected Behavior

Connect to the server normally.

### Actual Behavior

Cannot connect to the server. Backend side has no output of players and velocity outputs this:
`[15:09:03 ERROR]: [connected player] MinecraftBaymax (/111.60.194.117:61871): unable to connect to server forge
com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.`
The Arclight has support velocity because velocity supports modern forge but there's something wrong with me!
![QQ_1721721010100](https://github.com/user-attachments/assets/07aa7de0-a00a-45fe-9e32-ca4e59d54dde)

### Steps to Reproduce

1. Start a velocity server and a arclight-forge-1.20.4 server and configure them correctly
2. Use forge client with same mods as arclight server to connect to velocity
3. Unable to connect :(

### Plugin List

Velocity:
luckperms, fastlogin, authmevelocity, cmiv, litebans, maintenance, maintenanceaddon, minimotd-velocity, packetevents, playercrasher, skinsrestorer, slashhub, trchat, voicechat
Arclight:
CMILib, AuthMe, CMI

### Velocity Version

[15:48:41 INFO]: Velocity 3.3.0-SNAPSHOT (git-44b1e0c6-b412)
[15:48:41 INFO]: Copyright 2018-2023 Velocity Contributors。Velocity 以 GNU 通用公共许可证第三版授权。
[15:48:41 INFO]: velocitypowered.com - GitHub

**Comment by Warriorrrr** [comment]
Unable to reproduce, I can connect just fine after configuring the proxy & server correctly. We also do not support those who pirate the game
