### ISSUE TITLE
eaglercraft support

### ISSUE THREAD

**Issue by jolynexoxo** [PaperMC/Velocity#1391]
### Requested Feature

bungeecord has eaglercraft support but velocity does not. so i request to add eaglercraft server feature to velocity. 

### Why is this needed?

eaglercraft is an AOT compiled voxel game inspired from Minecraft designed to run on Javascript. it only provides bungeecord support, so i request to add eaglercraft support to velocity.

### Alternative Solutions

make a plugin

**Comment by electronicboy** [comment]
bungee only supports the minecraft protocol, as does velocity; if you mean eaglercraft supports bungeecord mode, then you can just use legacy forwarding support for that. We're not going to add proto support for random projects out there we have 0 relation to.

e: oh, you mean the plugin for that. We're not going to add native support for this, but, nothing stops them creating a plugin for velocity if they or somebody so desires.
