### ISSUE TITLE
Velocity 3.3.0 Failing to connect to Fabric 1.20.1

### ISSUE THREAD

**Issue by olly-mcleod** [PaperMC/Velocity#1396]
Expected Behavior

Client to connect to fabric server when going through velocity

### Actual Behavior

unable to connect to server modded
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: getsockopt:

### Steps to Reproduce

Not sure

### Plugin List

None

### Velocity Version

3.30.0

### Additional Information

Hi im trying to setup a few servers behind velocity.

Here is the structure:
Velocity [
  Hub Server   (Latest)
  Vanilla Server (Latest
  Fabric Server (1.20.1)

The Hub And Vanilla Servers connect fine however when i try to connect to the fabric server through Velocity i get this error
(/127.0.0.1:51603): unable to connect to server modded
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: getsockopt:

The fabric server is in offline mode. i have the correct version of FabricProxy-Lite installed and the fabric-proxy.toml contains the forwarding secret generated by velocity.
I also have the correct version of CrossStitch Installed and have tried it with and without.

If i revert the fabric server to a normal state as if it had no Proxy clients connect no problem so I've ruled out an issue with the Fabric Server. It is only when trying to connect through velocity.

My Velocity Config is as shows:
 Should we forward IP addresses and other data to backend servers?
 Available options:
- "none":        No forwarding will be done. All players will appear to be connecting
                 from the proxy and will have offline-mode UUIDs.
 - "legacy":      Forward player IPs and UUIDs in a BungeeCord-compatible format. Use this
                  if you run servers using Minecraft 1.12 or lower.
 - "bungeeguard": Forward player IPs and UUIDs in a format supported by the BungeeGuard#                  plugin. Use this if you run servers using Minecraft 1.12 or lower, and are
                  unable to implement network level firewalling (on a shared host).
 - "modern":      Forward player IPs and UUIDs as part of the login process using
                  Velocity's native forwarding. Only applicable for Minecraft 1.13 or higher.
player-info-forwarding-mode = "modern"

Should Velocity pass server list ping requests to a backend server?
Available options:
 - "disabled":    No pass-through will be done. The velocity.toml and server-icon.png
                  will determine the initial server list ping response.
- "mods":        Passes only the mod list from your backend server into the response.
                 The first server in your try list (or forced host) with a mod list will be
                 used. If no backend servers can be contacted, Velocity won't display any
               mod information.
 "description": Uses the description and mod list from the backend server. The first
                 server in the try (or forced host) list that responds is used for the
                  description and mod list.
 - "all":         Uses the backend server's response as the proxy response. The Velocity
                  configuration is used if no servers could be contacted.
ping-passthrough = "mods"

[servers]
Configure your servers here. Each key represents the server's name, and the value
 represents the IP address of the server to connect to.
hub = "IP:20011"
survival = "IP:20010"
modded = "IP:20013"

**Comment by electronicboy** [comment]
> io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: getsockopt

The attempt to open a TCP connection to the target host failed, this is outside of what velocity can control, and is generally down to firewall or network setup issues.
