### ISSUE TITLE
SocketException: Connection reset when connecting to lobby server

### ISSUE THREAD

**Issue by var1nthon** [PaperMC/Velocity#1412]
### Expected Behavior

Players should connect to the lobby server without any issues, maintaining a stable connection throughout the session.

### Actual Behavior

Upon attempting to connect to the lobby, the connection resets, causing the player to be disconnected with the message: "Your connection to lobby encountered a problem."

### Steps to Reproduce

1. Start the Velocity proxy with the provided configuration.
2. Have a player attempt to connect to the lobby server.
3. Observe if the player gets disconnected with a Connection reset error.

### Plugin List

Velocity Proxy Plugins:

ajqueue 2.7.0
authmeproxy 1.0
cmiv 1.0.1.2
geyser 2.4.2-b650
luckperms 5.4.139
matrixbungee 1.0.0
minimotd-velocity 2.1.3-SNAPSHOT+19917d4
miniplaceholders 2.2.4
packetevents 2.4.0
pl-hide-pro 2.10.4
protocolize v2
skinsrestorer 15.4.2
spark 1.10.97
tab 4.1.7
uarvp Build 2b
viaversion 5.0.3
viabackwards 5.0.3
viarewind 4.0.2

### Velocity Version

Booting up Velocity 3.3.0-SNAPSHOT (git-6100e675-b416)

### Additional Information

- The connection resets are sporadic but frequent enough to impact player experience.
- The error log shows that the reset occurs after a short duration of connection to the server.
- The issue persists across different versions of the Velocity proxy.

**Comment by electronicboy** [comment]
Connection reset is a generic network error, you'd need to try to diagnose what is going on from the logs and network monitoring, etc
