### ISSUE TITLE
`Tristate.UNDEFINED` make console unable to run command

### ISSUE THREAD

**Issue by Elikill58** [PaperMC/Velocity#1415]
### Expected Behavior

I want `Tristate.UNDEFINED` doesn't prevent console to be able to run command

### Actual Behavior

Answer "This command doesn't exist"

### Steps to Reproduce

Let me explain.
If you are  using this code:
```java
@Subscribe(order = PostOrder.LATE)
public void onProxyInitialize(ProxyInitializeEvent event) {
	CommandManager commandManager = getServer().getCommandManager();

	commandManager.register(commandManager.metaBuilder("test").plugin(this).build(), new TestCommand());
}

@Subscribe(order = PostOrder.LAST)
public void onOtherPermissionSetup(PermissionsSetupEvent e) {
	e.setProvider((subject) -> ((permission) -> Tristate.UNDEFINED));
}
```
Then, your console can no longer do `/test`. The issue is `Tristate.UNDEFINED` result in same things as `Tristate.FALSE` even if we are the console. As by default, the console has all permissions, it should be normal that the `UNDEFINED` result just result in checking for next things or keep default behavior, instead of breaking it.

In the example, I didn't manage the player. It's only to simplify it, but I'm only talking about the console sender.

### Plugin List

- My test plugin

### Velocity Version

```
Velocity 3.3.0-SNAPSHOT (git-00ed2284-b415)
```

**Comment by electronicboy** [comment]
velocity does not come with default perms, it's 100% on the command impl to handle this

**Comment by Elikill58** [comment]
On the documentation [here](https://jd.papermc.io/velocity/3.3.0/com/velocitypowered/api/permission/Tristate.html), it said "a non-existent setting" but it act as existing (and as "FALSE" value). If you don't write the event, it works fine.

I means, the code has different meaning that the documentation for me.

So:
- No permission check -> you can
- Check that said "idk" -> you can NOT

How that is not a bug? And in fact, it have been used for command, but it's true for almost all permissions checks

**Comment by electronicboy** [comment]
Commands write their own requires check, it's 100% on them to determine how they handle each state

https://jd.papermc.io/velocity/3.3.0/com/velocitypowered/api/permission/Tristate.html#asBoolean()

Anything which directly converts it to a boolean without trying to coerce it a to true by default will result in it being deemed as false. With the information provided here, I don't exactly see what is wrong here.

**Comment by astei** [comment]
> I want `Tristate.UNDEFINED` doesn't prevent console to be able to run command

This has always been defined in Velocity as "I don't know if the user has permission to do this."

The point of this is to permit plugins to provide fallback default permissions when no permissions plugin is enabled, or if that plugin determines that it also doesn't know if the user has permission to perform a given action.

If you want to grant the console all permissions, then you can do this:

```java
@Subscribe(order = PostOrder.LAST)
public void onOtherPermissionSetup(PermissionsSetupEvent e) {
    if (e.getSubject() instanceof ConsoleCommandSource) {
        e.setProvider((subject) -> ((permission) -> Tristate.TRUE));
    }
}
```
