### ISSUE TITLE
Request for PremiumVanish Support in SimplyProxyChat

### ISSUE THREAD

**Issue by MisterMakey** [PaperMC/Velocity#1421]
### Requested Feature

We are currently using SimplyProxyChat on a Velocity network and have encountered an issue where commands like `/msg` do not properly handle interactions with players who are invisible using PremiumVanish. It would be incredibly helpful if SimplyProxyChat could directly support PremiumVanish, allowing these commands to be intercepted and customized messages (like "Player not found") to be displayed.

Since Velocity does not currently offer a CustomCommandMessages feature like BungeeCord, adding native support within SimplyProxyChat would be the ideal solution. This feature would greatly enhance the compatibility and user experience on our server network.

Thank you for considering this request and for your continued hard work on Velocity!

### Why is this needed?

k

### Alternative Solutions

d

### Additional Information

d

**Comment by electronicboy** [comment]
This sounds like you created the issue on the wrong repo
