### ISSUE TITLE
Player with 1.12- are considered using protocol for 1.13

### ISSUE THREAD

**Issue by Elikill58** [PaperMC/Velocity#1430]
### Expected Behavior

1.8.9 players should use 1.8.9 protocol

### Actual Behavior

`player.getProtocolVersion().getProtocol()` return 393 (the version for MC 1.13) instead of 47

### Steps to Reproduce

Use code `player.getProtocolVersion().getProtocol()`, then login to your velocity server with 1.8.9 client (in my case, on 1.21 server with Via*)

### Plugin List

- ViaVersion
- ViaBackwards
- ViaRewind
- My test plugin

### Velocity Version

3.3.0-SNAPSHOT-415

**Comment by electronicboy** [comment]
You’re using a protocol translation system which is going to translate the players protocol version.
