### ISSUE TITLE
forwarding-secret-file ignored

### ISSUE THREAD

**Issue by sleepy-nols** [PaperMC/Velocity#1432]
### Expected Behavior

The forwarding-secret-file is being used to read the forwarding secret

### Actual Behavior

Velocity appends `forwarding-secret = "random_secret"` to the config and uses it instead of the secret in the file. 

### Steps to Reproduce

I am using the default config from 
https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/resources/default-velocity.toml

I have tried setting `player-info-forwarding-mode = "modern"` which did not change the behaviour.

### Plugin List

no plugins

### Velocity Version

```
[17:30:50 INFO]: Velocity 3.1.1
[17:30:50 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[17:30:50 INFO]: velocitypowered.com - GitHub
```

**Comment by powercasgamer** [comment]
You're running an unsupported version of Velocity. Update to the latest 3.4.0 from the [downloads page](https://papermc.io/downloads/velocity).

**Comment by sleepy-nols** [comment]
Why is it unsupported thought? I would think that snapshot builds are experimental, according to your build page, 3.1.1 is the latest stable release. (in other words, why is everything tagged as snapshot?)
Tanks anyway :)

**Comment by electronicboy** [comment]
Because it's a 3 year old version, and sadly due to the turbalance of latest MC releases combined with "this is not our day job", getting to a stable release has taken longer than hoped

**Comment by sleepy-nols** [comment]
Oh well then this seems to be an issue on my side. Should have payed more attention to the release date, sorry for the trouble ^^
