### ISSUE TITLE
Player could not respawn

### ISSUE THREAD

**Issue by LovelyCatEx** [PaperMC/Velocity#1438]
### Expected Behavior

Players should be respawn on their original server

### Actual Behavior

Player could not respawn, but op could

### Steps to Reproduce

Player death

### Plugin List

velocity, ambassador, minimotd-velocity, papiproxybridge, tab, trchat, xconomy

### Velocity Version

Velocity 3.3.0-SNAPSHOT (git-2016d148-b436)

### Additional Information

Console outpus:
[latest.log](https://github.com/user-attachments/files/17173364/latest.log)

**Comment by Nacioszeczek** [comment]
We need you to provide actual reproduction steps and what exactly doesn't work.

**Comment by LovelyCatEx** [comment]
Players need to set a respawn point in their world using a bed, otherwise it will lead to this problem. But it seems that this problem has been solved. Thank you very much.
