### ISSUE TITLE
API for proxy plugins

### ISSUE THREAD

**Issue by Stis780** [PaperMC/Velocity#1452]
### Requested Feature

So I'm thinking, why is there no API for proxy plugins like TCPShield etc? Most of plugins would use reflection and mess with Velocity internals which could result in unpredictable behavior.

Example: https://github.com/TCPShield/RealIP/blob/master/src/main/java/net/tcpshield/tcpshield/velocity/handler/VelocityPacket.java

### Why is this needed?

API allowing to modifying data or even better new event would make this a lot cleaner, easier to debug and probably improved performance if reflection is no longer needed.

### Alternative Solutions

Using reflection, messing with Velocity internals.

**Comment by electronicboy** [comment]
if there are concrete examples of API that would benefit these plugins, they are more than welcome to submit a PR; but, most of these plugins rely on hooking into the internals to get the data that they inject over the network anyways, and that is not exposable in the API, so is not a high consideration, especially when reliable, standardised alternatives are already baked into the proxy
