### ISSUE TITLE
Kick for too big packets when using Axiom

### ISSUE THREAD

**Issue by TheBjoRedCraft** [PaperMC/Velocity#1454]
### Expected Behavior

Dont get kicked

### Actual Behavior

If you execute an larger Action with [Axiom](https://modrinth.com/mod/axiom), like pasting something or painting a large area, you will be kicked from the proxy

### Steps to Reproduce

1. Use [Axiom](https://modrinth.com/mod/axiom) on your backend server
2. Execute a large Operation like pasting something big or painting a large area

### Plugin List

/

### Velocity Version

3.3.0-SNAPSHOT

### Additional Information

About 2 months ago it worked, but now it doesn't

**Comment by Timongcraft** [comment]
Please provide appropriate logs

**Comment by electronicboy** [comment]
We would need more information; 
Is this testable with the free version? do you have something we can paste to reproduce this? (and instructions on doing so)

**Comment by TheBjoRedCraft** [comment]
Yeah you can do it with the free version, you can just select a large landscape of the world and copy it to another location

**Comment by TheBjoRedCraft** [comment]
**How to copy**
1. Open the Editor Menu (default key: r shift)
2. Make a selection with L and R Click on the Mouse
3. Copy the selection with STRG C
4. Move to another place
5. Paste the selection with STRG V

**Comment by TheBjoRedCraft** [comment]
And yeah you can to it with the free version

**Comment by TheBjoRedCraft** [comment]
I downloaded the latest build and there it works, thank you :D
