### ISSUE TITLE
/latest/ Download API

### ISSUE THREAD

**Issue by oddbyte** [PaperMC/Velocity#1458]
### Requested Feature

Hello, I am trying to make a auto-updating Velocity server, but I cant find any way to programmatically get the latest velocity download link

Can you make this a thing / share where such link exists?

### Why is this needed?

For people who need to make an auto-downloader for Velocity

### Alternative Solutions

just make https://api.papermc.io/v2/projects/velocity/versions/latest/builds/latest/downloads/velocity-latest.jar a symlink to the latest jar

**Comment by oddbyte** [comment]
Sorry, i have now been informed that https://versions.velocitypowered.com/download/latest.jar is what i'm looking for.

**Comment by Camotoy** [comment]
That link does not appear to work (and, even if it did, the name implies a very old jar).

If you so desire an auto-update solution, I would recommend doing a Google search for "Paper download API latest version" and finding a solution that works best for you (any field with the Minecraft server version is replaced with the Velocity snapshot version, E.G. `3.4.0-SNAPSHOT`). 

However, we generally don't want people downloading the latest version without understanding what changes have been implemented, which is one of the reasons why a `latest` endpoint does not exist.

**Comment by Timongcraft** [comment]
The docs can also be found here:
https://docs.papermc.io/misc/downloads-api
https://api.papermc.io/docs/swagger-ui/index.html?configUrl=/openapi/swagger-config

**Comment by oddbyte** [comment]
> That link does not appear to work (and, even if it did, the name implies a very old jar).
> 
> If you so desire an auto-update solution, I would recommend doing a Google search for "Paper download API latest version" and finding a solution that works best for you (any field with the Minecraft server version is replaced with the Velocity snapshot version, E.G. `3.4.0-SNAPSHOT`).
> 
> However, we generally don't want people downloading the latest version without understanding what changes have been implemented, which is one of the reasons why a `latest` endpoint does not exist.

This response is mostly incorrect. Lets break it down:

> That link does not appear to work (and, even if it did, the name implies a very old jar).

This latest endpoint in fact does work. It, in fact, is the same file, just with a different name.

> If you so desire an auto-update solution, I would recommend doing a Google search for "Paper download API latest version" and finding a solution that works best for you (any field with the Minecraft server version is replaced with the Velocity snapshot version, E.G. `3.4.0-SNAPSHOT`).

The "Paper download API" is unnecessarily complicated, and makes little sense to me as a backend developer why you would implement it in this way. It "works", but you must jump through several hoops in order to use your recommended solution, including installing unnecessary software, using bash scripts, and is not at all intuitive. 

> However, we generally don't want people downloading the latest version without understanding what changes have been implemented, which is one of the reasons why a `latest` endpoint does not exist.

This seems okay on the surface, however most people really dont care about the changes that have been implemented, and 99% of the time they dont affect them in any way anyways. In the slight chance something breaks, it is probably because they forgot to update a plugin along with the server.

**Comment by oddbyte** [comment]
# Update:

https://mineacademy.org/api/velocity/latest has the latest velocity version. Check https://mineacademy.org/endpoint to see which server software they support

**Comment by kangarko** [comment]
Not sure about the downvote, we built this endpoint with permission from core Paper team to supply their lack of latest endpoint. It works fine for over a year now!
