### ISSUE TITLE
Disconnection and Reconnection Issue with Velocity and Modded Backends

### ISSUE THREAD

**Issue by Marlon2025c** [PaperMC/Velocity#1463]
### Expected Behavior

Players should not be disconnected when switching between the lobby server and backend servers.

### Actual Behavior

When switching from the lobby server to a backend server (or vice versa), I frequently receive a "Lost connection" or "Please reconnect" message.

### Steps to Reproduce

1. Set up Velocity with the provided configuration (velocity.toml below).
2. Configure at least two backend servers using Mohist 1.20.1.
3. Install the plugins listed below on the proxy and backend servers.
4. Connect to the lobby server through Velocity.
5. Use a server selector plugin (ServerSelectorX) to switch to server1.
6. Observe the frequent "Lost connection" or "Please reconnect" messages.

### Plugin List

Proxy plugins (Velocity):
- LuckPerms
- Ambassador-Velocity

- Backend plugins (Mohist 1.20.1):
- EssentialsX
- ViaVersion
- PlaceholderAPI
- ServerSelectorX
- AntiWorldDownloader
- LPC
- WorldBorder

### Velocity Version

velocity 3.4.0-SnapShot

### Additional Information

Velocity Configuration (velocity.toml):
```
# Abbreviated example. Full configuration can be provided if needed.
motd = "SpaziaCraft"
show-max-players = 999
online-mode = true
force-key-authentication = true
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
ping-passthrough = "mods"

[servers]
lobby = "192.168.1.174:25566"
server1 = "192.168.1.174:25567"
server2 = "192.168.1.174:25568"

try = ["lobby"]
failover-on-unexpected-server-disconnect = false
```
List of Mods on Backend Servers:

- [1.20.1] SecurityCraft
- Biomes O' Plenty
- Chisel
- Iron Chests
- Refurbished Furniture
- TerraBlender

Velocity Logs: 
![Image](https://github.com/user-attachments/assets/b1269357-3033-442a-a85f-c9dc6add8cf1)

Lobby Server Logs (Mohist): 
![Image](https://github.com/user-attachments/assets/822a3db2-f708-442e-ab73-e36e9e27fb35)

Server1 Logs (Mohist):
![Image](https://github.com/user-attachments/assets/6354d63d-304d-4294-9e80-f4dde943bd2f)

**Comment by electronicboy** [comment]
"please reconnect" comes from your plugins, Ambassador; This is generally due to being in a state where the plugin cannot perform a server transfer all on its own without client mods, etc (and, this setup is generally unsupported by us)
