### ISSUE TITLE
Server kicks

### ISSUE THREAD

**Issue by GothkittyGirl** [PaperMC/Velocity#1471]
### Expected Behavior

Hey there .... suppose to just write the msg not kick people happens alot after typing ... with some words

### Actual Behavior

i type Hey there ... and it kicks everyone from the server in all servers

### Steps to Reproduce

just type in 

hey there ...
pffft... it's fun
was hoping for a repeat.. lol

### Plugin List

[https://puu.sh/Kk6g2/7d2f8d15a7.png](url) 
[https://puu.sh/Kk6hj/9bef375a4a.png](url) 
[https://puu.sh/Kk6hu/aaa833c1a9.png](url) 
[https://puu.sh/Kk6hy/979c7f3c1c.png](url)

### Velocity Version

velocity-3.4.0-SNAPSHOT-454.jar

**Comment by electronicboy** [comment]
There is nothing actionable here for us, no errors, no kicks, etc

**Comment by GothkittyGirl** [comment]
it was a op thing with one of the plugins i think now because it happens on all my servers and theres a few plugins in common with all of my servers

**Comment by electronicboy** [comment]
Velocity has 0 concept of OP, and so this is going to likely be a backend server issue
