### ISSUE TITLE
IV should not equal key

### ISSUE THREAD

**Issue by cryptochecktool** [PaperMC/Velocity#1473]
### Expected Behavior

In your code: https://github.com/PaperMC/Velocity/blob/965db127a9ce193a0fb9c2a7e198edc885d8cfb8/native/src/main/java/com/velocitypowered/natives/encryption/JavaVelocityCipher.java#L52
Use IV=key.
But iv should be set to a sufficiently random number, otherwise it will lead to a CPA attack.
If IV=key, then CCA attacks will be allowed, that is, only need to send a specific message for encryption, then the key can be restored.
For specific attack methods, see: [https://cedricvanrompay.gitlab.io/cryptopals/challenges/[27](https://cedricvanrompay.gitlab.io/cryptopals/challenges/27](https://cedricvanrompay.gitlab.io/cryptopals/challenges/%5B27%5D(https://cedricvanrompay.gitlab.io/cryptopals/challenges/27). html).html

### Actual Behavior

...

### Steps to Reproduce

...

### Plugin List

...

### Velocity Version

...

**Comment by valaphee** [comment]
Velocity has to use the same IV as Minecraft, and its an already known weakness

```java
public static Cipher cipherFromKey(int opMode, Key key) throws NetworkEncryptionException {
	try {
		Cipher cipher = Cipher.getInstance("AES/CFB8/NoPadding");
		cipher.init(opMode, key, new IvParameterSpec(key.getEncoded()));
		return cipher;
	} catch (Exception var3) {
		throw new NetworkEncryptionException(var3);
	}
}
```

**Comment by astei** [comment]
Closing as irrelevant. This is a cryptographic weakness in the Minecraft protocol, and I do not consider Minecraft protocol encryption to be secure in any way.
