### ISSUE TITLE
Can‘t work with leaves-1.21.3-83

### ISSUE THREAD

**Issue by zlink2010** [PaperMC/Velocity#1476]
### Expected Behavior

connect to the other server(using Leaves-1.21.3-83)

### Actual Behavior

report an error:The player is already in the server.

### Steps to Reproduce

1.connected the first server(using Paper1.21.3-81) without reporting error.
2.tried connect the second server(using Leaves-1.21.3-83).
3.reported an error

### Plugin List

velocity:none
backend:
Paper Plugins:
 - spawn_spot_protect
 Bukkit Plugins:
 - AuthMe, eBackup, EntityClearer, GrimAC, GroupManager, IpacPER, IpacWhitelist, PlaceholderAPI, ProtocolLib, ServersNPC,
 SetHome, SimpleTpa, SkinsRestorer, SuperVanish, TabTPS, Vault, XConomy

### Velocity Version

Velocity 3.4.0-SNAPSHOT (git-4aa9ee77-b455)

### Additional Information

[latest（the backend server）.log](https://github.com/user-attachments/files/18163856/latest.the.backend.server.log)

**Comment by electronicboy** [comment]
We do not provide support for offline mode setups; Your backend server logs show plugins throwing exceptions when *writing* packets out of the network, which velocity has 0 influence over
