### ISSUE TITLE
Auto restrat feuture

### ISSUE THREAD

**Issue by masood151117** [PaperMC/Velocity#1482]
### Requested Feature

Auto restart

### Why is this needed?

cleanup memory and better perfomance

### Alternative Solutions

.

### Additional Information

Hello, please add an auto-restart to it so that anyone who likes to enable it can use that feature. I have many plugins on the server that fill up the memory after a certain period of time or have a negative effect on the performance of the proxy, such as voice chat, etc., and I want to restart the proxy automatically every day. If possible, add this simple feature

**Comment by U5B** [comment]
The best way to do this is via a plugin or externally

You could try out this plugin: https://www.spigotmc.org/resources/1-8-8-1-21-4-ultimateautorestart-need-an-autorestart-plugin-grab-the-best-one-today.64414/

**Comment by astei** [comment]
Closing as not planned. This type of thing is usually better handled outside of the proxy.

**Comment by masood151117** [comment]
there is no plugin to restart proxy

**Comment by Skullians** [comment]
> there is no plugin to restart proxy

This is why common web management panels, such as pterodactyl, pufferpanel, crafty, AMP, moonlight etc have restart systems built in, just for this!

If you want scheduled restarts or whatever, set up a script for it, or use your web panel’s schedules system if present.

Hence ‘better handled **outside** of the proxy.’
