### ISSUE TITLE
Expose scheduler data via API

### ISSUE THREAD

**Issue by alexstaeding** [PaperMC/Velocity#276]
The scheduler's implementation has information such as the current list of tasks available that is not (but could be) exposed via the API.

Additionally, it would be useful to have a `builder()` method with no args that returns a `TaskBuilder`. That way, all task properties can be set via the `TaskBuilder` which is more consistent than requiring two properties in order to construct the `TaskBuilder` in the first place.

**Comment by astei** [comment]
I followed an idiomatic pattern when I made `buildTask()` explicitly require the plugin and runnable to execute. It might be slightly cleaner to have a `TaskBuilder` to pre-populate this information, but I'm not swayed.

I'd be open to exposing more data through the scheduler API. Any ideas?

**Comment by astei** [comment]
Closing as there has been no real response for several months now.

**Comment by MrIvanPlays** [comment]
Having a `getTasksByPlugin` would be a good start. Proper builder too, but for people that don't like smol builders ( ~~like me :eyes:~~ ) we could have also a `scheduleDelay` and `scheduleRepeat` methods consuming all necessary stuff for the task type. 
I'm ready to open a PR to the 2.0.0 branch.
