### ISSUE TITLE
[1.1.0] Reimplement #149 (send just one respawn packet on server switch) for < 1.16 clients

### ISSUE THREAD

**Issue by Leymooo** [PaperMC/Velocity#372]
After 1.16 changes #149 (https://github.com/VelocityPowered/Velocity/commit/39e48c9467a5308dd2db3daeacbcd5657c788b12) was discarded (https://github.com/VelocityPowered/Velocity/commit/cd9bb61f208e3b27da9fbdcb4bf6cafc9135be65#diff-841534de988d03173f1983984bc82b9fe24e2bd3296db704a3bd6412b32674eaL337).

Respawn and JoinGame packets trigger full GC. So 2 respawn packets slow down server switch proccess.

**Comment by astei** [comment]
Fixed

**Comment by LuminousLoreBloom** [comment]
git commit --author/co-author=Leymooo?
