### ISSUE TITLE
CompletableFuture potentially swallowing exceptions

### ISSUE THREAD

**Issue by A248** [PaperMC/Velocity#374]
A link Crypnotic posted to LoginSessionHandler caught my attention. From what I can tell, the use of CompletableFuture in LoginSessionHandler has the potential to swallow exceptions.

https://github.com/VelocityPowered/Velocity/blob/fd6394517595e291e95bca5f60cb1a68bc18c8de/proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java#L255

thenAccept(Async), thenRun(Async), and all other transformation methods on CompletableFuture not related to exception handling store any thrown unchecked exceptions in the returned future wrapped in CompletionException, but if the using code discards this future, the stored exception is lost.

**Comment by astei** [comment]
That is not really an issue, since the fire method catches all the exceptions and logs them, never throwing an exception. The issue he is having is completely different.

**Comment by A248** [comment]
No, I'm suggesting it is proxy code, not event listeners, which may throw an unchecked exception, inside the thenAcceptAsync callback.

**Comment by astei** [comment]
I will need proof that a problem actually exists.

**Comment by A248** [comment]
```java
	@Test
	public void testSwallowExceptions() {
		java.util.concurrent.CompletableFuture.runAsync(() -> {
			System.out.println("Pre throw");
			// Can also throw here and achieve the same result
		}).thenRunAsync(() -> {
			System.out.println("Throwing...");
			throw new RuntimeException();
		});
	}
```

I'm not saying there are any exceptions being swallowed at the moment, merely that if an unchecked exception were to be thrown, it would not be detected.

The key thing to note is these are futures which are neither awaited nor have any dependent actions.

**Comment by Gabik21** [comment]
Took me an eternity to debug one of these. It is very frustrating that CompletableFutures behave that way. It looks so ugly to glue that block to every one of these:
```java
        .exceptionally(throwable -> {
          throwable.printStackTrace();
          return null;
        });
```
