### ISSUE TITLE
[2.0.0] Consider bumping to Java 11 as a minimum

### ISSUE THREAD

**Issue by astei** [PaperMC/Velocity#381]
Velocity 2.0.0 won't be releasing for some time but we need to at least start this discussion.

Velocity 1.x.x requires at least Java 8 as the minimum version of Java. This has the widest possible range of compatibility but it limits the features and performance improvements we can do. For Velocity 2.0.0 I propose we bump the minimum to Java 11. Why would we want to move to Java 11?

* [A future major version of Netty will require Java 11 at minimum.](https://github.com/netty/netty/pull/10650)
* We get access to all the new features introduced with Java 9, 10, and 11
* We can clean up code that now compiles under Java 11 but wouldn't under 8 without doing ugly stuff like `MethodHandles`

Of course there are reasons against the move, and it is that hosts often do not offer anything other than Java 8 - the problem with this line of thought is that if someone doesn't force the transition, then it won't ever happen. There is also the consideration that some servers depend on Java 8 exactly (mostly Sponge). The user can install Java 8 to run Sponge if this is an issue.

**Comment by MrIvanPlays** [comment]
> hosts often do not offer anything other than Java 8 - the problem with this line of thought is that if someone doesn't force the transition, then it won't ever happen.

I have a friend who's the owner of a hosting company, and when I asked him why he's not upgrading from java 8 he said "because I'm scared of breaking something. Once I tried, and one of the ssds of the server were gone. Also we had problems with plugins refusing to load". In my opinion the decision of enforcing a new java version should be left to Mojang, although there are very strong points of migrating to java 11 too.

**Comment by mikroskeem** [comment]
Decent hosting companies should always provide a way for people to change Java version, so clients could pick e.g (still) 7, 8, 11 or 15.

> and one of the ssds of the server were gone

Not going to lie, losing a SSD after upgrading Java sounds like a very stupid excuse or pure incompetence.

**Comment by iamceph** [comment]
That would be awesome!

**Comment by Justsnoopy30** [comment]
+1 for this (raising Java version requirement to 11)

**Comment by astei** [comment]
There is generally a consensus that we should move forward with this. We do not anticipate a Velocity 2.0.0 release until well after the release of the next Java LTS version (Java 17) anyway.

I am looking forward to the improved performance, new features, and code cleanups we can now do thanks to requiring Java 11.
