### ISSUE TITLE
[2.0.0] Switch completely to Configurate

### ISSUE THREAD

**Issue by astei** [PaperMC/Velocity#386]
For Velocity 2.0.0 it is my intention for Velocity to stop depending on Night-Config and switch to Configurate instead for better maintainability and to be on par with the rest of the Velocity plugin ecosystem. This will likely mean a switch away from TOML, as the only TOML serializer for Configurate is backed by a library we had to deliberately abandon due to the number of issues we had with it.

**Comment by LuminousLoreBloom** [comment]
Would there be an automatic conversion process in code for old format configs (or is this a user responsibility)? If so, how would we recognise the config properties without the TOML lib imported by Maven/Gradle?

**Comment by astei** [comment]
We'll cross that bridge when we get there. We still need to iron out issues in the Velocity 1.1.x series first.

**Comment by astei** [comment]
#414 duplicates this but there is more useful discussion there. Closing this issue.
