### ISSUE TITLE
Support tunnelling arbitrary Brigadier argument types where possible

### ISSUE THREAD

**Issue by astei** [PaperMC/Velocity#389]
We are seeing more and more mods adopt custom Brigadier argument types. This poses a challenge to us for continued mod support on Velocity.

There's two options here:

1. Provide a mod that creates a new command type and "smuggles" the original command type to the proxy. Once we are ready to send the `AvailableCommands` packet, we will eliminate this command type and send what the mod was expecting.
2. Disable intercepting `AvailableCommands` entirely (or just pass it through if we fail to deserialize anything).

We are going to try (1) as while it will be more work, it will also be the most feature-rich solution.

**Comment by jacoballen1** [comment]
What drawbacks will we experience if we just pass it through if deserialization fails? Just wondering if this solution may be easier for native support.

**Comment by astei** [comment]
Commands from the proxy won't show up and we won't be able to fire `PlayerAvailableCommandsEvent`.

**Comment by jacoballen1** [comment]
Ah I see
