### ISSUE TITLE
Error: "Fallback server lobby is not registered in your configuration."

### ISSUE THREAD

**Issue by crispyricepc** [PaperMC/Velocity#391]
I can't get the proxy to start with my configuration file. The only values I've changed are the ones found in `servers` and `forced-hosts`. I removed the default config called `lobby`, since I know I don't need a lobby server for my setup.

Is the lobby server required? I really don't want to use one as it doesn't fit how I'll be using this proxy

**Comment by astei** [comment]
The Velocity bug tracker is not a support channel. No, a lobby server is not required, and you left the lobby server specified in a forced host. Leave that section empty if you don't want a forced host.

**Comment by crispyricepc** [comment]
Hmm, strange

I've purged all mention of `lobby` from my config file, the only place `lobby` is referenced is in the source code, thus I still believe this is a bug.

Ther error is thrown here
https://github.com/VelocityPowered/Velocity/blob/e3f17eeb245b8d570f16c1f2aff5e7eafb698d5e/proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java#L151

The server `s` seems to be got from here 
https://github.com/VelocityPowered/Velocity/blob/e3f17eeb245b8d570f16c1f2aff5e7eafb698d5e/proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java#L510

Again there is no mention of lobby in my config file.

**Comment by Crypnotic** [comment]
Did a quick test. Can confirm that `ImmutableList.of("lobby")` causes the error, but only when the `try = []` block is deleted.

@CRISPYricePC a fix for now is to add `try = []` under the servers block

**Comment by astei** [comment]
Please paste your configuration. I genuinely don’t believe this is a Velocity bug.

**Comment by Crypnotic** [comment]
https://paste.gg/p/anonymous/38bd0889133a4a46a2dcfdbffa6d9d88

This configuration would fail as the `try` block has been removed.
Which uses the immutable list fallback of just `lobby` here 
https://github.com/VelocityPowered/Velocity/blob/e3f17eeb245b8d570f16c1f2aff5e7eafb698d5e/proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java#L529

Edit: This is less of a bug, more someone completely removed the try block since they didn't need it. Which had unintended consequences

**Comment by titivermeesch** [comment]
I can indeed confirm this. A bit weird that this issue is still closed since it's definitely some sort of issue. Or a lack of information in the documentation

**Comment by titivermeesch** [comment]
FYI I tested this with v3.3.0 and the issue seems to be resolved. I can now properly handle dynamic lobby registration without some hacky workarounds

**Comment by AndrobaL** [comment]
> FYI I tested this with v3.3.0 and the issue seems to be resolved. I can now properly handle dynamic lobby registration without some hacky workarounds

Hey can I ask you what do you mean by "some hacky workarounds" ? I'm interested

**Comment by titivermeesch** [comment]
> > FYI I tested this with v3.3.0 and the issue seems to be resolved. I can now properly handle dynamic lobby registration without some hacky workarounds
> 
> Hey can I ask you what do you mean by "some hacky workarounds" ? I'm interested

I don't remember exactly since it's been a while, but it consisted of starting a fake lobby server (just an empty paper server running), waiting on my load balancer to launch the initial lobbies, registering those and then unregistering the old one
