### ISSUE TITLE
Got an unexpected error code 500 whilst contacting Mojang to log in Skerit

### ISSUE THREAD

**Issue by skerit** [PaperMC/Velocity#393]
I've been getting this message since last night for a few players (myself included). Sometimes it takes 4-5 attempts to actually make it on to the server. A 500 error code does indicate it's a problem on their end, anyone else know something more?

**Comment by mikroskeem** [comment]
According to https://status.mojang.com/check, session server is down right now. "Works as intended"

**Comment by astei** [comment]
Not a Velocity issue

**Comment by astei** [comment]
The session servers have been acting a bit weird since last night but do seem to be up for me.
