### ISSUE TITLE
Open inventory for player

### ISSUE THREAD

**Issue by semenishchev** [PaperMC/Velocity#394]
I want to do a server selector gui with velocity. But i didn't found any code for inventory.

**Comment by Xernium** [comment]
That is correct and there isn’t going to be any. Velocity is a proxy and this is outside of the scope of a proxy. (Even Bungeecord doesn’t have that)   

You can either create and add the packets in question yourself with a plugin or, send a plugin channel message to the server you’re currently on and have that send you the packets in question.   

Note that the first option is highly discouraged and can not be done using the API, hence you will not get support for it. We can and will break this part as we see fit, even during API release versions.

**Comment by astei** [comment]
Adding support for inventories on the proxy only rises to the level of "cool, but impractical". It's a lot of added headache with almost no real gain for us.

**Comment by semenishchev** [comment]
Solved
