### ISSUE TITLE
Wrong amount of packet on 1.8 servers

### ISSUE THREAD

**Issue by Elikill58** [PaperMC/Velocity#395]
Hi,
I'm a developer which use the amount of Flying packet (include Flying, Look, Position and Position Look).

I just found that on Velocity (and not on bungee) I have a problem :
On 1.8 server, with 1.15 or 1.16 client, I get at least 20 flying packets constantly.

I tried with 1.15 server and the error disapear. I tried also with 1.8 client on both servers, and I didn't get this problem.

I'm using ViaVersion 3.2.0 everywhere (Spigot & Velocity servers)

**Comment by Gabik21** [comment]
This is not a velocity issue. The protocol spec. when a flying packet is sent changed over time. A 1.8 Client sends one every tick and ViaVersion will emulate that behaviour for newer Clients on a 1.8 Server for compatibility reasons.

**Comment by Elikill58** [comment]
But on Bungeecord i didn't get this problem (same when it's not with proxy).
And why some position packet, which are flying one, are not count as flying ?
Because I have 20 flying packets all the times, even when moving (and when moving, I also get position...).

**Comment by Gabik21** [comment]
That is impossible. Velocity cannot be a factor in this, because there is no implementation for en- or decoding of flying packets. They are forwarded as-is from the client.

**Comment by Elikill58** [comment]
Ok so you suggest to me to report this to ViaVersion ?

**Comment by astei** [comment]
This doesn't sound like a Velocity issue to me.

> I'm using ViaVersion 3.2.0 everywhere (Spigot & Velocity servers)

This is not a setup the ViaVersion developers recommend.
