### ISSUE TITLE
The ArchitectureCraft mod gui interface cannot be used after  cross-server

### ISSUE THREAD

**Issue by misako227** [PaperMC/Velocity#397]
Hello，
This mod cannot be used after cross-server，I don't know which side is the problem.
If you have time, please help me look at this,Thanks.

ArchitectureCraft :[https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev](https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev)

Velocity version : velocity-1.1.2
player-info-forwarding-mode = "legacy"

Server version：
    Minecraft: 1.12.2
    SpongeAPI: 7.3-7127e0882
    Sponge: 1.12.2-7.3.0
    SpongeForge: 1.12.2-2838-7.3.0
    Minecraft Forge: 14.23.5.2847
    JVM: 1.8.0_211/64-bit (Oracle Corporation)
    OS: Windows 10 (10.0/amd64)

**Comment by astei** [comment]
This is likely to be a mod issue. I don't have enough experience with Forge to debug this, however.

**Comment by misako227** [comment]
> This is likely to be a mod issue. I don't have enough experience with Forge to debug this, however.

Well, thank you for your response.
