### ISSUE TITLE
kicked from server lobby: Timed out

### ISSUE THREAD

**Issue by luciobortoletto** [PaperMC/Velocity#398]
When a player joins the server, the chunks load slowly, everything is loading slowly and some times the player get kicked with: "kicked from server lobby: Timed out". I need help as soon as possible. Sorry for the bad english

**Comment by luciobortoletto** [comment]
A clarification: this happens only from other wifis or when I join the server with the public ip

**Comment by luciobortoletto** [comment]
Version: ![Cattura2](https://user-images.githubusercontent.com/52795018/101364273-ab04ad80-38a2-11eb-92fc-c7577f984b34.PNG)

**Comment by Xernium** [comment]
Are there errors in the Velocity or the Server logs? If not we will just have to assume the reasonable thing happened: The connection timed out. Did you measure your latencies?

**Comment by luciobortoletto** [comment]
No, there isn't any error. How can I measure my latency?

**Comment by luciobortoletto** [comment]
Another thing: this happens every time

**Comment by Xernium** [comment]
I would recommend you test the latency of your target machine with both ICMP ping and TCP ping. 
Side-note: This issue is invalid. If you can get it working fine on your own network, then your routing or Link/NAT is at fault and not Velocity

**Comment by luciobortoletto** [comment]
ok
