### ISSUE TITLE
Your connection to SERVER ecountered an error

### ISSUE THREAD

**Issue by Niketion** [PaperMC/Velocity#408]
![image](https://user-images.githubusercontent.com/20048349/103096965-00142380-4606-11eb-8df7-2039a437a525.png)
As you can see from the image, every time I enter the server administrators (with * permission on luckperms) are ejected after a few minutes
No error in console

**Comment by astei** [comment]
Try restarting Velocity with the `-Dvelocity.packet-decode-logging=true` startup option (before the `-jar` in your startup command).

**Comment by Niketion** [comment]
![image_2020-12-25_13-10-38](https://user-images.githubusercontent.com/20048349/103134862-871fd500-46b4-11eb-8c81-46d3eeb11ff5.png)
this is the error

**Comment by astei** [comment]
We can't do anything about the server sending malformed packets
