### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by TheLeCrafter** [PaperMC/Velocity#413]
Information:
Server name: mainisland
Server port: 25601
Server version: paper-1.16.4-412
I followed the steps at the velocity wiki for the configuration of the paper.yml, spigot.yml and the velocity.toml.

**Comment by TheLeCrafter** [comment]
My velocity version is 1.1.3

**Comment by Xernium** [comment]
This is a networking issue on your end you need to figure out yourself. Looks like the port you’re trying to access isn’t open or firewalled in some capacity.

**Comment by astei** [comment]
Velocity cannot connect to your server. Please double check that the server is running, that it is running on the correct IP and port, and that a firewall isn't interfering.

**Comment by TheLeCrafter** [comment]
Thank you. I accidentally mistyped the port. I'm sorry for this inconvenience but thank you.
