### ISSUE TITLE
Tab completion/suggest in Brigadier commands?

### ISSUE THREAD

**Issue by itsTyrion** [PaperMC/Velocity#417]
I've been crawling through docs and source code over the last 20 minutes, trying to locate the new way for suggestions with no success.

Would be helpful to have an example of that in the docs

**Comment by quantiom** [comment]
https://jd.velocitypowered.com/1.1.0/com/velocitypowered/api/command/InvocableCommand.html

**Comment by astei** [comment]
The issue tracker is intended for issues with Velocity. It is not a general support forum. Here's some resources you can look at for reference:

**Comment by astei** [comment]
(forgot the actual references!)

https://fabricmc.net/wiki/tutorials:commands:suggestions
https://github.com/VelocityPowered/Velocity/blob/dev/1.1.0/proxy/src/main/java/com/velocitypowered/proxy/command/builtin/GlistCommand.java#L39

I am going to close this issue now. If you have any more questions, [please join our Discord](https://discord.gg/8cB9Bgf) which is meant for help with all sorts of issues.
