### ISSUE TITLE
Not able to connect Fabric server to Velocity

### ISSUE THREAD

**Issue by Janilom** [PaperMC/Velocity#418]
I have Velocity setup with a lobby using Paper 1.16.4.
I have an AllofFabric3 server setup and fabricproxy installed and configured.
I also have a Paper 1.16.4 survival world setup.
My velocity.toml is setup with all 3 servers and they all show up in the /server list.

I am able to use a vanilla launcher and reach my lobby as well as survival worlds without issue.
If I try connecting to the fabric server it times out .

If I launch with the AllofFabric3 launcher I am not able to connect to the lobby which is running 1.16.4.

If these can all work together, what am I missing and doing incorrectly. 
I may have totally misunderstood the capabilities of Velocity as well and its not intended to work this way.

Any help is appreciated.
Thank you

**Comment by Xernium** [comment]
Could you please provide the server and proxy logs and the output of /velocity dump and have you tried this with our Fabric mod that adds an additional layer of compatibility? You might need it https://www.curseforge.com/minecraft/mc-mods/crossstitch

**Comment by astei** [comment]
You will probably need to install [CrossStitch](https://www.curseforge.com/minecraft/mc-mods/crossstitch) on the server.

**Comment by astei** [comment]
Closing this issue as there has been no reply in over 3 weeks, if you're still having a problem please join our [Discord](https://discord.gg/8cB9Bgf)

**Comment by DefomCode** [comment]
+
