### ISSUE TITLE
Client won't exit automatically when the server disconnect it

### ISSUE THREAD

**Issue by MCUmbrella** [PaperMC/Velocity#420]
Players are still connected to the proxy when they are kicked by the server or the server is shutting down. After 30 secs their client will show a "timed out" message and disconnect.
Tried newest 1.1.x build and the problem still exists.

https://user-images.githubusercontent.com/40854260/105622265-fff88500-5e4a-11eb-9a90-16e7e972bd4e.mp4

**Comment by astei** [comment]
Unable to reproduce this issue. In order for us to completely diagnose the issue we would need the output of `/velocity dump`. In addition, you are using authlib-injector, which is something we do not support.

**Comment by MCUmbrella** [comment]
OK I just tried the original online mode and it still happens. When should I type `/velocity dump`?

**Comment by astei** [comment]
At the console. Remove the slash in front.

**Comment by MCUmbrella** [comment]
Here it is
https://dump.velocitypowered.com/ovevexefik.json

**Comment by astei** [comment]
My guess is that Velocity is trying to fallback to the other server you have on the `try` list, but it is failing. Did you want the fallback?

**Comment by MCUmbrella** [comment]
No. I cleared try[] left only "lobby", tried to set `failover-on-unexpected-server-disconnect` to false and got the same result

**Comment by MCUmbrella** [comment]
I just let it regenerate a config and changed servers. It works well now so I guess there's something wrong in my old config but I'm not sure where it is

**Comment by MCUmbrella** [comment]
It looks like it happened after I changed some messages. I have written two `%s` in a message which only have 1 variable. This is the cause of this problem. Thank you for your help!
![图片](https://user-images.githubusercontent.com/40854260/105626568-6a212200-5e6b-11eb-80de-6fc3bb1c5f23.png)
