### ISSUE TITLE
Compatibility with spigot server

### ISSUE THREAD

**Issue by Xharos** [PaperMC/Velocity#425]
Hey,

I'm currently building a custom server and I'm very interested in works with velocity instead of Bungeecord (needs to fix bugs by myself back in the day).
I'm struggling for my need to work with Spigot and I'm aware of compatibility issue with velocity according to your documentations :
Spigot
Spigot is not well-tested with Velocity. However, it is based on vanilla and as it is the base for Paper, it is relatively well-supported.

Spigot does not support Velocity's modern forwarding, but does support legacy BungeeCord forwarding.

In term of performance, it is useful to use velocity with legacy forwarding? In this case, it does not make advantage of the security you offer ?

I've created a netty handler to handle all the packet before the server does :
- https://github.com/islands-wars/islands/tree/develop/api/src/main/java/fr/islandswars/api/net

Can you list all the modifications I need to make to handle modern forwarding or is it over complicated?

Thanks a lots
Val

**Comment by Xernium** [comment]
See https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0298-Add-Velocity-IP-Forwarding-Support.patch for the modifications needed for modern forwarding

**Comment by Xernium** [comment]
There is no real performance difference, but there is the question of the additonal security it offers. Do note that the system this uses (login plugin channel messages) are only available on 1.13 or newer.

**Comment by toinouH** [comment]
I tested Velocity and a fork of Paper and the modern IP forwarding worked in my case.
That part of the doc has not been updated: sorry for the confusion :/.

**Comment by Xharos** [comment]
Dam that was a quick answer.
So with the latest version of spigot, I just need to run the patch and I will be free to use modern forwarding and also benefits the security?

**Comment by astei** [comment]
The patch cannot be applied as-is as it requires other Paper patches. You're much better off just running Paper anyway, but if you want to port the patch to run atop regular Spigot, that is your prerogative, but officially we only support Paper (and Paper derivatives) and Fabric for modern forwarding.
