### ISSUE TITLE
Command packet parsed wrongly with redirection

### ISSUE THREAD

**Issue by TheMode** [PaperMC/Velocity#429]
Without velocity:
<img width="301" alt="Screenshot 2021-02-16 at 06 54 22" src="https://user-images.githubusercontent.com/8581638/108023884-cd921000-7023-11eb-946b-2d9a83537e59.png">
With velocity:
<img width="309" alt="Screenshot 2021-02-16 at 06 55 41" src="https://user-images.githubusercontent.com/8581638/108023991-fdd9ae80-7023-11eb-986b-b5a49d937225.png">

The issue is that velocity is always redirecting the "step" literal to the first syntax where it appears. Except that preceding arguments do not match, meaning that this "optimization" shouldn't happen.

I am running the newest stable 1.1.4 version, without any plugin or forwarding.

Here is the link to the server jar I am using https://cdn.discordapp.com/attachments/786079397110874135/811112753715609610/server.jar
It is likely that I am messing with the packet in a way that velocity doesn't expect, I do however consider it an issue since it conforms to the protocol.

I do not think that it is necessary (given that it is from my own framework), but here is the command code https://pastebin.com/2D47yzQx and my ugly serializer algorithm https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/command/CommandManager.java#L424 https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/command/builder/arguments/ArgumentLoop.java#L62

**Comment by astei** [comment]
Interesting catch, and I'm fairly certain I know what the bug here is. Try the `fix/id-mapper-identity-hashing` branch and see if it works.

**Comment by TheMode** [comment]
It seems to have fixed it, thanks!

**Comment by astei** [comment]
Fix has been merged in now.
