### ISSUE TITLE
Command implementation overhaul

### ISSUE THREAD

**Issue by hugmanrique** [PaperMC/Velocity#432]
The new Command API introduction focused on clean API design patterns (separation of concerns, meta builders) over an optimal implementation that exclusively relied on Brigadier command parsing for execution, tab completion suggestions, and permission handling.

Brigadier uses a typed argument parser, which means we have had to emulate some of its responsibilities for the `String[] args`-style commands (this includes `SimpleCommand`, `RawCommand` and the deprecated `Command` methods), which Mojang removed from the game in 1.13. This has resulted in multiple bugs (https://github.com/VelocityPowered/Velocity/commit/648624d33317751dad5e820c66b67548eb92083a, https://github.com/VelocityPowered/Velocity/commit/523b61e0c7d3803e25bed90574221b73b213fcd4, https://github.com/VelocityPowered/Velocity/commit/65e1b7be8732f544f3ea0a77d2f5767f9b1ef84f), all of these coming from the "hacky" way in which we create `CommandNode`s to support the typeless argument parsing in [CommandNodeFactory](https://github.com/VelocityPowered/Velocity/blob/648624d33317751dad5e820c66b67548eb92083a/proxy/src/main/java/com/velocitypowered/proxy/command/CommandNodeFactory.java) and [BrigadierUtils](https://github.com/VelocityPowered/Velocity/blob/648624d33317751dad5e820c66b67548eb92083a/proxy/src/main/java/com/velocitypowered/proxy/util/BrigadierUtils.java). Most recently, itsTyrion and Cableguy20 discovered an issue with "`/` + <tab>" suggestions not checking for permissions. Cable has drafted a fix in https://github.com/alexstaeding/Velocity/commit/f98cf4098291c802435d5b3b0b6cd7677cad5c97, but it further builds on the current way to perform permission-checking logic during command execution, instead of during parsing (which is also used for tab completion suggestions). My [initial suggestion](https://discord.com/channels/472484458856185878/472486015525847050/813169822766465064) was to further re-implement logic which Brigadier already supports (and is tested thoroughly).

~~On further inspection, I instead propose to create a subtype of `ArgumentCommandNode`, called `RawArgsCommandNode` that acts as an adapter between Brigadier methods like `CommandNode#listSuggestions` and the corresponding Velocity methods (`InvocableCommand#suggestAsync`).~~ (I opted to PR some changes to Velocity's Brigadier fork). This will allow us to remove `CommandNodeFactory` and some methods from `BrigadierUtils` ([`buildRedirect`](https://github.com/VelocityPowered/Velocity/blob/648624d33317751dad5e820c66b67548eb92083a/proxy/src/main/java/com/velocitypowered/proxy/util/BrigadierUtils.java#L33) and [`buildRawArgumentsLiteral`](https://github.com/VelocityPowered/Velocity/blob/648624d33317751dad5e820c66b67548eb92083a/proxy/src/main/java/com/velocitypowered/proxy/util/BrigadierUtils.java#L59) are major hacks that come to mind, among others used for hinting and manual parsing).

Some nice benefits are reduced memory usage.

Non-goals include adding, modifying, removing or deprecating any API.

**Comment by astei** [comment]
Done with #520
