### ISSUE TITLE
Server Icon Not Working

### ISSUE THREAD

**Issue by JasperJRoth** [PaperMC/Velocity#435]
When I connect to my server directly, not using velocity the server icon works fine, but when I connect through velocity the server icon appears as white. I have the server-icon.png placed in the lobby server folder as well as the velocity folder. The ping-passthrough is set to "all".

This is the server icon I am using. Ignore the silly face.
![server-icon](https://user-images.githubusercontent.com/38472993/109434230-4c068e80-79e2-11eb-9aa6-5fde4ea51b01.png)

This is what it looks like through velocity.
![image](https://user-images.githubusercontent.com/38472993/109434284-8cfea300-79e2-11eb-80cb-13b4578ec428.png)

I'm not sure what to do, I've tried changing a whole bunch of settings in the velocity.toml. Any help would be appreciated.

**Comment by jacoballen1** [comment]
It is quite possible that the client has cached the icon, try using another client to check.

**Comment by astei** [comment]
Probably not a Velocity issue. Closing.
