### ISSUE TITLE
Disconnect called after login on connection loss

### ISSUE THREAD

**Issue by roccodev** [PaperMC/Velocity#439]
I've encountered this weird issue today. Note that it's really rare and If I understood it correctly, it requires someone to lose connection and instantly connect back (network change?).

Here's the relevant section of the Velocity logs:
```
[18:46:53 INFO]: [connected player] Player (/[ip]:56200) has connected
[18:46:53 INFO]: [server connection] Player -> SERVER has connected

[19:06:29 INFO]: [connected player] Player (/[ip]:56556) has connected
[19:06:29 INFO]: [connected player] Player (/[ip]:56200) has disconnected: 
[19:06:29 INFO]: [server connection] Player -> SERVER has disconnected
[19:06:29 INFO]: [server connection] Player -> SERVER has connected
```
The effect is that DisconnectEvent gets fired *after* the new LoginEvent, so in my case it ends up removing the player that was initialized.
The player is still registered in `/glist all` though.

Perhaps setting `failover-on-unexpected-server-disconnect` to `false` could fix it?

Velocity 1.1.4
```json
{
    "bind": "0.0.0.0:25565",
    "showMaxPlayers": 500,
    "onlineMode": true,
    "preventClientProxyConnections": false,
    "playerInfoForwardingMode": "LEGACY",
    "announceForge": false,
    "onlineModeKickExistingPlayers": true,
    "pingPassthrough": "DISABLED",
    "advanced": {
      "compressionThreshold": 128,
      "compressionLevel": -1,
      "loginRatelimit": 3000,
      "connectionTimeout": 5000,
      "readTimeout": 30000,
      "proxyProtocol": false,
      "tcpFastOpen": true,
      "bungeePluginMessageChannel": true,
      "showPingRequests": false,
      "failoverOnUnexpectedServerDisconnect": true,
      "announceProxyCommands": true,
      "logCommandExecutions": false
    }
}
```
Server (Paper 1.8.8) logs are normal:
```
[18:46:53 INFO]: Player[/[ip]:56876] logged in with entity id 571 [...]

[19:06:29 INFO]: Player lost connection: Disconnected
[19:06:30 INFO]: Player left the game.
[19:06:30 INFO]: Player[/[ip]:60026] logged in with entity id 573 [...]
```

If this is intended behavior, feel free to close.

**Comment by astei** [comment]
Ordering the events such that DisconnectEvent is called before LoginEvent is quite tricky and due to #289 extremely unreliable. Therefore we have to keep the current behavior.

**Comment by roccodev** [comment]
No problem, do you think changing the failover option would affect anything?

**Comment by astei** [comment]
> No problem, do you think changing the failover option would affect anything?

It won’t change anything. But if you disable the onlineModeKickExistingPlayers setting, then the scenario cannot happen at all.
