### ISSUE TITLE
API to retrieve a player client brand's name

### ISSUE THREAD

**Issue by TheMode** [PaperMC/Velocity#457]
There seems to do not have any API (or even packet listener) allowing us to retrieve a player brand name. 
This is unfortunate since it would require forwarding a request to a Minecraft server. Is there any plan on this matter?

**Comment by OskarZyg** [comment]
There is [this fork](https://github.com/Cryptite/Velocity/commit/08f6d29993e882a3e0c4c4b9cd69c3452d5de622) with this type of functionality, you might want to take a look at that in the meantime.

**Comment by TheMode** [comment]
> There is [this fork](https://github.com/Cryptite/Velocity/commit/08f6d29993e882a3e0c4c4b9cd69c3452d5de622) with this type of functionality, you might want to take a look at that in the meantime.

I'd personally prefer to avoid relying on a fork. Though I'll have to if there isn't any plan to merge it.

Is there any reason why it hasn't been implemented? 
Could there perhaps be a kind of unsafe inbound packet listener API allowing users to fix by themselves such omission?

**Comment by OskarZyg** [comment]
Probably because it isn't a plugin message that can be registered, but I think there might be a way to use Velocity Internals to access packets, but don't quote me on that.

**Comment by TheMode** [comment]
Fixed by #523
