### ISSUE TITLE
Forced hosts not working when Capitalization is not matched

### ISSUE THREAD

**Issue by AzraAnimating** [PaperMC/Velocity#464]
It seems like, when using forced hosts, capitalization matters. 
So if I try to connect to "pvp.example.com" and the forced Host is "pvp.example.com" it'll work flawlessly, but if I connect to "PVP.example.com" the forced host is ignored entirely.

tested on Velocity-1.1.4

**Comment by astei** [comment]
Thanks for the report - should be fixed now.
