### ISSUE TITLE
Handful of players are being disconnected with an unexpected socket close

### ISSUE THREAD

**Issue by ChipWolf** [PaperMC/Velocity#510]
Hey, all of our players are heading to the same backend which is correctly configured for Bungee IP forwarding.
We're using legacy mode for player info forwarding.

Several of our players are seeing this error intermittently but everyone is able to connect eventually, with a retry or two:
```
[23:06:16 ERROR]: [connected player] Steve (/<IP>:37848): unable to connect to server charmander
com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
This is usually because the remote server does not have BungeeCord IP forwarding correctly enabled.
See https://docs.velocitypowered.com/en/latest/users/player-info-forwarding.html for instructions on how to configure player info forwarding correctly.
```

The receiving server throws this in the debug log:
```
[Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Steve lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
```

I don't see a clear way to troubleshoot this issue, any help would be massively appreciated!

**Comment by ChipWolf** [comment]
So, if we define the same server 10 times, and stack them in the `try` list, it reduces errors logging in. This is obviously a pretty crap hack, but the results are interesting.

Several connections get in on the first attempt, some get in on later attempts, some don't get in after 10 attempts and must attempt a reconnect.
There are no peformance/network/or any other resource bottlenecks I can see.

**Comment by astei** [comment]
This sounds like a server issue, not a Velocity issue. It appears you're running some sort of modded server so I'd look there.

**Comment by ChipWolf** [comment]
Hi @astei, as this issue became a problem for us again this year, following some extensive evaluation over the last several weeks we can say with almost total certainty the issue stems from Velocity.

We've eliminated all variables, and through process of elimination, packet tracing, and application profiling, we can see this issue only occurs when Velocity is introduced & in the vast majority of cases it occurs on the first handshake for new users joining, and subsequent handshakes are successful.

Can we re-open this issue to discuss our findings and figure out how to progress please?
_This issue is still the first result in Google if you search for that specific error message._
Thanks!

**Comment by mrgeneralq** [comment]
> Hi @astei, as this issue became a problem for us again this year, following some extensive evaluation over the last several weeks we can say with almost total certainty the issue stems from Velocity.
> 
> We've eliminated all variables, and through process of elimination, packet tracing, and application profiling, we can see this issue only occurs when Velocity is introduced & in the vast majority of cases it occurs on the first handshake for new users joining, and subsequent handshakes are successful.
> 
> Can we re-open this issue to discuss our findings and figure out how to progress please? _This issue is still the first result in Google if you search for that specific error message._ Thanks!

+1 same issue, happening for 1.16 clients

**Comment by electronicboy** [comment]
This issue is closed generally because the issue is coming from something other than what we have control over, and we have nothing here to be able to diagnose
All we can see is that your server is trying to send a packet which has not been registered, which would alude to some race condition somewhere; Given that we cannot diagnose this issue, there is no inherent advantage to just having this issue sit open on the tracker unless there's something actionable for us to work on

first step is generally going to be to work out what packet is being sent out of phase, then you'd need to dig deeper into that; but, generally, there's nothing actionable for us here

**Comment by IsCibocaz** [comment]
@ChipWolf Please try checking the JDK version you're using! I encountered the same issue when running Paper 1.20.6 with JDK 25 behind a Velocity proxy. After switching to JDK 21, the problem was resolved.

**Comment by ChipWolf** [comment]
> @ChipWolf Please try checking the JDK version you're using! I encountered the same issue when running Paper 1.20.6 with JDK 25 behind a Velocity proxy. After switching to JDK 21, the problem was resolved.

This was maybe 4-5 years ago, I don't suppose I've seen this particular issue recently
