### ISSUE TITLE
Hover on Velocity ?

### ISSUE THREAD

**Issue by Akira13345** [PaperMC/Velocity#528]
Hi, I saw that Velocity does not have a "ProxyPingEvent" like bungeecoord which allows you to hover.
It would be cool to add it.

Example  
![exemple1](https://user-images.githubusercontent.com/60575816/121854810-f0db7c00-ccf2-11eb-9ee7-c22cb43cf739.PNG)

**Comment by vSKAH** [comment]
Yes i have same problem. I can't set strings in players list

**Comment by astei** [comment]
[We literally have it, down to the name being the same and configured in an identical matter](https://jd.velocitypowered.com/1.1.0/com/velocitypowered/api/event/proxy/ProxyPingEvent.html).

@vSKAH Note that most data objects in Velocity (like `ServerPing`) are immutable and so must be explicitly built through a builder.

Closing this issue as "we already have this."
