### ISSUE TITLE
`ConnectionRequestBuilder.connect()` doesn't reset in flight connections if an exception is thrown

### ISSUE THREAD

**Issue by Technical27** [PaperMC/Velocity#535]
If an exception is thrown during `ConnectionRequestBuilder.connect()`, a connection may be in flight, but it doesn't get reset and leads to a state where the connection is in progress, but the connection has already failed.

`ConnectionRequestBuilder.connectWithIndicaiton()` has exception handling that runs [this](https://github.com/VelocityPowered/Velocity/blob/baaf91a00d2ab0fdf02be144f5ce8b734a20da75/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L664-L667), which properly resets the connection.

You can either use `connectWithIndication()` and get error messages printed to the player or use `connect()` but on the current server to "reset" the connection.

**Comment by astei** [comment]
I believe 59ca9a53 (targeting Velocity 3.0.0) already fixes this issue. Given that Velocity 3.0.0 is due for imminent release, I think the fix can wait a bit longer (Velocity 3.0.0 is scheduled for release when MInecraft 1.17.1 is released).

**Comment by astei** [comment]
I consider this issue fixed with the release of Velocity 3.0.0.
