### ISSUE TITLE
Maven repo error

### ISSUE THREAD

**Issue by kubo6472** [PaperMC/Velocity#538]
Hi, I know the mistake is probably on my side, but anyway, has anyone come across this issue?
![image](https://user-images.githubusercontent.com/26146502/125122577-ed6ec100-e0f5-11eb-8810-7349de21658a.png)
When I hover over it:
![image](https://user-images.githubusercontent.com/26146502/125122594-f19ade80-e0f5-11eb-879a-0fcc4810c601.png)

**Comment by astei** [comment]
This error is likely spirous and in any event isn't considered a bug in Velocity.
