### ISSUE TITLE
JoinKick functionality not working in 3.0

### ISSUE THREAD

**Issue by kubo6472** [PaperMC/Velocity#542]
Players are still getting errors: "You are already connected to this proxy!" from time to time

**Comment by astei** [comment]
This is not a bug in Velocity. The functionality you're looking for was integrated into Velocity long ago, set `kick-existing-players` to `true` in your `velocity.toml`. Closing as this is not a bug.

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/125453960-2c0fa4be-0494-4613-ab54-760571f1c7cd.png)
since it is set to true and I moved on from that plugin, since the dev said you integrated it to using this option. yet for some reason those issues keep happening, and they were not. that is why I am reporting it as a bug in velocity.

**Comment by kubo6472** [comment]
```
[09:52:37] [Netty epoll Worker #5/INFO]: [connected player] *** has disconnected: You are already connected to this proxy!
[09:52:41] [Netty epoll Worker #8/INFO]: [connected player] *** has disconnected: You are already connected to this proxy!
[10:05:32] [Netty epoll Worker #9/INFO]: [connected player] *** has disconnected: You are already connected to this proxy!
```

here with some timestamps from logs. so please, I don't have the right to reopen this issue.

**Comment by astei** [comment]
I cannot reproduce the issue by myself, and you have given me no way to reproduce the issue. Please provide a link to your `/velocity dump`.

**Comment by kubo6472** [comment]
https://dump.velocitypowered.com/oyayogupuk.json
sorry, I didn't know what was needed. is this sufficient?

**Comment by astei** [comment]
You are running in offline mode. As a general policy, we do not support offline mode, and the vanilla Minecraft server acts very similar to Velocity's behavior here. This can be leveraged by an attacker to generate a trivial denial-of-service by repeatedly logging in as every player in your network.

This issue remains closed as "works as intended" - if you don't like the behavior, it is simple to modify Velocity yourself to remove the requirement that the server has to be in online mode to enforce the setting.

**Comment by kubo6472** [comment]
All right, I understand. That is why I used a plugin for that. Except, now I can't, since it's deprecated. I'll see what I can do.
