### ISSUE TITLE
Add an event when player join new dimension?

### ISSUE THREAD

**Issue by plusls** [PaperMC/Velocity#545]
I don't know how to know is a player join a new dimension, I want an event to know  this.

**Comment by ghost** [comment]
You can use the plugin messaging channel. Also why do you need this anyway?

**Comment by plusls** [comment]
> You can use the plugin messaging channel. Also why do you need this anyway?

I want to teleport player to other server after they change dimension.

You mean is write another plugin in sub-server and send custom plugin message when dimension change?

**Comment by ghost** [comment]
> You mean is write another plugin in sub-server and send custom plugin message when dimension change?  

Yes.

**Comment by plusls** [comment]
> > You mean is write another plugin in sub-server and send custom plugin message when dimension change?
> 
> Yes.

Ok. I just think that can add a event when recv a MinecraftPacket and send a  MinecraftPacket.
