### ISSUE TITLE
Sending a resource pack offer instantly on LoginEvent flashes the prompt screen on the client

### ISSUE THREAD

**Issue by Jaren8r** [PaperMC/Velocity#546]
When I send a resource pack offer from my plugin directly on LoginEvent and the client is set to prompt on server resource packs, the prompt screen shows for a millisecond, not allowing the user to accept it. Delaying the prompt by a second works, but is not ideal.

**Comment by mikroskeem** [comment]
Nothing to do about it, unfortunately. Your best bet is to move resourcepack sending to a backend server and send it immediately when client calls/sends out first movement event/packet.

**Comment by astei** [comment]
Unfortunately no good way to do this, the screen will pop up too early at `LoginEvent` time. You're better off waiting until, say, 500 milliseconds after the player joins a server for the first time for similar (`ServerPostConnectEvent`, previous server should be null or not exist).

Closing this issue as we can't fix this in Velocity.
