### ISSUE TITLE
Minor breakages in event listener registration

### ISSUE THREAD

**Issue by A248** [PaperMC/Velocity#547]
With the rewrite of the EventManager implementation in Velocity 3, behavior has changed.

The `unregisterListener(Object, Object)` no longer allows unregistering annotated listeners, that is, listener objects which use annotated methods to declare handlers. For example:

```java
Object annotatedListener = new AnnotatedListener();
eventManager.register(PLUGIN_A, annotatedListener);
eventManager.unregisterListener(PLUGIN_A, annotatedListener);
```

In Velocity 1.x, the listener will be unregistered. In 3.x, the listener remains registered.

If this is an intended behavioral change, it would be worthwhile to mention it on the [migration docs](https://github.com/VelocityPowered/site/blob/master/docs/developers/porting-from-velocity-1.md).

**Comment by astei** [comment]
This sounds like a regression to me.
