### ISSUE TITLE
Add `isOnlineModeKickExistingPlayers` to ProxyConfig

### ISSUE THREAD

**Issue by plusls** [PaperMC/Velocity#550]
I found it in VelocityConfiguration, but it not in `ProxyConfig` in api, I can't to get this configure.

**Comment by astei** [comment]
Why? For the record, I am not a very big proponent of the current `ProxyConfig` API, it needs a rework and to not be a leaky abstraction, based on actual needs instead of theoretical ones.

**Comment by plusls** [comment]
thank you for your reply. After seeing your reply, I thought for a moment that this function is really not needed, and refactored my code.
