### ISSUE TITLE
[FR/BUG] "Proxy shutting down" not localizable

### ISSUE THREAD

**Issue by kubo6472** [PaperMC/Velocity#552]
The message "Proxy shutting down" can not be localized/customized.

**Comment by astei** [comment]
As mentioned multiple times, this is a non-issue since you can always specify your own reason for shutting down the proxy.

**Comment by kubo6472** [comment]
I searched proxy shutting down in the issues (open&closed) and haven't found anything. Is there any how-to on how to change that message then?

**Comment by astei** [comment]
Use `/shutdown <your message>`. This is documented on the wiki too.
