### ISSUE TITLE
Typo in the wiki

### ISSUE THREAD

**Issue by Pairman** [PaperMC/Velocity#553]
Is the "systen" a typo in this paragraph shown below? If so, hope  you can fix it.

https://velocitypowered.com/wiki/users/what-does-velocity-do-for-me/

![Screenshot_20210802-033756_Firefox~2.png](https://user-images.githubusercontent.com/18365163/127783310-00c83cf4-19c8-434b-93e2-7c5724c9b8ed.png)

**Comment by astei** [comment]
This is not the correct place to report problems with the website (that would be the [website repo](https://github.com/VelocityPowered/site)).
