### ISSUE TITLE
HAProxy - Velocity refusing connection

### ISSUE THREAD

**Issue by aegontargaryen-dev** [PaperMC/Velocity#561]
On spigot servers everything works perfectly, the connection is forwaded but on velocity it shows "Disconnected".

frontend bungee_frontend
    bind *:25565
    mode tcp
    option tcplog
    timeout client  1m   # miiiiigghht want to play with those, no clue
    default_backend bungee_backend

backend bungee_backend
    mode tcp
    option tcplog
    option log-health-checks
    log global
    balance roundrobin
    timeout connect 10s
    timeout server 1m   # again, if you notice random disconnects, play with those values
    server bungee1 <bungee 1 hostname>:<bungee 1 port> check
    server bungee2 <bungee 2 hostname>:<bungee 1 port> check
    
    Velocity proxy 1 runs on localhost:25566
    Velocity proxy 2 runs on localhost:25567
    
    Both has haproxy protocol support enabled.
    
    Haproxy runs on 25565.

**Comment by astei** [comment]
User configuration error. You did not enable the HAProxy PROXY protocol, [here's some instructions on that](https://www.haproxy.com/blog/using-haproxy-with-the-proxy-protocol-to-better-secure-your-database/).
