### ISSUE TITLE
Can't send Login custom payloads to client while using Velocity

### ISSUE THREAD

**Issue by ExcessiveAmountsOfZombies** [PaperMC/Velocity#570]
I've recently been messing around with sending packets from paper to modded clients and needed to send some data during the `LOGIN` phase to prepare for the `PLAY` phase. This would be the ClientboundCustomQueryPacket (mojmap) or PacketLoginInCustomPayload (spigot). It's the same packet that's used to add velocity support.

after poking around on wiki.vg and velocity the equivalent would be 
https://github.com/VelocityPowered/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/LoginPluginMessage.java

I look and see where it's being handled
https://github.com/VelocityPowered/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java#L86

and it seems anything that isn't the velocity info packet is just discarded or rather sent back to the server empty. 

I'm wondering is this an intentional thing? is it some limitation of going through a proxy that CustomQueryPackets can't be sent to the client? Normally i'd just spend a few days messing around with the code and see if I could get it to work, but in this instance I think I'd rather ask.

**Comment by astei** [comment]
The short answer is "we haven't implemented the functionality because nobody has asked for it yet."

**Comment by ExcessiveAmountsOfZombies** [comment]
Ok, all good, that's better than what I had alternatively thought

**Comment by ExcessiveAmountsOfZombies** [comment]
After spending yesterday and today seeing if I could get it to work myself, I'd be curious to know the longer answer, because this feels like something that is more difficult to implement than I was thinking. 

Admittedly I don't know much about networking but through some debugging it looks like by the time the server can get around to sending the LoginPluginMessage/ClientboundCustomQueryPacket the player on the proxy has already changed from `login` to `play` meaning they can't receive it anymore.

If it's not really too much to ask, is this something that's difficult to implement? i.e as someone who doesn't know much about networking would I just be wasting my time trying to do this myself (and subsequently making a PR that probably wouldn't even be that great if it worked.) If so, would you mind explaining the technical reasons? I'm always open to learning new things

**Comment by astei** [comment]
The main issue is that login plugin messaging requires the server (in this case, Velocity) to block server login until the necessary handshaking has been completed. This requires special support on the client and the proxy, while at the same time also being compatible with vanilla clients.

**Comment by ExcessiveAmountsOfZombies** [comment]
Hey, thanks for the explanation, from the debugging I was kinda trending towards that line of thinking but it's nice to have it confirmed.
