### ISSUE TITLE
Villager 

### ISSUE THREAD

**Issue by zombihunterbonn** [PaperMC/Velocity#579]
Village residents do not eat food to mate

**Comment by astei** [comment]
This is not something Velocity influences, closing this issue

**Comment by Xernium** [comment]
Velocity is a proxy server software and lacks any game mechanics that server software such as Paper has. You either posted this issue on the wrong project or you’ve worded this issue too poorly for anyone to understand it. Either way please pay more attention next time when opening an issue, thanks.
