### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by johncsuti** [PaperMC/Velocity#585]
I purpose creating a /help command so that it shows all available commands and there usage.

**Comment by OskarZyg** [comment]
This would override the backend server `/help` command and frankly, imo it's the responsibility of the plugin to offer documentation and command usage.

**Comment by johncsuti** [comment]
Don't gotta be so hostel with the thumbs down... It's a recommendation for a help command to show all _velocity commands_ and there usage. About it undermining the back-end servers, it would be a console only command that will only work from velocity's console. I thought that would have been obvious, but i guess i wasn't clear about that.

**Comment by MrIvanPlays** [comment]
what about /ghelp ?

**Comment by johncsuti** [comment]
> what about /ghelp ?

"/ghelp" would be a good command that would just show all default velocity commands. We wouldn't need to worry about allowing plugins to inject there own help pages. It would just be a way that i wouldn't need to lookup the commands on the wiki. Then it would also show command usage.

**Comment by astei** [comment]
I don't think we'll implement this. The commands are documented on [the wiki](https://velocitypowered.com/wiki/users/built-in-commands/) and all of them already include usage information where appropriate. I would understand if there were dozens of commands in Velocity, but there's 8 if you count `/velocity` and its subcommands as individual commands.
