### ISSUE TITLE
Probably nothing but I was told to post it here

### ISSUE THREAD

**Issue by Strahilchu** [PaperMC/Velocity#589]
![DeepCodeAI](https://user-images.githubusercontent.com/69178324/139911989-dcf88a6e-8f1e-4e07-aca9-97e84481933a.JPG)

**Comment by astei** [comment]
Velocity is not configured by default to accept logs from other servers over a TCP or UDP socket, nor is it used in practice in this configuration. ~~While I will update log4j to the latest version,~~ I am closing this issue as superfluous.

**Comment by astei** [comment]
After examining the dependency tree I can conclude that Velocity was never vulnerable in the first place and we already updated to the latest log4j version already. So your automated scanning tool is completely b0rked.

**Comment by Strahilchu** [comment]
Thanks for looking into it! It's "DeepCode AI" I tried a few things to see what it finds. Glad it's nothing!
