### ISSUE TITLE
[Bug] "NBSP" characters in the French messages 

### ISSUE THREAD

**Issue by SB2DD** [PaperMC/Velocity#595]
When having velocity in french, some messages with ":" have nbsp characters before

![Capture d’écran, le 2021-11-13 à 21 03 22](https://user-images.githubusercontent.com/45701824/141664624-a6bba488-d040-4110-bb3f-9f1351248d6d.png)

Intellij is able to see them. I will try to work on a quick pr to fix this.
![Capture d’écran, le 2021-11-13 à 21 04 28](https://user-images.githubusercontent.com/45701824/141664640-5ac54d46-2ab0-49c8-bf4d-26d90d743dea.png)

**Comment by astei** [comment]
Localization issues need to be fixed on Crowdin: https://crowdin.com/project/velocity

**Comment by SB2DD** [comment]
Right, thanks !

**Comment by SB2DD** [comment]
Changes have been submitted.

**Comment by toinouH** [comment]
Those are NonBreakingSpace...
The debate between keeping a full space or removing the space will come back :/

**Comment by Proximyst** [comment]
> Those are NonBreakingSpace...
> The debate between keeping a full space or removing the space will come back :/

The debate should probably be decided upon on the Discord, and for now, remove the NBSP. Minecraft does not properly render NBSPs for some reason, so that’s just what needs to be fixed.

The ”most correct” fix here from my POV would be just removing it and having no space as a NBSP would be rendered like there is no space at all.

**Comment by SB2DD** [comment]
> Those are NonBreakingSpace... The debate between keeping a full space or removing the space will come back :/

In french you need a space before colons( : ) and that's exactly what I changed on Crowdin. I guess the original person doing the translation had typing bugs or something, as some newer translations with colons did not have the original issue.

**Comment by toinouH** [comment]
@Mrredstone5230 Before crowdin we had a big debate about using NonBreakingSpace in the PR so I ended using the Windows ShortCut to use them. I don't know what happened after to be honest.
