### ISSUE TITLE
TabCompleteEvent for commands.

### ISSUE THREAD

**Issue by mdxd44** [PaperMC/Velocity#596]
The current event gives access only to the tab request without a slash.

**Comment by electronicboy** [comment]
if you mean, "the event should fire for /a", then the modern client doesn't send a request to the server for those, thus there is nothing for the server, well, proxy, to try to intercept there to fire an event and modify it

**Comment by Xernium** [comment]
That is absolutely intentional. If you want to use completions with commands look into Brigadier or the velocity command system
