### ISSUE TITLE
If forced-hosts is missing, don't load defaults.

### ISSUE THREAD

**Issue by cubuzz** [PaperMC/Velocity#597]
Simple QoL improvement: If the [forced-hosts] thingy is missing, don't load any. This would improve config readability significantly (and solve another bug I am experiencing due to another library).

Expected behaviour: Forced-Hosts is missing so no forced hosts are loaded.
Actual behaviour: Defaults are loaded.

**Comment by astei** [comment]
You can leave the section empty. This isn’t difficult to do (all you have to do is delete the contents except for the [forced-hosts] header) and Velocity won’t load any defaults.

Closing because this is a user configuration issue.

**Comment by iversond** [comment]
This was confusing behavior and took a while to figure out until I found this closed issue. If the `[forced-hosts]` header is missing, the defaults shouldn't be loaded since we are not defining any.
