### ISSUE TITLE
Question of different default server setting

### ISSUE THREAD

**Issue by WDRshadow** [PaperMC/Velocity#600]
It is very inconvenient for players as they are forced to enter one specific server every time they login. How to let them enter the privious server by default?
Currently, we can set and have to set at least one defalut server which force players try to connect when they login. But I want to let them try to connect the previous server last time they exited. Or just try to connect different servers depends on their client version or host they entre.

**Comment by Xernium** [comment]
I understand that this behavior is frustrating. It’s possible for plugins to change this behavior which is why this isn’t provided in Velocity itself. That and Velocity doesn’t store player information of any kind (well except for what’s in the logs).

**Comment by WDRshadow** [comment]
Cheers! I found a plugin in the community. Thats very helpful for me.

**Comment by GenMannnnnn** [comment]
> Cheers! I found a plugin in the community. Thats very helpful for me.

ello, may I ask the plugin's name ? it will helpful for me. thx !!
