### ISSUE TITLE
unicode characters are not displayed correctly in logs

### ISSUE THREAD

**Issue by weihao** [PaperMC/Velocity#603]
```
smp_1             | [06:45:40 INFO]: <.HuangFuSL> ������������������������
smp_1             | [06:45:49 INFO]: <.NewBeeplus> ������������������������
smp_1             | [06:45:54 INFO]: <.NewBeeplus> ���������������
smp_1             | [06:45:54 INFO]: <.HuangFuSL> ���
```

They are displayed correctly in game but not in consoles.

**Comment by astei** [comment]
More likely your console/server is configured with the wrong character set and instead of Chinese characters you get mojibake. In any case, Velocity treats all text as UTF-8 anyway.

Closing as this does not appear to be a bug in Velocity but rather a user configuration issue.
