### ISSUE TITLE
Capital letters in plugin id

### ISSUE THREAD

**Issue by markusmarkusz** [PaperMC/Velocity#606]
As is well known, the following regulations apply to plugin ids:
- only lowercase letters
- allowed special chars: underscore or dashes
- numbers
- max. 63 chars

This is checked by the following regex:
https://github.com/PaperMC/Velocity/blob/b14e7e651eab8111da58bbc76b103247d1541fcd/api/src/ap/java/com/velocitypowered/api/plugin/ap/SerializedPluginDescription.java#L17

Judging by the regex, the use of capital letters was at least an topic in the past. So is this just a holdover from removal or a badly implemented feature?
Depending on this, you could otherwise adjust the regex at some point.

**Comment by electronicboy** [comment]
i fail to understand this issue?
The regex explicitly requires that you start with an alpha character, and then ensures that you only have the correct allowable characters, up to 63 characters

**Comment by markusmarkusz** [comment]
@electronicboy 
> i fail to understand this issue? The regex explicitly requires that you start with an alpha character, and then ensures that you only have the correct allowable characters, up to 63 characters

The regex checks twice whether the letters are lowercase.
`[a-z][a-z...` -> Either one of them is too much or someone tried to allow capital letters and accidentally didn't get it right. I just wanted to be clarified whether that was intentional or unintentional.

**Comment by electronicboy** [comment]
The first [a-z] ensures that an id can start with only a-z

**Comment by markusmarkusz** [comment]
Oops. Didn't realize that. Sorry!
