### ISSUE TITLE
[3.1.1] When a legacy client pings the server, the connection object is logged and not the IP

### ISSUE THREAD

**Issue by TechnicallyCoded** [PaperMC/Velocity#608]
EDIT: I just noticed #604 already exists which would fix it =P

**Server version**
Velocity 3.1.1

**Description**
When a player using a legacy version of the game pings the server, the object of their connection seems to be logged to the console instead of the their IP. Definitely not an urgent issue but looks weird in the logs ^^. I assume it's probs a one-liner fix so if someone wants something fun to work on here you go :)

**Bugged log**
`[19:16:26 INFO]: com.velocitypowered.proxy.connection.client.HandshakeSessionHandler$LegacyInboundConnection@5709e05d is pinging the server with version Legacy`

**Expected result**
Something that looks like this
`[19:24:40 INFO]: [initial connection] /**.***.**.**:***** is pinging the server with version 1.**`

**Additional Info**
This is probs a server list service pinging my proxy rather than an actual player. No idea if that could affect something so I may as well mention it.

**Screenshot**
![image](https://user-images.githubusercontent.com/29813490/145629672-0bc8b54e-ced1-4e0c-875e-68e2f3f0d089.png)

**Comment by astei** [comment]
Pulled #604 which fixes this issue
