### ISSUE TITLE
1.17.1+ Required Resource Pack for Velocity

### ISSUE THREAD

**Issue by myavuzokumus** [PaperMC/Velocity#610]
Do you have a chance to add this feature, which is included in Minecraft vanilla servers, to the Velocity Proxy?

The mandatory Resource pack sending feature that came in 1.17 to players connected to Proxy with Velocity would be nice. I think this could be included in Velocity. No additional plugins needed.

**Comment by NoahvdAa** [comment]
This can already be done with a plugin such as [VelocityResourcePacks](https://forums.velocitypowered.com/t/velocityresourcepacks-manage-resourcepacks-for-servers-and-whole-proxy/515) or [ForcePacks](https://forums.velocitypowered.com/t/forcepacks-kick-players-that-decline-the-resourcepack-download-prompt/864), I doubt Velocity is going to have built-in support for this relatively niche feature.

**Comment by tjalp** [comment]
> This can already be done with a plugin such as [VelocityResourcePacks](https://forums.velocitypowered.com/t/velocityresourcepacks-manage-resourcepacks-for-servers-and-whole-proxy/515) or [ForcePacks](https://forums.velocitypowered.com/t/forcepacks-kick-players-that-decline-the-resourcepack-download-prompt/864), I doubt Velocity is going to have built-in support for this relatively niche feature.

Actually it is already possible via `Player#sendResourcePackOffer(ResourcePackInfo)`.
You can make the resource pack required by using `ResourcePackInfo.Builder#setShouldForce(boolean)`

**Comment by NoahvdAa** [comment]
Was talking about adding it as a config option, which is probably what the OP wants (since they don't mention API anywhere).

**Comment by myavuzokumus** [comment]
> Was talking about adding it as a config option, which is probably what the OP wants (since they don't mention API anywhere).

Yes, that's true.

But you misunderstood my request. In 1.17, there is a feature about the use of mandatory resource pack and it needs to be integrated. It's not the old one. And VelocityResourcePack does not have this feature.

When I told his developer this, he dismissed the situation. That's why I wanted to open a issue about how it can be integrated into Velocity.

By the way, to better understand the feature I want, I can give you the following setting in the "server.properties" settings file.

```
require-resource-pack=true
resource-pack-prompt=
```

**Comment by electronicboy** [comment]
We didn't misunderstand your request, the API already supports this? I don't see why there is such a need for velocity to expose this in the config when it would be trivial to have a plugin elsewhere which just uses this API; No need to cram the core with features which are used by few but have to be maintained for everybody, especially when API exists for it

**Comment by astei** [comment]
Velocity already supports this in the API. To me, this sounds like you are not happy with a specific plugin. In that case you are welcome to write your own plugin with some basic Java programming skills.

Closing this issue as it’s not a Velocity issue.

**Comment by myavuzokumus** [comment]
> Velocity already supports this in the API. To me, this sounds like you are not happy with a specific plugin. In that case you are welcome to write your own plugin with some basic Java programming skills.
> 
> Closing this issue as it’s not a Velocity issue.

Sorry, I thought this was a nice feature for Velocity.

Yes you are right, I will add it myself.
