### ISSUE TITLE
Issue on start

### ISSUE THREAD

**Issue by ZethiaZ** [PaperMC/Velocity#612]
Whenever I start my server after updating to build 105 from build 98 the following error occurs. Im limited on time so I havent checked if the server still works otherwise - but I bet it would as the console log saved when you stop the server does not show the errors and the normal startup messages do print after the error stops spamming console.

[a.txt](https://github.com/PaperMC/Velocity/files/7730211/a.txt)

**Comment by ZethiaZ** [comment]
- After further testing I can confirm version 103 does not have this issue. So the issue must have been introduced in version 104 or version 105.

**Comment by jacoballen1** [comment]
Please upload the contents of the file to a paste site. We will not download random files.

**Comment by vinceh121** [comment]
This issue is fixed in d7195060f54c7c8980a421a4c91e33a69b0762b0
