### ISSUE TITLE
Broken Development Download URL

### ISSUE THREAD

**Issue by ssamjh** [PaperMC/Velocity#617]
When trying to download the latest dev build on this URL: https://versions.velocitypowered.com/download/3.0.x-SNAPSHOT.jar

Error 1101
Worker threw exception

Screenshot: https://m.sjh.at/chrome_2021-12-20_17-53-01.png

**Comment by Rishon** [comment]
> When trying to download the latest dev build on this URL: https://versions.velocitypowered.com/download/3.0.x-SNAPSHOT.jar
> 
> Error 1101 Worker threw exception
> 
> Screenshot: https://m.sjh.at/chrome_2021-12-20_17-53-01.png

Velocity is now a part of PaperMC, you can find Velocity latest stable & dev builds at https://papermc.io/downloads#Velocity

**Comment by Xernium** [comment]
Velocity and Velocity development can now be obtained using the Paper downloads api
Documentation for that can be found here https://papermc.io/api/docs/swagger-ui/index.html?configUrl=/api/openapi/swagger-config
If you have additional questions feel free to join the PaperMC Discord and ask.
