### ISSUE TITLE
Forward "Client Settings" when switching the server

### ISSUE THREAD

**Issue by Ling556** [PaperMC/Velocity#619]

**Comment by Camotoy** [comment]
A modern client re-sends its client settings when the join game packet is sent; the join game packet is forwarded upon switching the server in Velocity. If an older client has different functionality, you should specify. If a modded client has different behavior, then this doesn't sound like a Velocity issue.

**Comment by astei** [comment]
Velocity already gets the client to do this by resending the join game packet. File a new issue if there is an actual bug and _explain_ why.
