### ISSUE TITLE
ServerCommand permission case

### ISSUE THREAD

**Issue by iSilviu-debug** [PaperMC/Velocity#622]
https://github.com/PaperMC/Velocity/blob/058014aa75f7ac1a2caf5b9aa6a495d512f9e2d7/proxy/src/main/java/com/velocitypowered/proxy/command/builtin/ServerCommand.java#L160

Many servers tend not to set the _"velocity.command.server"_ permission to false, in fact they keep it as the default without knowing it. In fact, a player can use it to a disadvantage. I know perfectly well that it is possible to disable the permission and keep it on false, but can it give problems for those who don't know?
For example **GlistCommand** has permission which is equivalent to `== Tristate.TRUE`

_I haven't read anything about this in the wiki, so I hope I was helpful! ^^"_

**Comment by astei** [comment]
This isn’t a bug and it is fully documented. If anything, forcing users to be explicitly granted /server makes the default configuration far less intuitive.
