### ISSUE TITLE
Add Event for Resource Pack Send Packets

### ISSUE THREAD

**Issue by CoreyShupe** [PaperMC/Velocity#624]
This issue is representing the work for adding in an event for the [Resource Pack Send](https://wiki.vg/Protocol#Resource_Pack_Send) packet.

This allows the owner of a proxy to transform the resource pack request coming from the backend servers at the proxy level rather than sending a resource pack request at the proxy level. This can help synchronize server resource pack sends without needing to push the logic into the proxy level.

**Comment by astei** [comment]
This is long-implemented, so closing.
