### ISSUE TITLE
add multi-velocity support

### ISSUE THREAD

**Issue by ImFound** [PaperMC/Velocity#627]
like RedisBungee

**Comment by CoreyShupe** [comment]
https://github.com/GiansCode/Chocolate
and
https://github.com/schematico/trevor

This isn't something which should be implemented at the velocity level anyhow, it should be done by a plugin or via user implementation

**Comment by Xernium** [comment]
Yes. This is something that should be solved by plugins, any implementation on Velocity directly would be too broad and it would be impossible to cater to the specifications required by all users.
