### ISSUE TITLE
Unexpected JVM crash

### ISSUE THREAD

**Issue by pierreogagnon** [PaperMC/Velocity#638]
Hello!

It's the second time this week velocity crash unexpectedly.

Java: 11.0.14
Velocity: 3.1.1
OS: Debian 11

[hs_err_pid39768.log](https://paste.gg/p/Pencil/3ea4158d3de844f0af1ae31a45a855eb)

**Comment by astei** [comment]
SIGSEGV crash, you should perform a memory test. Closing as this is exceedingly unlikely to be a Velocity issue.
