### ISSUE TITLE
 The connection to the remote server was unexpectedly closed

### ISSUE THREAD

**Issue by ghost** [PaperMC/Velocity#639]
whenever i try to connect to the lobby in my velocity proxy, this happens
![image](https://user-images.githubusercontent.com/41709262/152770354-7e5d9cdc-fdf0-4fc4-a09b-8b0ccfa11784.png)
(im using the playit.gg tunnel since i cant port forward, if thats got to do anything with the error)

**Comment by ghost** [comment]
nevermind fixed it

**Comment by Clyde6790pGIT** [comment]
Might be super late but how do you run this with a playit tunnel?
