### ISSUE TITLE
Player info forwarding for forge server

### ISSUE THREAD

**Issue by Wolfyxon** [PaperMC/Velocity#640]
How do I use player info forwarding when the backend server is in Forge? Skin's doesn't work.
I tried using many plugins but none of them works too.
When reading docs I saw that I have to enable something in paper.yml but I can't use other engine than regular Forge because it's a modpack.
Modpack: Project Ozone 3 new way forward
Version: 1.12.2 Forge
Proxy version: 3.1.1

Please help

**Comment by KoxSosen** [comment]
Please use the Discord server or the Forums for support. Generally, you'll get faster replies there, and more people see your issue. 

Modern forge ( 1.13+ ) isn't supported, and people replied to your issue on Discord. ^_^

**Comment by jacoballen1** [comment]
Requesting this issue be closed as the user has found the solution, SpongeForge, through discord.

**Comment by Wolfyxon** [comment]
> Requesting this issue be closed as the user has found the solution, SpongeForge, through discord.
The solution doesn't work
spongeforge doesn't work on modpack servers
![image](https://user-images.githubusercontent.com/58263600/152862459-0617b272-40e5-4b96-a980-94f32ca1323d.png)

**Comment by Wolfyxon** [comment]
Reopen issue pls

**Comment by astei** [comment]
Unfortunately we do not provide standalone forwarding support for Forge and don’t intend to. Sorry about that.

**Comment by Wolfyxon** [comment]
> Unfortunately we do not provide standalone forwarding support for Forge and don’t intend to. Sorry about that.

Oh ok then....

Is there a plugin that can modify the data that is sent to player via proxy? Not request skin change on the backend server like SkinRestorer.

**Comment by jacoballen1** [comment]
You will need to talk to the folks over at the Sponge discord for help with getting sponge to work on your server. SpongeForge does, in fact, work on modpacks.

**Comment by Wolfyxon** [comment]
> You will need to talk to the folks over at the Sponge discord for help with getting sponge to work on your server. SpongeForge does, in fact, work on modpacks.

Alright
