### ISSUE TITLE
Disconnect when try to connect

### ISSUE THREAD

**Issue by spatrik2001** [PaperMC/Velocity#642]
Hi,
I have a problem when try to connect my lobby server through velocity. In velocity, i got this error:
https://pastebin.com/j8ZN0yVw and in the lobby server i got this: `[16:01:46] [Server thread/INFO]: MrEveriX lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 3`

I'm using `Velocity 3.0.0` and `ViaVersion 4.0.2-SNAPSHOT`.

I look forward to hearing from you soon.

**Comment by spatrik2001** [comment]
bump

**Comment by astei** [comment]
This isn't the place to ask this question, could be a ViaVersion issue for all we know, so ask them first next time.
