### ISSUE TITLE
Allow empty response if correct hostname is not used.

### ISSUE THREAD

**Issue by angwdev** [PaperMC/Velocity#646]
Simple workaround if I don't want to allow access from other place than the hostname / hostnames.
Example if to prevent access using direct IP or hostnames not listed. This may increase security and prevent bot attacks without going much farder.
```
[forced-hosts]
	#"minigames.example.com" = ["minigames"]
	# Configure your forced hosts here.
	#"lobby.example.com" = ["lobby"]
	#"factions.example.com" = ["factions"]
        # No response if none of the listed hosts is used.
        #"" = []
```

**Comment by astei** [comment]
It's not clear to me what value there is for this, and you could just use a plugin to enforce this anyway.

**Comment by angwdev** [comment]
It's simple, like nginx does
```
server {
    listen       80;
    server_name  example.org;
server {
    listen       80;
    server_name  _;
```
The ability to listen to "any other host" so players can only join from the hostname I want.

(No plugin does that yet)':

**Comment by astei** [comment]
Well, no, you can already do this...

```
[servers]
# ...your servers...

# if we didn't come through a forced host, don't connect to any server
try = []

[forced-hosts]
"minigames.example.com" = ["minigames"]
"lobby.example.com" = ["lobby"]
```

and it works just fine. No need to implement anything new.

**Comment by angwdev** [comment]
Doesn't look implemented yet.
`There are no available servers to connect you to. Try again later or contact an admin.`

**Comment by electronicboy** [comment]
I mean, that's the expected behavior here, there is no available servers for you to connect to
am not sure what the other appropriate response would be here given that this is as the proxy intended, sounds that you're expecting some odd behavior which the usecase of 1 really doesn't merit

**Comment by angwdev** [comment]
My bad I forgot one detail.
