### ISSUE TITLE
A event exclusively for disconnecting from a backend server

### ISSUE THREAD

**Issue by AoElite** [PaperMC/Velocity#649]
There doesn't appear to be a event for whenever a player disconnects exclusively from the proxy after successfully connecting to a backend server. There is the `DisconnectEvent` however you can trigger different login statuses after logging out for different reasons. If you decide to listen to all of them then you can end up calling code for no reason even if they didn't successfully connect.

The only current solution right now is to create a map and store if they successfully connected via the `ServerPostConnectEvent` (which is in beta) and then check on the DisconnectEvent. I think there could be a dedicated event for this or some way to reliable to check this without doing what I mentioned. If there is a reliable way to do this without doing what I mentioned please let me know!

**Comment by derklaro** [comment]
IIRC the disconnect event has a status of the login, one of them should be `successful_login`, maybe thats what you need?

**Comment by Xernium** [comment]
As @derklaro said, the event has the login status; plus you can still get the current server of the player at this point.

**Comment by AoElite** [comment]
@Xernium @derklaro The successful login status can still occur without successfully connecting to the server.

**Comment by Xernium** [comment]
As I said, you can still get the current server if any.

**Comment by AoElite** [comment]
You can have occurrences of the ServerPostConnectEvent not firing and DisconnectEvent login status being successful.

**Comment by AoElite** [comment]
> As I said, you can still get the current server if any.

Won't this always show as empty since it's being called on disconnect?
