### ISSUE TITLE
About haproxy-protocol

### ISSUE THREAD

**Issue by XenWayne** [PaperMC/Velocity#652]
After enabling "haproxy-protocol = true"
the proxy tunnel is working，but those connections which connect directly through IP(without proxy) doesn't work.
It should allow both ways(direct/proxy) to connent the velocity server.
like what the plugin [bc-haproxy-detector](https://github.com/andylizi/bc-haproxy-detector/) has done at bungeecord.

**Comment by astei** [comment]
> the proxy tunnel is working，but those connections which connect directly through IP(without proxy) doesn't work.

That's just asking for a security issue. No, you're asking for insanity.
