### ISSUE TITLE
when player moved to other server, head skin was disappeard.

### ISSUE THREAD

**Issue by Ecilpse** [PaperMC/Velocity#670]
i set properly (modern, velocity-support in paper.yml, bungeecord: false in spigot.yml

>> paper.yml, spigot.yml, velocity.toml
[Desktop.zip](https://github.com/PaperMC/Velocity/files/8374210/Desktop.zip)
)
i asked to paper discord, i can't get solutions.
how can i set??

**Comment by TheMuo** [comment]
My situation is similar to yours, but my body parts are abnormal.

**Comment by 4drian3d** [comment]
Can you give clearer instructions on how to reproduce the bug? Personally I have not been able to reproduce it

**Comment by 4drian3d** [comment]
I have not been able to reproduce the bug nor has this issue provided any way to replicate it in almost 2 years

**Comment by Ecilpse** [comment]
> I have not been able to reproduce the bug nor has this issue provided any way to replicate it in almost 2 years

i think this bugs happend only forge players.
