### ISSUE TITLE
Unable to connect you to [server]. Please try again later.

### ISSUE THREAD

**Issue by ghost** [PaperMC/Velocity#686]
Hello Velocity Community,
There is a issue on the latest velocity version where **some** players can't connect through our servers and keep getting the Unable to connect message

https://user-images.githubusercontent.com/56703279/162626789-27249aa3-283f-40c2-8be7-6e8eabfd9ae5.mp4

Console Log 1 
[18:34:46 INFO]: [server connection] NebOrzo -> pikachu has disconnected
[18:34:46 ERROR]: [connected player] NebOrzo (/109.151.127.82:52472): unable to connect to server pikachu
com.velocitypowered.proxy.util.except.QuietRuntimeException: The connection to the remote server was unexpectedly closed.
This is usually because the remote server does not have BungeeCord IP forwarding correctly enabled.
See https://docs.velocitypowered.com/en/latest/users/player-info-forwarding.html for instructions on how to configure player info forwarding correctly.
[18:34:46 INFO]: [connected player] NebOrzo (/109.151.127.82:52472) has disconnected: Unable to connect to pikachu. Try again later.

Console Log 2
https://images-ext-2.discordapp.net/external/-werG4rIL4KOXHmoR2BIccKuEWbI71lDA23RVAntnSw/https/i.imgur.com/vnwRxY7.png?width=1312&height=676

**Comment by kyngs** [comment]
What appears on the console of the target server? (pikachu9 in this case)

**Comment by LegendaryMouse** [comment]
https://cdn.discordapp.com/attachments/1157331238479220896/1191379319369519154/image.png?ex=65a53974&is=6592c474&hm=190fdceebfa593c760ca31d5575405ff25b0236de30a749850c2f1bd93eef2e9&

**Comment by LegendaryMouse** [comment]
the problem is still here

**Comment by LegendaryMouse** [comment]
![image](https://github.com/PaperMC/Velocity/assets/134811008/3e129ef5-5b65-4d7e-bcaa-9fedc34a4626)
