### ISSUE TITLE
[Bug] Velocity not support server with snapshot ver. when ViaVersion-Dev is installed my Velocity server

### ISSUE THREAD

**Issue by 8MiYile** [PaperMC/Velocity#687]
i try use client 22w11a connect my server 22w11a 
the connect have through velocity
velocity have installed viaversion-dev plugin
but client give an error
Disconnect: incompactible client , you should use client 22w11a
but my client is 22w11a
*PS: 22w11a is minecraft version

**Comment by Xernium** [comment]
Velocity doesn’t support snapshots in non-test versions and I haven’t started on the 1.19 update process yet.
