### ISSUE TITLE
PreLoginEvent.PreLoginComponentResult.denied() doesn't kick players/show them Component text

### ISSUE THREAD

**Issue by SenPr** [PaperMC/Velocity#689]
e.setResult(PreLoginEvent.PreLoginComponentResult.denied(create(configuration.getNode(webMsg).getString())));

This was my line of code trying to cancel a player's login. Not entirely sure that this is a bug, but when I tested it, the client shows "Connecting to server" until I time out or cancel the connection. Velocity shows I disconnected whenever I disconnect, not when the event is triggered

I'm assuming its a bug since the component text is there to fill, but doesnt even get shown.

Velocity Version: Velocity 3.1.2-SNAPSHOT (git-44dc2e7c-b131)

**Comment by kyngs** [comment]
I cannot replicate this, can you make sure that there isn't a bug on your side? (Especially the create() method)
Maybe add some print statement after the PreLoginEvent#setResult statement to check that it actually returned?

**Comment by SenPr** [comment]
create() was just a method to deserialize component
I'll test again when I can

**Comment by Hikk0o** [comment]
I have the same problem. Is there a solution?

**Comment by SenPr** [comment]
I'll assume this is a logic error since I haven't encountered this bug since.

**Comment by KonusIntelliJ** [comment]
I solved this problem in the method before it in the annotation, change to PostOrder.LAST and everything will work.
