### ISSUE TITLE
Can't use libdeflate

### ISSUE THREAD

**Issue by andreasdc** [PaperMC/Velocity#695]
I can't use libdeflate on linux, why?
Using Java 11 compression from Velocity.
Using Java cipher from Velocity.

**Comment by Xernium** [comment]
Hi, you provided absolutely zero context about your OS or proxy environment so we can’t help. Please open a new issue with a `/velocity dump` link and as much information about your OS, installation and environment as possible. Please also attach a proxy log.

**Comment by andreasdc** [comment]
> Hi, you provided absolutely zero context about your OS or proxy environment so we can’t help. Please open a new issue with a `/velocity dump` link and as much information about your OS, installation and environment as possible. Please also attach a proxy log.

I'm using velocity-natives on spigot.

**Comment by Xernium** [comment]
The Velocity natives were made to work with Velocity in mind so we don’t expect them to work elsewhere without a fair amount of modification. You’re free to use the Velocity natives as the proxy license permits, but we won’t offer support for such uses on the Velocity project directly. In any case you’re free to ask development-related questions about this on the Paper Discord, but the Velocity issue section is the wrong location for this.

**Comment by andreasdc** [comment]
> The Velocity natives were made to work with Velocity in mind so we don’t expect them to work elsewhere without a fair amount of modification. You’re free to use the Velocity natives as the proxy license permits, but we won’t offer support for such uses on the Velocity project directly. In any case you’re free to ask development-related questions about this on the Paper Discord, but the Velocity issue section is the wrong location for this.

Do I have to install something for libdeflate to work or how does natives loading work?

**Comment by Xernium** [comment]
Again, not the right place to ask. As long as it works on Velocity this isn’t an issue that you’ll get help with here.
