### ISSUE TITLE
Support compression natives for s390x

### ISSUE THREAD

**Issue by jamespglines** [PaperMC/Velocity#699]
Hello. Is it possible the velocity natives compression support for s390x IBM Z?

Thanks!

**Comment by astei** [comment]
Yes, it’s possible, but we’re not going to support it. None of us have access to IBM z hardware and libdeflate isn’t optimized for IBM z. In addition the number of servers running on IBM z hardware is probably lower than even ARM servers.

It’s not hard to add support if you really need it.
