### ISSUE TITLE
Make the Bungeeguard forwarding compatible with forge

### ISSUE THREAD

**Issue by StG3rm4in** [PaperMC/Velocity#701]
At this time the Bungeeguard forwarding is not compatible with forge, the mods data are not forwarded, I tested it myself on my spongeforge server with the bungeeguard fork of nickuc https://github.com/nickuc/BungeeGuardPlus and it says that I don't have forge on my client. I also tested it on waterfall with the plugin on the proxy and the server and I don't have any problem.

**Comment by astei** [comment]
This isn't something we want to do. This sounds like a bug in the fork of BungeeGuard you're using.
