### ISSUE TITLE
Can't sendPluginMessage while using event with no player connected

### ISSUE THREAD

**Issue by ghost** [PaperMC/Velocity#702]
@Subscribe
   public void test(PlayerChooseInitialServerEvent event) { // send failed
      ByteArrayDataOutput out = ByteStreams.newDataOutput();
      out.writeUTF(...);
      server.getServer("...").get().sendPluginMessage(identifier, out.toByteArray());
   }
If I change it to PlayerChatEvent or ServerPostConnectEvent(which is player based and player is connected), sendPluginMessage works as expected. But many others event like ProxyInitializeEvent does't work

**Comment by electronicboy** [comment]
plugin messaging requires using a players connection to send a message, it's literally 0 surprise and generally unavoidable that it doesn't work in the case that there is no player connection to shove such data down
