### ISSUE TITLE
Add avatar to the proxy server

### ISSUE THREAD

**Issue by ZocP** [PaperMC/Velocity#704]
I haven't seen any instructions that allow me to add an avatar to the velocity proxy server. I've tried adding server-icon.png to the same directory as velocity-*.jar but this doesn't seem to work. It will be great if there is an option for using an avatar!

**Comment by NoahvdAa** [comment]
Make sure the icon is 64x64 pixels, Velocity should pick it up if its the correct size and named server-icon.png

**Comment by ZocP** [comment]
Yes, I've named it server-icon.png and restarted the proxy, but velocity didn't seem to pick it up.

**Comment by ZocP** [comment]
Is it possible that it's a file owner problem that causes it? 
I've confirmed that the size is 64x64 pixels
![image](https://user-images.githubusercontent.com/87646631/167316009-34811ba9-d341-4e4e-b939-31cabb48ef02.png)

**Comment by ZocP** [comment]
I've changed the file owner and it seems to work now! Thanks a lot!
