### ISSUE TITLE
Add separate configuration for player logs in and kicked server

### ISSUE THREAD

**Issue by Pantera07** [PaperMC/Velocity#705]
Add separate configuration for player logs in and kicked server

↓ example
```
[servers]
	# Configure your servers here. Each key represents the server's name, and the value
	# represents the IP address of the server to connect to.
	limbo = "127.0.0.1:30066"
	lobby = "127.0.0.1:30067"
	survival = "127.0.0.1:30068"
	# In what order we should try servers when a player logs in or is kicked from a server.
	log-in = ["lobby"]
	kick = ["limbo"]
```

**Comment by Xernium** [comment]
Sorry, we aren’t going to consider this. This wouldn’t work with forced hosts and also it isn’t the job of the proxy to dynamically decide. The try list is provided for convenience. This functionality is rather trivial to implement with a plugin, and besides not being compatible with potential existing plugins, there isn’t much point to a niche usage like this one.
