### ISSUE TITLE
Fix packets pls

### ISSUE THREAD

**Issue by roggy666** [PaperMC/Velocity#728]
When Java players try to enter, they have an error.
exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@129749e4
com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
--
I use ViaVersion (Main server side)
And GeyserMC, geyser players can join, but when they write something in the chat, they get kicking with the same massage in the console

**Comment by CoreyShupe** [comment]
Please do not use 1.19 in production right now - it's unstable and in development. Patches will be pushed soon.

**Comment by emmanuelvlad** [comment]
can't we keep it open so people could be notified when fixed?

**Comment by jacoballen1** [comment]
People should not be using it in production, as Corey said, so there is no need to leave this open for notification purposes. We will make people aware when it is ready.
