### ISSUE TITLE
Velocity says that forvarding.secret is empty but is isn't!

### ISSUE THREAD

**Issue by Overwrite987** [PaperMC/Velocity#738]
After updating velocity to the latest snapshop (150), I found an incomprehensible bug. After enabling the "bungeeguard" mode and running the proxy, it tells me that my forwarding secret file is empty. But it was already generated by the proxy at the first launch and just can't be empty!
Video-proof: https://drive.google.com/file/d/1T_CIxEpqxNQWnUJ7ez82DW9LyUssI3gC/view?usp=sharing
error: https://pastebin.com/QbbXjUMH

**Comment by RoccoDev** [comment]
Yes, that snipped you posted is wrong because of operator precedence, it should be:
```java
if (forwardingSecret.length == 0 && (forwardingMode == MODERN || forwardingMode == BUNGEEGUARD))
```
