### ISSUE TITLE
Can't start Velocity 3.1.2-SNAPSHOT (git-74edac96-b153)

### ISSUE THREAD

**Issue by Askarionn** [PaperMC/Velocity#740]
https://pastebin.com/a0EcSqdM

**Comment by motz0815** [comment]
same error here

**Comment by logsym** [comment]
Please attach your `velocity.toml` configuration contents as well. If possible, it would be appreciated you paste the contents here on GitHub so others don't have to go to a different (ad-filled) site.

Edit:

See [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) on how to paste exceptions and code/config data.

I am interested specifically in the `forwarding-secret-file` parameter in your configuration file. Also which operating system are you using?

**Comment by motz0815** [comment]
A Java 17.0.2 container running in docker.
I don't have any velocity.toml. After upgrading to this version, the console told me to delete it and let it re-generate a new one with the newer options. So I did exactly that - delete the config file and restart.
Even in a completely empty folder, just starting the velocity.jar, this error occurs.

**Comment by Xernium** [comment]
This happens 

> A Java 17.0.2 container running in docker.
> I don't have any velocity.toml. After upgrading to this version, the console told me to delete it and let it re-generate a new one with the newer options. So I did exactly that - delete the config file and restart.
> Even in a completely empty folder, just starting the velocity.jar, this error occurs.

This happens because your container doesn’t have a valid Java $TMP location the proxy is able to read/write/modify to. It also needs to be able to write/read/modify in the ENV user.dir to generate a config file

**Comment by logsym** [comment]
Looks like the culprit might be the forwarding secret file logic and not the main configuration file: `at com.velocitypowered.proxy.config.VelocityConfiguration.read(VelocityConfiguration.java:482)`

@motz0815 could you show an example of what your Dockerfile looks like? I'm interested in how you run the velocity jar and the layout of the file system in the image. Please describe everything that is copied over in your `COPY` statements as well.

And when you say you started it in a completely empty folder, does that mean it was _not_ in Docker, but in Windows/macOS or something?

**Comment by 4drian3d** [comment]
> Looks like the culprit might be the forwarding secret file logic and not the main configuration file: `at com.velocitypowered.proxy.config.VelocityConfiguration.read(VelocityConfiguration.java:482)`
> 
> @motz0815 could you show an example of what your Dockerfile looks like? I'm interested in how you run the velocity jar and the layout of the file system in the image. Please describe everything that is copied over in your `COPY` statements as well.
> 
> And when you say you started it in a completely empty folder, does that mean it was _not_ in Docker, but in Windows/macOS or something?

Part of the fault is the logic for loading the forwarding-secret-file file, for example, I was testing pull request #666 days ago and that caused the config-version option to change to 1.1, which according to the current logic, the configuration would have been restarted and the forwarding-secret-file option should have a valid value by now, but currently it did not exist, using the default value of "" which goes to the velocity directory, not to a file. In pull request #743 I fixed that
