### ISSUE TITLE
[feature request] auto-tab-complete toggle

### ISSUE THREAD

**Issue by TOWUK** [PaperMC/Velocity#742]
like a spigotmc please **add** this function
for example to hide plugins from the list such as lpv / viaversion / vvviaversion and so on
![image](https://user-images.githubusercontent.com/28830162/173204002-b6d5c2c3-0c1a-4aca-a2e6-42d02e2dfd59.png)

**Comment by Xernium** [comment]
The first one doesn’t work with Brigadier-
And the second one also goes against brigadier. So no, we will not consider this. (And we really can’t)

**Comment by Xernium** [comment]
Just as a side-note: Plugins can absolutely block auto-completion of commands.
For connections with 1.13 and above you should edit the root command node on https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/command/PlayerAvailableCommandsEvent.html and to achieve the same on 1.12.2 and older you need to interact with the https://jd.papermc.io/velocity/3.0.0/com/velocitypowered/api/event/player/TabCompleteEvent.html event
