### ISSUE TITLE
Console doesn't translate game's locale keys

### ISSUE THREAD

**Issue by Sanluli36li** [PaperMC/Velocity#745]
![image](https://user-images.githubusercontent.com/5201743/173357742-c64b0739-3a5f-41d7-9b9b-25f82a525af2.png)
Console doesn't translate game's localized keys. Should be displayed in English at least.

**Comment by 4drian3d** [comment]
Velocity does not have the official Minecraft translations, it only contains its own translations. I don't know how "legal" or permissible it would be to include at least the English translations in Velocity.
In the case of messages to the player, the player's client is responsible for translating the message.

**Comment by Xernium** [comment]
As @4drian3d said, there is no good way for us to do this.
