### ISSUE TITLE
sent message with invalid signature

### ISSUE THREAD

**Issue by Folas1337** [PaperMC/Velocity#746]
If you use velocity in modern fowarding mode and run a current paper 1.19 server behind it, a 1.19 client won't be able to send messages and in the paper console it'll show you the following error:
<user> sent message with invalid signature: '\<message\>'

I have verified this on my online as well as local server, running velocity build 153 and paper build 8.
If I switch to a forwarding mode like bungeeguard, it works fine. Any clients lower than 1.19 are also fine (if you for example allow them to connect through ViaVersion+ViaBackwards.

**Comment by galacticwarrior9** [comment]
Can confirm on `Velocity 3.1.2-SNAPSHOT (git-74edac96-b153)`. Backend server used Purpur 1665.

**Comment by Xernium** [comment]
Cannot reproduce. Doesn't happen on Paper 1.19 builds and recent Velocity builds- Is probably down to a Tablist plugin or a chat plugin you are running.

**Comment by Folas1337** [comment]
I have to agree, it was me running MultiChat on Velocity and totally forgot to check its plugins for issues.
My bad, sorry guys!

**Comment by Folas1337** [comment]
> Cannot reproduce. Doesn't happen on Paper 1.19 builds and recent Velocity builds- Is probably down to a Tablist plugin or a chat plugin you are running.

One thing though... why does this only happen in modern forwarding mode and not in any other mode (like legacy and bungeeguard)? It seems like legacy is forwarding the signature while modern isn't, otherwise feel free to correct me :)
