### ISSUE TITLE
Players get kicked cause of multiplayer.disconnect.missing_public_key

### ISSUE THREAD

**Issue by just-dev-creator** [PaperMC/Velocity#748]
When trying to connect trough a 1.19 client to the latest velocity version, I get kicked with the following reason displayed in game:
`Missing profile public key.
This server requires secure profiles. `

The console displays the following message:
`[initial connection] /xxx:45906 has disconnected: multiplayer.disconnect.missing_public_key`
I don't know how this relates to [MC-252942](https://bugs.mojang.com/browse/MC-252942), but I can confirm that the mojang servers are online as I can connect to other servers without any problems.

**Comment by 4drian3d** [comment]
Set the option https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/resources/default-velocity.toml#L19 to false

**Comment by just-dev-creator** [comment]
Thank you very much @4drian3d, that did indeed solve the problem. Apparently the option was not present in my local version of the config, otherwise I might have come across it earlier.

**Comment by UmerSalman02** [comment]
i am facing this problem should i enable it or disbale?

**Comment by 4drian3d** [comment]
> Set the option https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/resources/default-velocity.toml#L19 to false
