### ISSUE TITLE
io.netty.channel.AbstractChannel$AnnotatedConnectionException error

### ISSUE THREAD

**Issue by onebeastchris** [PaperMC/Velocity#752]
https://paste.gg/p/anonymous/cdac9246b4aa469bb85486ad9e5c4436

[link to log](https://paste.gg/p/anonymous/cdac9246b4aa469bb85486ad9e5c4436) 

This error shows up with the newest velocity version - any idea what's causing it? It says server unreachable, but if that's the case, why throw an error 20 lines long 👀
-> server should've been reachable, since it's online during the time + other players have connected to it

Velocity connects to a 1.19 fabric server in the background - if you need me to provide anything else, just lmk

**Comment by electronicboy** [comment]
All we can see is that the server refused the connection, i.e. nothing was running on that port or network config issues
Cleaning up those exceptions is on the todo list given that there's very little reason to print the full trace for such an issue in most cases
