### ISSUE TITLE
Error java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by DimaSergeew** [PaperMC/Velocity#753]
Such an error occurs quite often with GeyserMC players, sometimes after this error they cannot even enter the server. That is, they can play normally for a week and then just fly out with it. I wrote in support of the geyser, they sent me here and said that the problem is in Velocity but not on their part. I think this is true, since I did not encounter such an error on Bungeecord. It can happen randomly with any GeyserMC player error log: https://mclo.gs/PesIGk4

**Comment by electronicboy** [comment]
The connection was closed in an unexpected manner, nothing to do with velocity as that isn't our pipeline, that looks to be their connection between the client
