### ISSUE TITLE
Update Configurate Provided in Velocity API

### ISSUE THREAD

**Issue by Astralchroma** [PaperMC/Velocity#764]
Provided version is 3.7.2, latest is 4.1.0. The version provided by velocity is horribly out of date.

**Comment by Xernium** [comment]
Since updating configurate form 3.x to 4.x has breaking changes this will need to wait until a major release.

**Comment by Astralchroma** [comment]
Also, adventure is out of date.

**Comment by kezz** [comment]
> Also, adventure is out of date.

See https://github.com/PaperMC/Velocity/issues/757
