### ISSUE TITLE
Fallback 

### ISSUE THREAD

**Issue by FrancyPro** [PaperMC/Velocity#768]
In my server don't work fallback server, help me.

**Comment by 4drian3d** [comment]
What do you mean it doesn't work? Is there an error?

Can you pass the try configuration section to see how you have it configured?

The best thing to do would be to go to Paper's Discord server to get support

**Comment by FrancyPro** [comment]
ok, I'll give you the configuration

**Comment by FrancyPro** [comment]
https://www.mediafire.com/file/hojrm0dcaifdfr6/velocity.toml/file

**Comment by 4drian3d** [comment]
As I ask you again... in what way does it not work?

**This seems not to be a Velocity bug, but a problem with your proxy settings or your plugins, which may be better addressed in [Discord](https://discord.gg/papermc), although considering that you are using offline mode, support will be limited**

**Comment by FrancyPro** [comment]
The problem is that when I'm on a server and it reboots it doesn't redirect me to the fallback server but it kicks me with internal server problem.

**Comment by Xernium** [comment]
Internal server error?    
Sometimes a fallback will not work if the client is in an invalid state, we can’t do anything about that. Please provide a list of your plugins too and a list of backend servers, versions and their types
