### ISSUE TITLE
sent message with invalid signature

### ISSUE THREAD

**Issue by IIMuyaII** [PaperMC/Velocity#770]
if I do "player-into-forwarding-mode =modern", this is a problem.

`! [Tue 18:53:11 WARN  Server/PlayerConnection] IIMuyaII sent message with invalid signature: 'ghfhgfhghfghgf'
! [Tue 18:53:17 WARN  Server/PlayerConnection] IIMuyaII sent message with invalid signature: 'fghfghfghfg'
! [Tue 18:53:38 WARN  Server/PlayerConnection] IIMuyaII sent message with invalid signature: 'a'

this problem only happens if you are logged in with client vanilla 1.19.

**Comment by kyngs** [comment]
Does this appear on the server or the proxy? If possible attach the log of both.

**Comment by IIMuyaII** [comment]
server, 1.19 this is reflected on my server console.

i can forward the log in the morning.
velocityversion:
> velocity version
[23:25:15 INFO]: Velocity 3.1.2-SNAPSHOT (git-0caff79b-b156)
[23:25:15 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[23:25:15 INFO]: velocitypowered.com - GitHub

1.19 Server Version:
[23:26:32 INFO]: Checking version, please wait...
[23:26:33 INFO]: This server is running Paper version git-Paper-33 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 147a2b7)
You are running the latest version
Previous version: git-Paper-32 (MC: 1.19)

**Comment by HarisAli3** [comment]
This same thing is happening with me , i am using latest velocity with 1.19 server . 
![image](https://user-images.githubusercontent.com/99520506/182888770-1d13d26c-2c68-418d-8842-aa374900a866.png)
This message appears on console and is not displayed in chat. Means no can see this message nor me .

**Comment by NotMarra** [comment]
same 
![image](https://user-images.githubusercontent.com/70058346/184101195-6aaaeb2d-3979-4faf-b861-8aedb11bae40.png)

**Comment by IIMuyaII** [comment]
I have updated to 1.19.2 paper version and velocity latest version this problem has been solved.

**Comment by 4drian3d** [comment]
This problem has most likely been fixed in current versions as mentioned, personally I have not been able to reproduce the bug either
