### ISSUE TITLE
QUESTION: How to do memory dump in velocity? Do i need spark for that?

### ISSUE THREAD

**Issue by jokbon** [PaperMC/Velocity#781]
**QUESTION: How to do memory dump in velocity? Do i need spark for that?**

_FEEDBACK: Thanks for making nice proxy, it can handle 3 times bigger load than bungee on my server._
Close this when answered, i will see on email.

**Comment by 4drian3d** [comment]
From the last commit, with the new `/velocity heap` command you can make a heap dump without installing any additional plugin
