### ISSUE TITLE
Preventing double resource pack installations on server switch by player

### ISSUE THREAD

**Issue by Feniksovich** [PaperMC/Velocity#791]
Currently, if a resource pack is sent to a player on a downstream server (let's call it `srv1`), in case the player moves to another server and then back to the `srv1` server, they will have to wait for the resource pack installation process again, although resource pack was already installed by the player earlier.

Was previously discussed [here](https://discord.com/channels/289587909051416579/908507886420910101/995706539342053436).

**Comment by hhrht** [comment]
^

**Comment by Xernium** [comment]
You did provide the hash for the pack in either instance?
If this still happens if the correct hash is provided then this is an actual issue.

**Comment by Feniksovich** [comment]
Yes, this happens regardless of whether the hash is passed or not (also correct or no). That's just how it works in Minecraft by default and it's not Velocity specific problem.
