### ISSUE TITLE
[Forge1.12.2][SpongeForge] Velocity couldn't work with SpongeForge

### ISSUE THREAD

**Issue by Longtianmu** [PaperMC/Velocity#793]
Velocity side log(Java17)
![image](https://user-images.githubusercontent.com/60567448/178323363-b1948162-b6e4-4c53-be7c-8bdf7bd0d91a.png)
SpongeForge side log(Java 8)
![image](https://user-images.githubusercontent.com/60567448/178323427-741f29fd-b29e-4501-b84d-4f1b96d5c27e.png)

**Comment by Xernium** [comment]
The biggerpackets mod breaks compatibility with the vanilla protocol spec and is therefore unsupported. We accommodate mods wherever possible, but this is not one such case.

**Comment by Longtianmu** [comment]
> The biggerpackets mod breaks compatibility with the vanilla protocol spec and is therefore unsupported. We accommodate mods wherever possible, but this is not one such case.

When delete biggerpackets,the error still exists.
![image](https://user-images.githubusercontent.com/60567448/178339757-0a5fd647-3826-4d69-9298-5929048ee338.png)
