### ISSUE TITLE
[Forge1.12.2][SpongeForge] Velocity couldn't work with SpongeForge #2

### ISSUE THREAD

**Issue by Longtianmu** [PaperMC/Velocity#794]
When delete biggerpackets,the error still exists
![image](https://user-images.githubusercontent.com/60567448/178345952-fb6e4813-95c5-4940-b4f5-86470749126d.png)

**Comment by electronicboy** [comment]
All we can see is that the server disconnected you, make sure that you removed that mod from both sides, otherwise, generally, you're potentially gonna need to start yanking mods, there's nothing here for us to work off
