### ISSUE TITLE
Minify Core

### ISSUE THREAD

**Issue by ghost** [PaperMC/Velocity#802]
Please minify all java scripts for Velocity to work quickly

**Comment by astei** [comment]
![image](https://user-images.githubusercontent.com/16436212/181106013-96918a1f-e728-4f84-8856-8a9d4fece315.png)

**Comment by astei** [comment]
FYI: Minifying the Java source code will not do a thing to improve performance.

**Comment by Cryptite** [comment]
It is well known that spaces and newlines cause tremendous performance problems in object oriented programming languages.

**Comment by BBaoVanC** [comment]
> It is well known that spaces and newlines cause tremendous performance problems in object oriented programming languages.

I'm no expert but as far as I know it should have no performance difference at runtime since it's a compiled language. (Java != JavaScript)
