### ISSUE TITLE
Not working with 1.19.1

### ISSUE THREAD

**Issue by seb303** [PaperMC/Velocity#803]
https://logpaste.com/eYH6dbnV

velocity-3.1.2-SNAPSHOT-162
ViaBackwards-4.4.0
ViaVersion-4.4.0

Backends are PaperMC 1.17.1 and Fabric 1.19

**Comment by seb303** [comment]
Here's the full log include start-up:
https://logpaste.com/aoJ51W0U
1.19 clients are working fine.
The 1.19.1 client is user seb303

**Comment by electronicboy** [comment]
Yes, we know, 1.19.1 literally just released, a velocity release will come soon™

**Comment by weihao** [comment]
@electronicboy not sure why you closed the issue. It still doesn't work with 1.19.1, so that's a valid request.

Updates on this?

**Comment by seb303** [comment]
@electronicboy
I too would prefer to see this issue left open until a velocity release supporting 1.19.1 is available.

Vanilla clients are now using 1.19.1 by default, and this is currently broken with Velocity even using the latest ViaVersion & ViaBackwards (4.4.1 has same problem as with 4.4.0 reported above)

**Comment by birdhimself** [comment]
@weihao @seb303 There's an open PR #772, you can just check the progress there.
