### ISSUE TITLE
add component in version and samplePlayer in MOTD

### ISSUE THREAD

**Issue by deestt** [PaperMC/Velocity#805]
I wanted to do my own MOTD with a custom version message and I will do info on hitting it has discord and etc. with hex colors

**Comment by astei** [comment]
you can do this with a plugin

**Comment by deestt** [comment]
I know that using a plugin, but my point is to add Version and SamplePlayer instead of a string to add a component

**Comment by electronicboy** [comment]
We can't add a component, if we did we'd need to serialise those back to raw strings anyways, so that makes 0 sense
