### ISSUE TITLE
Velocity registers channels on server switch as if they're registered from the client

### ISSUE THREAD

**Issue by VidTu** [PaperMC/Velocity#819]
After registering channel on Paper via `Bukkit.getMessenger().registerIncomingPluginChannel(Plugin, String, PluginMessageListener)` it does not appear (with vanilla client) in `Player.getListeningPluginChannels()`, but it appears there after switching servers with Velocity.
Steps to reproduce:
1. Set up Velocity and two Paper servers.
2. Register incoming channel `test:channel` (via `Bukkit.getMessenger().registerIncomingPluginChannel(this, "test:channel", (a, b, c) -> {})`)  on the first Paper server. (do not install any plugins on the second Paper server or Velocity)
3. Join the first Paper server via Velocity.
4. See that `Player.getListeningPluginChannels()` returns nothing. (or `BungeeCord` if `bungee-plugin-message-channel` is enabled in `velocity.toml`; expected behavior)
5. Switch to the second Paper server and switch to the first Paper server again.
6. See that `Player.getListeningPluginChannels()` now returns `test:channel`.

Example video: https://www.youtube.com/watch?v=fSPr45eJaSI
Velocity plugins: (none).
Plugins on the first Paper server: [Test](https://paste.gg/p/VidTu/e7f2e128d6a44dee910c1c4a8230a79c).
Plugins on the second Paper server: (none).
Possible fix is #591.

**Comment by AoElite** [comment]
I'm having this issue as well, can confirm this still happening with velocity 8761d02def69d9c2ed8e026ba348a7468a4c6d7b

**Comment by jascotty2** [comment]
I just switched my network over to Velocity and am having an issue related to this:

- Server1 and Server2 are listed in servers.try so they will fall back to a working one if one is down.
- Player connects, they are forwarded to server1. 
- Any client mod channels and plugin channels are registered with no issues.
- Player switches to server2. 
- Velocity forwards each and every plugin & mod channel that have been registered for all players to server2 on behalf of the player.
- Server2 cannot accept all of those channels from one player at a time.
- Server2 kicks the player for too many channels.
- Velocity forwards the connection to Server1.
- Velocity forwards each and every plugin & mod channel that have been registered for all players to server1 with the player login.
- Server1 kicks the player for too many channels.
- This repeats ad infinitum.

**Comment by 4drian3d** [comment]
Fixed in pull request #591
