### ISSUE TITLE
How to correctly create a CommandSource object for server.getCommandManager().executeAsync?

### ISSUE THREAD

**Issue by FirstL1ght** [PaperMC/Velocity#826]
I wanted to use [this RCON plugin](https://github.com/UnioDex/VelocityRcon). I rebuilt it with the latest dependencies and it works, but now I ran into a problem that the commands are not being executed by the `server.getCommandManager().executeAsync()`.

I decided to write a [simple plugin to check it separately](https://github.com/FeelinVoids/velocity-execute-test), and the commands are still not being executed.

Here is my CommandSource:
```
public class CommandExecutor implements CommandSource {
    private final Logger logger;

    public CommandExecutor(Logger logger) {
        this.logger = logger;
    }

    private PermissionFunction permissionFunction = ALWAYS_TRUE;

    @Override
    public PermissionChecker getPermissionChecker() {
        return permission -> getPermissionValue(permission).toAdventureTriState();
    }

    @Override
    public boolean hasPermission(String permission) {
        return true;
    }

    @Override
    public void sendMessage(@NonNull Component component) {
        logger.info(LegacyComponentSerializer.legacySection().serialize(component));
    }

    @Override
    public Tristate getPermissionValue(String permission) {
        return this.permissionFunction.getPermissionValue(permission);
    }
}
```

And that's how I'm trying to use it:
```
public class ExecuteTest {

    private final Logger logger;
    private final ProxyServer server;

    @Inject
    public ExecuteTest(ProxyServer server, Logger logger) {
        this.logger = logger;
        this.server = server;
    }

    public void createBrigadierCommand() {
        LiteralCommandNode<CommandSource> helloNode = LiteralArgumentBuilder
                .<CommandSource>literal("test")
                .executes(context -> {
                    Component message = Component.text("Executing", NamedTextColor.GREEN);
                    context.getSource().sendMessage(message);

                    // CommandSource source = context.getSource();
                    CommandExecutor source = new CommandExecutor(logger);
                    server.getCommandManager().executeAsync(source, "stop");
                    return 1;
                })
                .build();

        server.getCommandManager().register(new BrigadierCommand(helloNode));
    }

    @Subscribe
    public void onProxyInitialization(ProxyInitializeEvent event) {
        createBrigadierCommand();
    }
}
```
The plugin adds a `test` command, which should execute `stop` command from code. The command is not being executed with my `source`. However, if I use `context.getSource()`, it works.

So how should I create a custom CommandSource object for this?

**Comment by 4drian3d** [comment]
The /stop command can only be executed from the ConsoleCommandSource https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/command/builtin/ShutdownCommand.java#L40

**Comment by A248** [comment]
The dreaded culprit, swallowed exceptions, may be foiling you here. Look at this line:
```java
server.getCommandManager().executeAsync(source, "stop");
```
The method `executeAsync` returns a `CompletableFuture`. Every time you receive such an object, you *must* check it for exceptions -- no exceptions.

**Comment by astei** [comment]
You cannot invoke the `/stop` command using any other command source other than the `ConsoleCommandSource`.
