### ISSUE TITLE
Attempting to register a packet with a protocol version same as lastValidProtocolVersion throws an Exception.

### ISSUE THREAD

**Issue by kyngs** [PaperMC/Velocity#828]
When I attempt to register a packet mapping with the same protocol version and last valid protocol version **while the proxy's max protocol version is higher than the mapping protocol version**, I get the following exception:
```
Next mapping version (1.19) should be lower then current (1.19)
```
This is related to this code part:
https://github.com/PaperMC/Velocity/blob/6496983ca3b36db56b50cd3a9589c254460f5cfc/proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java#L423-L426

Example scenario when this is unwanted:
Let's get back to when 1.19 just came out and changed the mapping for the MapData packet. I went and created the following mapping:
id = 0x24
protocolVersion = 759 (1.19)
lastValidProtocolVersion = (1.19)

This worked fine, however, when I downloaded Velocity with 1.19.1 support, this broke.
The obvious solution would be to add a mapping supporting 1.19.1, but, this will break when you install Velocity with 1.19.2 support and so on...

A long-term solution would probably be to delete the mentioned code block completely.

***I realize that I am using internal Velocity stuff and not the API, however, I have no other option***

**Comment by Xernium** [comment]
I am confused. The last supported version should only ever be supplied once, to indicate that the registry should not assume this packet exists/ is continued in future versions. As you are using static mappings you will likely have to update them either way; There is no way to make this generic. You will also likely collide with some other mappings with the hard-coded ID in the future too, so I really think this isnt something we should consider.

**Comment by kyngs** [comment]
> I am confused. The last supported version should only ever be supplied once, to indicate that the registry should not assume this packet exists/ is continued in future versions. As you are using static mappings you will likely have to update them either way; There is no way to make this generic. You will also likely collide with some other mappings with the hard-coded ID in the future too, so I really think this isnt something we should consider.

Well, this is kinda hard to explain, I just want it not to intercept the packet until I explicitly add the support for it, which is why I am providing the last supported version. The truth is, that this works fine and as intended. I'm not sure that I understand what you meant by colliding with other mappings. However, if you really do not want to remove this, I will just inject the mapping manually (Trust me, I am not happy about it).
