### ISSUE TITLE
How to limit players from using /server command?

### ISSUE THREAD

**Issue by WilliamPlays0402** [PaperMC/Velocity#831]
This isn't actually an issue, but a question (I couldn't find anywhere else), how do you remove permissions from all players for using the /server command?
I would like to prevent them from joining a private server manually, but to be connected after doing a task (e.g. parkour).
How would I do this?

**Comment by 4drian3d** [comment]
You have to deny permission to execute the [`/server` command](https://docs.papermc.io/velocity/built-in-commands#server) with a permissions plugin like [LuckPerms](https://luckperms.net)
To send a player to another server in some other way you can do it from the server via the `bungee plugin messaging channel` or with a Velocity plugin

**Comment by WilliamPlays0402** [comment]
@4drian3d
> You have to deny permission to execute the [`/server` command](https://docs.papermc.io/velocity/built-in-commands#server) with a permissions plugin like [LuckPerms](https://luckperms.net)

I tried to use Luckperms already to remove permissions for `velocity.command.server`
![remove](https://user-images.githubusercontent.com/49759911/183992841-d404d93f-1096-4ee3-bba0-98211ccb231c.png) ,
then I deopped myself and then tried the command `/server` again:
![server](https://user-images.githubusercontent.com/49759911/183993270-ddd9ff4c-c019-48f0-afce-3f438f091637.png)

But it still worked.

**Comment by 4drian3d** [comment]
Are you using LuckPerms on Velocity? Try with `/lpv group default permission set velocity.command.server false`

Velocity does not have the concept of `op`

**Comment by WilliamPlays0402** [comment]
Thank you!
It was /lp**v** (I was wondering what the V was at the end of it was (I was using regular /lp)).

**Comment by sigma-abc** [comment]
this also helped me
