### ISSUE TITLE
Unsupported protocol version 756

### ISSUE THREAD

**Issue by burak-105** [PaperMC/Velocity#834]
![image](https://user-images.githubusercontent.com/92051998/184444087-7c2e49c4-7fcc-429f-95cf-8c602dbc2bfd.png)

edit:
I forgot to add important details lmao
Ok so im trying to connect from 1.17.1, to a 1.8 server with protocolsupport, I use protocolsupport to let older versions like 1.5 join

**Comment by electronicboy** [comment]
Your server refused the connection due to an unsupported protocol version, afaik, PS only provides support for older versions, not newer ones
