### ISSUE TITLE
[Feature] Add an event when player disconnects any server

### ISSUE THREAD

**Issue by kyngs** [PaperMC/Velocity#835]
While we have KickedFromServerEvent, it only fires when the player is well... kicked. To my knowledge, there isn't any event that always fires when a player exits a server. A BungeeCord alternative to this would be [ServerDisconnectEvent](https://github.com/SpigotMC/BungeeCord/blob/78ca16dfe3bf9a21d5c054a1884d4f5f198a62bc/api/src/main/java/net/md_5/bungee/api/event/ServerDisconnectEvent.java)

**Comment by Nacioszeczek** [comment]
`ServerConnectedEvent` allows you to get the previous server which would de facto be the server you disconnected from, should be a viable option unless I missed something?

**Comment by kyngs** [comment]
> `ServerConnectedEvent` allows you to get the previous server which would de facto be the server you disconnected from, should be a viable option unless I missed something?

This is a year old issue and I honestly don't remember the details. I'm going to close it.
