### ISSUE TITLE
Client 1.16.5 Forge version player skin BUG

### ISSUE THREAD

**Issue by ReverseAllen** [PaperMC/Velocity#844]
Client 1.16.5 Forge version player skin have bug.

After the player enters the default lobby server and switches the sub-server, the display of the hat skin on the head will appear abnormal.

Players need to manually click to open the appearance customization function menu, and then close the menu, the hat part skin will be displayed normally.

**Comment by astei** [comment]
Clearly a mod problem, doesn't sound like Velocity has anything to do with it

**Comment by Wonkiest29** [comment]
no sorry of reopen but i have forge 1.16.5 and without mods i have too error

**Comment by electronicboy** [comment]
Skins won't work on forge without a mod to provide support for ip forwarding, not a velocity issue

**Comment by Wonkiest29** [comment]
> Skins won't work on forge without a mod to provide support for ip forwarding, not a velocity issue

if possible can you share examples I just don't know what mod
ps im using paper minecraft
