### ISSUE TITLE
Operator Bug

### ISSUE THREAD

**Issue by LeftUnScarred** [PaperMC/Velocity#851]
I manage a modded server hooked into a velocity proxy. I’ve noticed a bug where if I try to run the /op (player) command in the console to make myself operator (as I own both the server proxy and other servers connected to the proxy. It will immediately kick me from the server as well as refuse to let me back in. Setting me down to the lobby of the proxy. I’ve tried multiple different combinations of solutions and have been unable to fix it altho it is able to be replicated easily by typing the command again. No matter what I do it refuses to let me have someone be Operator on the server. Any help in fixing this or if it’s something that must be done by you guys would be much appreciated.

**Comment by Xernium** [comment]
This is caused by modded Brigadier command argument types. Install CrossStitch to fix that issue.
