### ISSUE TITLE
Communication and unknown errors

### ISSUE THREAD

**Issue by WeroCode** [PaperMC/Velocity#857]
Hello.
For my server I need Spigot to send data to Velocity.
With Waterfall and the same code everything works.

Spigot:
![Spigot](https://user-images.githubusercontent.com/101685731/188298288-764b5d9a-cf03-47d4-afde-367cb549ee5a.png)

Velociy:
![Velocity)](https://user-images.githubusercontent.com/101685731/188298579-e1c78018-5d85-4e04-959f-b4ddbb8f954b.png)

Velocity Config: 
[Config](https://github.com/PaperMC/Velocity/files/9484083/velocity.txt)

Error:
[latest.log](https://github.com/PaperMC/Velocity/files/9484078/latest.log)

The error occurs only after writing the digit 1 or 2, 1 - sends the message via Bukkit, 2 - through the user.

**Comment by electronicboy** [comment]
The bungeecord channel expects that you follow the bungeecord channel spec, not try to send arbitary data over it, create your own messaging channel and use that
