### ISSUE TITLE
How to create messaging channel

### ISSUE THREAD

**Issue by WeroCode** [PaperMC/Velocity#858]
### Hello again.
My last issue: [https://github.com/PaperMC/Velocity/issues/857](https://github.com/PaperMC/Velocity/issues/857)

According to the answer I registered a channel in Spigot:
`this.getServer().getMessenger().registerOutgoingPluginChannel(this, "serverchannel");`
`this.getServer().getMessenger().registerOutgoingPluginChannel(this, "serverchannel2:main");`

And found a way to register a channel in Velocity:
`server.getChannelRegistrar().register(new LegacyChannelIdentifier("serverchannel"));`
`server.getChannelRegistrar().register(MinecraftChannelIdentifier.create("serverchannel2", "main"));`

When trying to send something to these channels, Velocity gets nothing.

My Config on Previous Issue
Thank you for answering in advance

**Comment by hugmanrique** [comment]
Make sure you also send the messages to these new channels in the Bukkit plugin. For an example on how to use the plugin messaging API on Velocity, see [this gist](https://gist.github.com/Xernium/95c9262c5f70b8791557861bbc09be1b) by Five. Further questions should be posted in the Discord server, this is an tracker for issues in the Velocity API and implementation.

Final note: you shared your forwarding secret in the config pastebin, make sure you replace it.

**Comment by WeroCode** [comment]
Don’t worry, I knew I gave this code, it’s a test server, and it’s not going to upload to hosting and so on.
I’m sending messages, and thanks for the recommendation.

**Comment by WeroCode** [comment]
Sorry, I saved the output file to the core, not to the plugins folder :)
