### ISSUE TITLE
Cracked clients are immediately disconnected, no logs on terminal

### ISSUE THREAD

**Issue by hiarthurbr** [PaperMC/Velocity#863]
Describing the problem:
While using velocity, a cracked player cannot join a server, as it is immediately disconnected, without sending any connection logs on terminal (pings are registered thought)
Terminal view:
![image](https://user-images.githubusercontent.com/54512246/189514649-f985b613-69aa-43c4-8467-e9662d2784db.png)

Using an authenticated account with the same name is enough to solve the problem, but I'm curious on whats happening here

(on the screenshot I'm using the latest velocity, with some plugins, but I have tried removing all plugins, reseting config, testing a vanilla client, etc) 

Cracked client view:
![image](https://user-images.githubusercontent.com/54512246/189514752-349d307d-c40b-4e7e-a4c8-ee049c5a2628.png)

The original client successfully connects to the server.
![image](https://user-images.githubusercontent.com/54512246/189514807-9aedf684-866e-479a-b2c2-0a340b8439f4.png)

**Comment by Xernium** [comment]
There’s a problem in 1.19 that messes up the disconnect reason. I am guessing force-key-authentication is causing your issue. Keep in mind that offline-mode/cracked players and piracy in general is unsupported and you wont get any further help here exclusive to this use.
