### ISSUE TITLE
1.19.1/1.19.2 Player gets kicked when CommandExecuteEvent gets triggered

### ISSUE THREAD

**Issue by julian-siebert** [PaperMC/Velocity#866]
Hello,

I wrote a plugin which cancels the CommandExecuteEvent and everytime a player playing in 1.19.1/19.2 via Viaversion, the player gets kicked with this message: "A proxy plugin caused an illegal protocol state. Contact your network administrator."
In 1.19 and lower everything works fine.

Why does this happen and how can I fix this issue?

Backend Servers: Paper 1.18.2
ViaVersion: Latest Snapshot
Velocity Version: Velocity 3.1.2-SNAPSHOT (git-57ca66de-b181)

**Comment by julian-siebert** [comment]
I'm not that amazing in English, so sorry for that

**Comment by astei** [comment]
There's not a ton we can do without basically reworking how chat signing works at the proxy level, so don't consider it in scope right now.

We can look at loosening things when chat/profile messages aren't validated but that really just kicks the can down the road.

**Comment by Xernium** [comment]
I requested this issue be opened, is related to a bug in command handling that causes all commands to be signed regardless of provided command registry. Tracking this here

**Comment by julian-siebert** [comment]
I've updated velocity to the latest available update on Papermc and 1.19.1/1.19.2 players are able to execute command but the problem is that the CommandExecuteEvent is still not cancelable :(

**Comment by julian-siebert** [comment]
Will there be an update soon which fixes this bug?

**Comment by BingYanchi** [comment]
CommandExecuteEvent is pretty important for the security of login plugins, hopefully this will be fixed.

**Comment by Xernium** [comment]
> CommandExecuteEvent is pretty important for the security of login plugins, hopefully this will be fixed.

The use-case you're referring to is unsupported by us because it primarily caters to piracy of the game.

Regardless, somewhere in the future this will be fixed, but until then you should do this sort of thing on the backend server rather than the proxy.

**Comment by BingYanchi** [comment]
请耐心等待加载完毕...

**Comment by julian-siebert** [comment]
> CommandExecuteEvent is pretty important for the security of login plugins, hopefully this will be fixed.

If you think it is important, you can take a look at my velocity fork.
I removed chat signing completely so you won't have to care about it anymore

**Comment by SLTDTKSS** [comment]
Where is the code of chat signature? I'm going to change it.

**Comment by julian-siebert** [comment]
> Where is the code of chat signature? I'm going to change it.

You can take a look on my profile. I already created a patched version of velocity where these "errors" are ignored.

**Comment by 4drian3d** [comment]
> > Where is the code of chat signature? I'm going to change it.
> 
> You can take a look on my profile. I already created a patched version of velocity where these "errors" are ignored.

~~It is not really necessary to make a separate fork of Velocity just to remove those checks, it can be done from plugins, for example with https://github.com/4drian3d/UnSignedVelocity
The problem with doing a fork is that you can't always have it updated to the latest version of Velocity, for example, the fork you have doesn't support 1.19.4.~~

~~Now, according to some tests I did, this "temporary solution" does not work anymore since version 1.19.4 because of some new checks in the server.~~

The best solution is to use SignedVelocity which synchronizes Velocity modifications via plugin messages to the backend server https://modrinth.com/plugin/signedvelocity/

**Comment by TroubledGnu201MC** [comment]
its beacuse youre muted on servers for secs or mins or hours or days. weeks. years ... its by a SRMOD if you mean by multi-players or minecraft itself. it can be if youre muted or the file **_raids__** has been deleted.

**Comment by TroubledGnu201MC** [comment]
and the file _raids **is the MC DATAscript._**

**Comment by TroubledGnu201MC** [comment]
and the file _raids_ is the MC DATAscript.

**Comment by 4drian3d** [comment]
> and the file _raids_ is the MC DATAscript.

That has nothing to do with this issue

**Comment by julian-siebert** [comment]
Well, kinda found a solution for myself
