### ISSUE TITLE
HEX not working

### ISSUE THREAD

**Issue by DarkKeeper1** [PaperMC/Velocity#872]
Greetings, dear Velocity developers, I am writing with a complaint that I want to make the entire server in 1 style with HEX, which does not work for you in the messages.properties file, either the usual color is displayed instead or nothing is displayed, please do so was HEX and I was able to do it with methods like on the site https://rgb.birdflop.com/, thanks in advance, I hope you will do it.

**Comment by 4drian3d** [comment]
Duplicate of https://github.com/PaperMC/Velocity/issues/720
