### ISSUE TITLE
[Feature]Configure each backend server's player-info-forwarding-mode

### ISSUE THREAD

**Issue by DreamUniverse843** [PaperMC/Velocity#877]
Could it be able to configure each backend server's player-info-forwarding-mode?

Example:
A pvp Server in 1.8.8(Legacy/Bungeeguard)
A Fabric Server(Modern Only)

tks :)

**Comment by AVuTuVA** [comment]
I agree

**Comment by electronicboy** [comment]
p. sure this was already declined, this would also probably induce some major issues dealing with modern versions

**Comment by DreamUniverse843** [comment]
Well,thank you.
