### ISSUE TITLE
BackendPlaySessionHandler: Packet decoding error

### ISSUE THREAD

**Issue by Platratio34** [PaperMC/Velocity#879]
Running Velocity 3.1.2-SNAPSHOT 168
1 fabric server running Fabrix-Proxy-Light v2.3.0

When a player running 1.19.2 fabric loader 0.14.9 api 0.60.0

When the player tries to join I get this
[latest.log](https://github.com/PaperMC/Velocity/files/9731157/latest.log)

Client just says "Disconnected"

velocity.toml
[velocity.txt](https://github.com/PaperMC/Velocity/files/9731162/velocity.txt)

**Comment by Xernium** [comment]
You need to also install CrossStitch on your server https://www.curseforge.com/minecraft/mc-mods/crossstitch to fix it.
