### ISSUE TITLE
Velocity crash

### ISSUE THREAD

**Issue by Vupsennc** [PaperMC/Velocity#882]
Hello, I have a problem with Velocity. Recently I moved the build to a VPS (Ubuntu) and now the proxy automatically shuts down after a few hours of startup. The only thing I found in the logs is this:

[main/ERROR]: Exception in thread "main" java.io.IOError: java.io.IOException: Input/output error
[main/ERROR]: 	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170)
[Shutdown thread/INFO]: Shutting down the proxy...
[main/ERROR]: 	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
[main/ERROR]: 	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
[main/ERROR]: 	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923)
[main/ERROR]: 	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956)
[main/ERROR]: 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651)
[main/ERROR]: 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)
[main/ERROR]: 	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158)
[main/ERROR]: 	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141)
[main/ERROR]: 	at com.velocitypowered.proxy.Velocity.main(Velocity.java:70)
[Shutdown thread/INFO]: Closing endpoint /0.0.0.0:25565
[main/ERROR]: Caused by: java.io.IOException: Input/output error
[main/ERROR]: 	at java.base/java.io.FileInputStream.read0(Native Method)
[main/ERROR]: 	at java.base/java.io.FileInputStream.read(FileInputStream.java:228)
[main/ERROR]: 	at org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73)
[main/ERROR]: 	at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62)
[main/ERROR]: 	at org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168)
[main/ERROR]: 	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57)
[main/ERROR]: 	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160)
[main/ERROR]: 	... 9 more

**Comment by electronicboy** [comment]
Your terminal disconnected, this generally means that the shell, or whatever you were running the server in died; make sure that you're running in a sane environment, i.e. using tmux or screen, etc
