### ISSUE TITLE
Virtual Hosts issues (maybe related with SRV records)

### ISSUE THREAD

**Issue by kyngs** [PaperMC/Velocity#885]
When using ConnectedPlayer#getVirtualHost in the PLAY state, it appears that the method returns a different address than the one which was used while connecting. 
See this part for a code snippet:
https://github.com/kyngs/LibrePremium/blob/d1518c20c4f7838c4c6a90ac1111bd3868e87f69/Plugin/src/main/java/xyz/kyngs/librepremium/velocity/VelocityLibrePremium.java#L231-L233

This prints out the following: `[DEBUG] Virtual host for player DoreK is play.reverial.net/<unresolved>:25565`, even though the player is connecting via `bud.reverial.net`. However, the address provided in the ProxyPingEvent appears to be correct, because the feature works correctly on MiniMOTD. See:
https://github.com/jpenilla/MiniMOTD/blob/bf9d92150c008d2ff0d6aae7bf32179f638d27a2/platform/velocity/src/main/java/xyz/jpenilla/minimotd/velocity/PingListener.java#L52-L54

The user reports that when they change from SRV to A record on their domain, it starts working correctly.

Take a look at this issue since this comment for further details: https://github.com/kyngs/LibrePremium/issues/24#issuecomment-1299022303

**Comment by Xernium** [comment]
This is a known client issue. We can't work around it. SRV records will only work correctly if there is an A-Record for this SRV record with the same name.
