### ISSUE TITLE
Canceled chat messages are forwarded to backend server for 1.19(.0) clients

### ISSUE THREAD

**Issue by AnttiMK** [PaperMC/Velocity#905]
![image](https://user-images.githubusercontent.com/13612979/207915504-a979fcf4-cfe3-42bf-815f-b8fab101479b.png)
If a 1.19(.0) client sends a message and it's canceled (in this case to admin chat prefixed with `%`), the message is still forwarded to the backend server the player is on, even though it shouldn't be. This makes it possible to bypass being muted, for example.
Running Velocity 3.1.2-SNAPSHOT (git-1ec77eb1-b200)

**Comment by Johvu** [comment]
Yes have noticed this too 👍

**Comment by Gerrygames** [comment]
https://github.com/PaperMC/Velocity/pull/941

**Comment by Gerrygames** [comment]
Fixed by https://github.com/PaperMC/Velocity/commit/cb1f336d1438859c8ab6d15b3e494f17324105e8
