### ISSUE TITLE
commands are canceled at the velocity level.

### ISSUE THREAD

**Issue by DarkyCat** [PaperMC/Velocity#907]
Velocity dump: https://dump.velocitypowered.com/owuvibiwif.json
When playing on the server, ABSOLUTELY ALL commands stop working for some players. From all plugins, even if full permissions are issued. The backend and proxy commands are not fully available. That is, when a player with full permissions, partial writes on any server anywhere, it is not logged in the console and does not display any response in the chat.

There are no errors or warnings in the console.

Video (Client 1.19.2, full permissions): https://litter.catbox.moe/6uvz99.webm

**Comment by electronicboy** [comment]
Have you tested without plugins?

**Comment by DarkyCat** [comment]
> Have you tested without plugins?

yes, at first I replaced plugins with blockers (pl-hide-pro, commandblocker, commandblocker). After testing without plugins. Some developers still have such a problem after a recent velocity update, they suggested adding more memory, I put another value of 8 GB instead of 4, but the situation has not changed.

**Comment by DarkyCat** [comment]
This happens randomly for a reason unknown to me, some players are fine, others do not respond to commands. Only a complete restart of the velocity helps. I contacted all the plugin developers that I use + also studied their code and found nothing that could interfere.

**Comment by DarkyCat** [comment]
![изображение](https://user-images.githubusercontent.com/50515714/208098233-bafa5736-e144-4b7d-949e-4f288e33ccde.png)
![изображение](https://user-images.githubusercontent.com/50515714/208098282-f13ad144-d83b-4b89-8c5b-d27f471a64ef.png)
![изображение](https://user-images.githubusercontent.com/50515714/208098311-d6c3b2c9-6224-42b7-80c6-b2ec80735819.png)
I write a lot of commands, but as you can see there is no answer in the chat. (these commands do not reach the backend server at all)
