### ISSUE TITLE
[Bug] Stuck on encrypting

### ISSUE THREAD

**Issue by sethmcallister** [PaperMC/Velocity#908]
Updated from build velocity-3.1.2-SNAPSHOT-179 to velocity-3.1.2-SNAPSHOT-200,

Connecting is prompted with `Encrypting...`, and subsequent 'Timed out'

Configuration: using proxy protocol

**Comment by xism4** [comment]
> Updated from build velocity-3.1.2-SNAPSHOT-179 to velocity-3.1.2-SNAPSHOT-200,
> 
> Connecting is prompted with `Encrypting...`, and subsequent 'Timed out'
> 
> Configuration: using proxy protocol

Probably the reverse thingy you're using is not handling properly connections

**Comment by 4drian3d** [comment]
Can you test in the latest version and without additional plugins installed in Velocity?

**Comment by 4drian3d** [comment]
There is no way to reproduce the possible bug and no answer in almost 2 years, I proceed to close the issue

**Comment by palepinkdot** [comment]
I'm able to reproduce this bug by trying to load too many chunks from a server under the proxy, then restarting both the proxy and the game server. I'm not sure if restarting has anything to do with it or not...

Version 3.3.0

**Comment by happyvalley-lmx** [comment]
Same problem.

Some countries and regions' firewalls may block Minecraft's Online-mode authentication servers, which can result in players getting stuck at the "encrypting..." and eventually receiving a timeout error. To resolve this issue, you need to use a proxy to bypass the firewall or modify the local hosts file to let the server to connect to a functional online authentication servers.
