### ISSUE TITLE
cant join servers through proxy with supported version

### ISSUE THREAD

**Issue by TruLone** [PaperMC/Velocity#911]
When i try to switch to any subserver, it just disconnects me with message "Outdated client! Please use 1.19.2" even though i'm trying on that version. I've tried resetting the hub, using ViaVersion but nothing works. Like look at this! 
![image](https://user-images.githubusercontent.com/108251926/209091421-8bee78c8-759c-443c-8077-621fb902ef8c.png)

**Comment by electronicboy** [comment]
Proxy version? Plugins?

**Comment by TruLone** [comment]
> Proxy version? Plugins?

proxy version: 3.1.1 (thats the one i downloaded), plugins: none

**Comment by electronicboy** [comment]
Use the latest snapshot from the papermc website

**Comment by TruLone** [comment]
ill try

**Comment by TruLone** [comment]
the same thing happens.

**Comment by electronicboy** [comment]
Velocity just passed through the given protocol, I'd suggest trying with an unmodified client and seeing if you can reproduce it without plugins on the backend, failing that, please use the discord for support
