### ISSUE TITLE
Randomly kicking players from Network

### ISSUE THREAD

**Issue by KasprTv** [PaperMC/Velocity#912]
Yesterday I started to having Issue with this error. Any idea how to solve this, please?

![image](https://user-images.githubusercontent.com/71224156/209542663-ce135531-49b7-411c-a1c7-1eca3fcc4e98.png)

**Comment by xism4** [comment]
> Yesterday I started to having Issue with this error. Any idea how to solve this, please?
> 
> ![image](https://user-images.githubusercontent.com/71224156/209542663-ce135531-49b7-411c-a1c7-1eca3fcc4e98.png)

Mostly a plugin issue

**Comment by KasprTv** [comment]
Do you use latest version of Intave anticheat?

**Comment by xism4** [comment]
> Do you use latest version of Intave anticheat?

No, but you should contact the developer then

**Comment by KasprTv** [comment]
> > Do you use latest version of Intave anticheat?
> 
> No, but you should contact the developer then

I did and It was plugin Issue thats why I closed it
