### ISSUE TITLE
Kick-Problem with latest velocity devbuild (201)

### ISSUE THREAD

**Issue by Askarionn** [PaperMC/Velocity#914]
Hello! I face a strange problem on my network. I have 2 servers (survival and skyblock), most of the players are playing on skyblock (~50 skyblock, ~10 survival). After a while all players are getting kicked from skyblock (actually from proxy but just the skyblock players) with message "Timed Out". Basically the connection between skyblock server and velocity breaks somehow. After the kick happen all players can rejoin on lobby, but not on skyblock (everything is working in SkyBlock console, the server doesn't crash). When the players are trying to reconnect on skyblock it doesn't work, velocity doesn't detect the skyblock to be online but after a SkyBlock restart the players will be able to rejoin again.
I tried more things, but after I downgrade velocity version from 201 to 196 the problem is not happening anymore.

I thought it's from TCPShield so I contacted them, they told me that it's on my proxy side.
![image](https://user-images.githubusercontent.com/51824859/209884358-f75f0f3a-d7c6-42ab-adc6-a1790f751fd8.png)
![image](https://user-images.githubusercontent.com/51824859/209884606-2b8eea1d-5f96-43e5-9d04-62b299e087b4.png)
![image](https://user-images.githubusercontent.com/51824859/209884613-bee817c2-db76-41bb-a1e9-18d2177880f7.png)

**Comment by Joo200** [comment]
TCPShield didn't say it's the proxy, looks more like some issue with your backend server (spigot/paper).
There is no such thing as "the backend server has to register itself at the proxy". either it's there or not.
If you have to restart the Skyblock server it's most likely that server crashed or has some other issues. But that's not a proxy issue.

**Comment by Askarionn** [comment]
> TCPShield didn't say it's the proxy, looks more like some issue with your backend server (spigot/paper). There is no such thing as "the backend server has to register itself at the proxy". either it's there or not. If you have to restart the Skyblock server it's most likely that server crashed or has some other issues. But that's not a proxy issue.

The server didn't crashed, I still can execute commands in console. When the connection breaks between skyblock and velocity the players can't even execute proxy commands. The problem appeared after I update the velocity, and if I downgrade to 196 the problem is not happening anymore so how is that not related to velocity?

**Comment by Joo200** [comment]
Sorry, I got a little bit confused there.
I'm not sure what changes between build 196 and 201 could cause such an issue.

The only real change was with build 200. Does any other version between 196 and 201 work?
