### ISSUE TITLE
Feature request: tab-complete disable in velocity plugins

### ISSUE THREAD

**Issue by m1trenv0** [PaperMC/Velocity#917]

**Comment by 4drian3d** [comment]
With plugins like [CommandWhitelist](https://modrinth.com/plugin/commandwhitelist) you can do this, there would be no need to integrate it directly into Velocity

**Comment by xism4** [comment]
> With plugins like [CommandWhitelist](https://modrinth.com/plugin/commandwhitelist) you can do this, there would be no need to integrate it directly into Velocity

Relying on plugins for something like this does not seem right, I think it is correct to integrate a system to deactivate the tab-complete.

**Comment by 4drian3d** [comment]
As already mentioned, this is very easy to integrate into a plugin, there is no need for it to be integrated directly into Velocity as no one would want to remove the tab-complete from their entire network
