### ISSUE TITLE
Proxy doesn't connect players the first time

### ISSUE THREAD

**Issue by ItsMacs** [PaperMC/Velocity#923]
Hi,

I'm running Velocity 3.2.0 (latest version at the time of writing) with this config: https://pastebin.com/FVgqU6UX.

The Proxy is running on CentOS 8 behind TCPShield.

Upon players connecting, they never can join the server on the first attempt, which gets stuck at "_Connecting to the server..._", not even logging onto the Proxy console. To be able to join, we need to exit the connection attempt, refresh the server list and retry, and the second attempt never fails.

**Comment by astei** [comment]
> TCPShield

> online-mode = false
