### ISSUE TITLE
Chat cancellation does not work correctly

### ISSUE THREAD

**Issue by Simonsator** [PaperMC/Velocity#935]
When a plugin cancels a chat message on minecraft clients newer than 1.19 the player is kicked and this message is sent to the console

> A plugin tried to cancel a signed chat message. This is no longer possible in 1.19.1 and newer. Disconnecting player

But this is not true. If you turn off message signing, the problem still occurs, even though messages are not signed anymore. Also, as proven by Bungeecord being able to do it, it is still possible to cancel signed user messages. 

With signed messages, you can still cancel them, but you cannot change the message and then say that this message was send by the player.

**Comment by electronicboy** [comment]
Not sending stuff through to the backend server messes up the chain which ends up causing issues, we are being somewhat overly strict about it but that is in part to avoid reintroducing some of the issues mojang tried to fix
