### ISSUE TITLE
[Consultation] Paper java flags vs Aikar flags

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [PaperMC/Velocity#940]
### Explanation:
I am setting up an instance of Velocity from scratch and I want to do it the best way possible.
I read [this documentation](https://docs.papermc.io/velocity/tuning) and they recommend using these flags for a velocity instance:

`-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15`

But before reading this documentation I was using the flags recommended by Aikar for bungee. They are these:

```
-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions 
-XX:MaxGCPauseMillis=100 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=60 
-XX:InitiatingHeapOccupancyPercent=30 -XX:TargetSurvivorRatio=90 
-Dusing.aikars.suggestion=http://emc.gs/W
```
### Results:
The results are as follows:

Paper java flags:
Initial consumption:
![huoTxlF 1](https://user-images.githubusercontent.com/44591651/214894894-7f87e53a-7671-431d-a57a-43fc7b86f88f.png)

Consumption after some time of logging in and out of the proxy:
Note: The backend servers were down, just throwing the error message "unable to connect to server".
![Captura de pantalla (3624)](https://user-images.githubusercontent.com/44591651/214896598-354f1ecf-c489-4cf8-aa77-bb18771346a6.png)

Aikar flags bungee (less memory usage):
Initial consumption:
![Captura de pantalla (3625)](https://user-images.githubusercontent.com/44591651/214898055-9341b66e-70ce-4253-b37e-39058305e4b4.png)

Consumption after a time of entering and exiting the proxy:
Note: The backend servers were down, just throwing the error message "unable to connect to server".
![Captura de pantalla (3627)](https://user-images.githubusercontent.com/44591651/214899785-93408f0b-6d78-4d52-acbd-b730f947448a.png)

In both scenarios the memory consumption does not return to the initial consumption, there seems to be no garbage collector and the memory just goes up and up.

### Conclusion:
What conclusion should I draw? Which is the best scenario for me in terms of proxy performance and memory usage? With either of the two scenarios will I experience lag spikes?

Should I allow the proxy to use more memory for stability? or the less memory the proxy uses the better?
Thank you for kindly answering my questions.

**Comment by astei** [comment]
Your test is completely meaningless. You're not going to know until you stress the proxy with actual traffic.

The reason for the higher RSS with the Velocity flags is probably because of `-XX:+AlwaysPreTouch` - this is also part of the recommended flag set for Paper too.

**Comment by 7wOv6ySCjo** [comment]
Sorry astei, I still don't really understand the use of java flags and it was something I was trying to understand. I apologise for the misunderstanding.
