### ISSUE TITLE
Disable Plugin from PluginManager?

### ISSUE THREAD

**Issue by weihao** [PaperMC/Velocity#947]
How to disable a plugin if initialization is not going as expected?

**Comment by 4drian3d** [comment]
If something goes wrong when starting your plugin, you should have a logic to be able to warn the user that it has happened or else to be able to fix the bug from within the plugin. If you really want some kind of "disabling" of the plugin, you can avoid loading features if something goes wrong when starting the plugin, for example, if it does not load correctly the configuration, you can avoid loading the other functions of your plugin with a simple return in the ProxyInitializeEvent

**Comment by weihao** [comment]
> 

I am looking for an equivalent method of `getServer().getPluginManager().disablePlugin(this);` in the plugin manager. Velocity should mark the plugin red to indicate there is a problem since users don't usually have access to logs.

**Comment by 4drian3d** [comment]
> > 
> 
> I am looking for an equivalent method of `getServer().getPluginManager().disablePlugin(this);` in the plugin manager. Velocity should mark the plugin red to indicate there is a problem since users don't usually have access to logs.

What do you mean by "should mark the plugin red"?

All server administrators have access to the server logs, from there they can be informed which plugin has not loaded correctly

**Comment by weihao** [comment]
> > > 
> > 
> > 
> > I am looking for an equivalent method of `getServer().getPluginManager().disablePlugin(this);` in the plugin manager. Velocity should mark the plugin red to indicate there is a problem since users don't usually have access to logs.
> 
> What do you mean by "should mark the plugin red"?
> 

By disabling the plugin from plugin manager, `/pl` will mark disabled plugins red. If a plugin is not disabled, it will show up as green even if the initialization failed.

> All server administrators have access to the server logs, from there they can be informed which plugin has not loaded correctly
Yes, you are describing the limitation: only from the logs you can see which plugin has not loaded correctly. And logs are only accessible to administrator who has backend access. 

What if I want check loaded/disabled plugin in-game? What if I want all players to have the ability to check plugins that are not loaded correctly? What if my host is on AWS EKS? It doesn't make sense to give out control panel permission for something you can do in simply the command line.

**Comment by 4drian3d** [comment]
I think very few people would require that functionality in Velocity, if you really want to do something like that in Velocity you can try using ServerUtils https://modrinth.com/plugin/serverutils

**Comment by astei** [comment]
Closing this. The lack of support for "disabling" plugins is from hard-learned experience. We're not going to support it. [It's a position I took from the start of the project.](https://github.com/PaperMC/Velocity/issues/64#issuecomment-417949904)
