### ISSUE TITLE
No error message when join is cancel

### ISSUE THREAD

**Issue by msmanui** [PaperMC/Velocity#952]
Hello. Since i switch from waterfall to velocity whenver a banned player try to join it won't return that he is banned, just will do the message of can't connect to this server. In the console it will appear the banned message but the player is not seeing it.
I've remove all plugins from velocity and backend as well but still. This also happens with the message of outdated client, so i guess it's with every message. 
This as well happens with the whitelist message, etc so is not even related to litebans. 

I'm testing through a lobby -> survival (banned in survival)

Tried with: velocity-3.1.2-207 and velocity-3.2.0-SNAPSHOT-228

**Comment by 4drian3d** [comment]
I cannot reproduce the possible bug in the latest version of Velocity and Paper, the client does receive the kick message correctly
![image](https://github.com/PaperMC/Velocity/assets/68704415/3cdec13c-5032-45f4-898e-85224fbb2b41)
![image](https://github.com/PaperMC/Velocity/assets/68704415/2772ffaf-e6e3-4593-9be8-bc01a1b23b99)
