### ISSUE TITLE
Kicks client and crashes it

### ISSUE THREAD

**Issue by Vivaan-d** [PaperMC/Velocity#970]
All it says is `exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@38d9420 and io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer`. That's it. (I have been experiencing this issue with a server resource pack, and the crash happens randomly)

**Comment by Vivaan-d** [comment]
The crash log posted on Reddit: https://www.reddit.com/r/admincraft/comments/11nomle/comment/jbo90lf/?context=3

**Comment by electronicboy** [comment]
All that says is that the connection was closed in an unexpected manner, given that your client crashes in the rendering logic due to a supposed missing method suggests an issue with mods installed on the client
