### ISSUE TITLE
Feature Request - Use Caffeine instead of Google Guava

### ISSUE THREAD

**Issue by coderFlameyosFlow** [PaperMC/Velocity#971]
Caffeine has extensions for features like JCache and some more features Guava has, also you get a much less memory overhead.
https://github.com/ben-manes/caffeine

**Comment by Xernium** [comment]
We are already using Guava and switching would require a big api-breaking update. Not quite unplanned but out of scope for now

**Comment by coderFlameyosFlow** [comment]
They have a migration guide from guava to caffeine

**Comment by Xernium** [comment]
I saw that, but that still doesn't constitute any sort of incentive for us to switch. We do welcome contributions however and if this switch can be done in a decent manner we would be open to talking about it/ adding it to the next big milestone
