### ISSUE TITLE
No Component/kick message when denying PreLoginEvent

### ISSUE THREAD

**Issue by daniel-skopek** [PaperMC/Velocity#992]
If I deny PreLoginEvent, the player will not connect, but it will show **Connecting to the server...** and after a while **Timed out** message instead of the intended kick message.

I'm cancelling the event with setResult: `event.setResult(PreLoginEvent.PreLoginComponentResult.denied(Component.text("§cYou cannot connect right now")));`

**Comment by hugmanrique** [comment]
We need details such as the Velocity version, client version, running any other plugins or mods that could affect joins, any proxy services such as tcp shield...

**Comment by daniel-skopek** [comment]
Velocity version: 3.2.0 (247)
Client: tried 1.8.8 and 1.19.3

The Velocity server was not behind TCPShield or any other proxy.

I think other plugins doesn't affect joining because I could join when I removed setResult().

I have similar problem as #689.

**Comment by Nacioszeczek** [comment]
I cannot reproduce this using `3.2.0-SNAPSHOT (git-be9ecf75-b261)`. If the issue still occurs please provide code examples that we can use to reproduce it on the latest version of Velocity.

**Comment by KonusIntelliJ** [comment]
I solved this problem in the method before it in the annotation, change to PostOrder.LAST and everything will work.
