### ISSUE TITLE
Velocity reload command fills /tmp/ with temporary files

### ISSUE THREAD

**Issue by codeHusky** [PaperMC/Velocity#999]
To allow our admins to update our server's config files on-demand without direct velocity perms or console access, we run a script that issues the `velocity reload` command on our proxies continuously while they're up. This allows our config sync system to operate.

With the way Velocity loads configs, specifically [here](https://github.com/PaperMC/Velocity/blob/cc74cf855f2eb0f66301b7448882a405011e8af0/proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java#L456), a temporary file is created of the default config each time a reload occurs which is intended to be deleted on exit. This file never changes with a single boot of the proxy, but is created multiple times in `/tmp/` for no reason, wasting the allocation in there with our particular use case. 

We also always have a "plugin took too long to shutdown" message when we reboot our proxies for updates, which I assume is the `deleteOnExit` calls. For reference on how severe this issue got, our box became almost unusable due to the lack of space in `/tmp` and there was ~9.45 million copies of various versions of the default config file in our `/tmp` folder.

The immediate fix I can see is keeping a single `tmpFile` reference for VelocityConfiguration I'd imagine, although I'll leave that up to contributors / anyone who wants to do a PR for this / me if nobody else does. Either that, or the way this mechanism is working should be revised (perhaps reading it once to a string?) to avoid doing this redundant IO operation on each reload.

In theory, in a system with low RAM or /tmp/ space, this bug could be abused to overflow /tmp with files and render the system unstable quite easily.

**Comment by astei** [comment]
My response to this is: you're doing it wrong. The `/velocity reload` command is intended to invoked _after_ a change is made. It is not meant to be invoked indiscriminately.

> To allow our admins to update our server's config files on-demand without direct velocity perms or console access, we run a script that issues the velocity reload command on our proxies continuously while they're up. This allows our config sync system to operate.

You can only invoke the command with a specific permission, `velocity.command.reload`. In this case, the solution you've devised _is not even required_ - just get a permissions plugin and grant your trusted staff that permission.

> In theory, in a system with low RAM or /tmp/ space, this bug could be abused to overflow /tmp with files and render the system unstable quite easily.

I'll buy there's a DoS bug here and will fix it. But you're doing it all wrong.

**Comment by astei** [comment]
Turns out, the copying of the default config file was some legacy artifact and wasn't needed at all.

**Comment by codeHusky** [comment]
> The /velocity reload command is intended to invoked after a change is made. It is not meant to be invoked indiscriminately.

I can understand that, but the nature of the “bug” here isn’t caused because we’re not doing that. It’s caused purely by the command’s code having an oversight in it, which is now fixed. There’s no reason that we would’ve had to assume reloading the config repeatedly should’ve had this effect in the first place. Plus, it’s just a waste of our time to devise a more-than-necessary complex system to verify a file has been changed before reloading than just send reload commands periodically. The bug would’ve occurred with a more elegant system over time regardless, our solution just accelerated the issue.

> In this case, the solution you've devised is not even required - just get a permissions plugin and grant your trusted stuff that permission.

Also get where you’re coming from on this, but a crafty attacker with access to a compromised staff account and a pretty mundane command could pretty much hard crash a proxy box with that.

Thanks for the fix - disagree with some of the commentary. I know our solution for this isn’t the most “beautiful” in the first place, but it’s far from bad IMO.

**Comment by astei** [comment]
> Also get where you’re coming from on this, but a crafty attacker with access to a compromised staff account and a pretty mundane command could pretty much hard crash a proxy box with that.

They could do a lot worse than "crash your proxy" - that would be one of the _last_ things they'd want to do with a compromised staff account. By definition, that comes with elevated access to your other servers, and I'm pretty sure they would go out to town griefing them before seizing up the proxy (well, without using this issue, which I have now fixed). The permission isn't granted by default anyway (in earlier versions of Velocity it was gated so that only the console could run it, and that's still the default configuration in Velocity).

Or worse, if they obtained shell access to the server running the proxy, _you've already lost_. Nuke the install on the machine and grab a fresh backup.

It's a DoS issue, but you need to have already "jumped the fence" to pull it off, so it's not really a high severity one in my eyes.

**Comment by codeHusky** [comment]
If one hosts a database on the same hardware as their proxy and the proxy begins filling up /tmp/, that puts things into a rather precarious spot. I see what you’re saying but the people going as far as to phish and compromise staff tend to have weird motives. We don’t personally host any critical services on the same machines as the proxies, but if we did and someone was compromised or installed a malicious mod, they could’ve fairly easily do some damage. Regardless, reducing attack surface in general is good to do and I’m happy you quickly addressed the issue for me and everyone else.
